### ISSUE TITLE
Update sitemap with CMS content audit: Home page (0.0) and Getting Started (1.0)

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#1289]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm putting this issue in the sprint although you don't have to start this task until August 9th. This should be submitted for me to review no later than August 16th. After incorporating comments received, upload the final document no later than August 23, 2022.

**Comment by AlexandracmONRR** [comment]
This sprint I will work to complete the the Home page (0.0), Getting Started (1.0), Reporting (2.0), and References (3.0).

**Comment by AlexandracmONRR** [comment]
This sprint I was able to update the Home page (0.0) and Getting Started (1.0). I had to go back and do some editing on my earlier work to make sure it was consistent across the different sections, which is why it took me longer than expected.
