### ISSUE TITLE
Add ability for table cells to have more than one line of content

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#1329]
These two locations are supposed to be on separate lines.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f61a39a7-cd50-4120-a052-cc2201ddc014)

Wireframe:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/626bb3cd-5e7e-4017-ae6a-e70e63673049)

**Comment by mcharg** [comment]
I reviewed all of the tables on the pages listed above and either put in pipes or reworked them to not need multiple lines. Reducing priority to low, since we can definitely launch without this.

**Comment by lpgoldstein** [comment]
It works now.
