### ISSUE TITLE
Add email icons to pages

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#1853]
Creating a separate issue, so we can close out individual page issues, but don't miss pages when we get the icons.

**Comment by mcharg** [comment]
- [ ] [New Reporter Checklist](https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-operator-number)

**Comment by lpgoldstein** [comment]
No
