### ISSUE TITLE
The press release and reporter letters on the homepage have screen reader issues

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/onrr.gov-site#1967]
They read as a single item list and only reads the first item and then jumps to View All.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/df50660d-6e71-422a-82c6-e871ed4943cf)

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/137c920d-d2b0-447e-b5cd-7ff14f164069)

**Comment by eelzi-ONRR** [comment]
This might be resolved by #2706
