### ISSUE TITLE
preview staging bug

### ISSUE THREAD

**Issue by mojobnichols** [DOI-ONRR/onrr.gov-site#2125]
graphql path part created when preview builds

**Comment by Maroyafaied** [comment]
@mojobnichols will have this done by tomorrow so we can start testing the workflow process.  He will do a workaround today to see if it works.

**Comment by Maroyafaied** [comment]
Building preview site in Circle Ci puts undefined in url. Build works locally.  Right now, preview is deployed from a local build unlike dev and production.
