### ISSUE TITLE
Pricing tables: increase rows shown at a time

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2169]
For the NYMEX prices table, the page only shows 10 rows at a time...since NYMEX is by year is there a way to default it to "All" so that it shows all 12 months?

**Comment by cthomasONRR** [comment]
This request is very similar. They are asking for the table rows displayed to be set to "All" but they just want the 12 months shown here too:

"If the user chooses a specific year in a pricing tab, such as "Indian Gas Index Zone > Oklahoma Zone 3 > Year 2020" could the default be "All"?  I understand that having the default as "All" in the general unfiltered page, would not work, but curious if on filtered pages the default can be unique. "

**Comment by eelzi-ONRR** [comment]
Updating this to be for all tables, not just NYMEX. Users asked for this for all pricing tables.

(as per User Research study 13 - Feb '23)

**Comment by greensomes** [comment]
@cthomasONRR, is it ok if we hide the pagination footer for the NYMEX table? I've changed the items per page to be 12 by default.

For the other tables, the default items per page is 10. When a year is selected, the items per page can be changed to 12 and the pagination can be hidden.

When a year is not selected in the other tables, what should we update the items per page to be? 25?

**Comment by Maroyafaied** [comment]
@greensomes Christine is out today but I have added @eelzi-ONRR to this issue to help with these design questions. Thanks!

**Comment by cthomasONRR** [comment]
@greensomes - 

Since for NYMEX you can only select 1 year at a time, I think it's ok to remove the pagination footer once the items per page is 12.

For other pricing tables, can we get the default to be 12, even when a year isn't selected? Then keep the pagination footer since multiple years can be selected?

**Comment by greensomes** [comment]
@cthomasONRR, 

Let me see what kind of control I have over the pagination component. I'll see if there's a property for overriding the select list options for items per page.

**Comment by greensomes** [comment]
@cthomasONRR, I figured out how to set the options property. I was thinking 12, 24, 36, 48, All. What do you think?

**Comment by cthomasONRR** [comment]
@greensomes I agree- all of those options would be good!

**Comment by greensomes** [comment]
@cthomasONRR, 

The changes to all pricing tables have been deployed to [dev](https://dev-onrr-frontend.app.cloud.gov/references/valuation) for review. Thanks!

**Comment by cthomasONRR** [comment]
@greensomes I just reviewed and it looks great! Thanks!
@eelzi-ONRR Do you also want to review?

**Comment by eelzi-ONRR** [comment]
@greensomes I tested out all the tables on the Valuation and Indian pricing pages and applied different filter settings - the new options work for all of them!
