### ISSUE TITLE
Pricing table filters not working when clicking between pricing tabs

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2171]
https://beta.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

If you jump from one price tab to another, the option to use the drop down filters does not work, or in some cases the prices disappear, and I have to use F5 to refresh the site.

**Comment by Maroyafaied** [comment]
one option is to reset the filters when switching tabs

**Comment by Maroyafaied** [comment]
This has been resolved.
