### ISSUE TITLE
Strategize ways to improve accessibility

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2216]
Ideas for the next round of accessibility testing:

- Automate the process or have to do it page by page?
- How to test for accessibility for people who don’t use screen readers.?
- Trusted tester program?
- Follow the USWDS?
- Use Wave or Axe to test?
- US Web Design System Standards- make sure we are indeed following

Using OCIO report, tools listed above, and what we learn from trusted tester training, make plans for any needed manual testing and implementing improvements.

**Comment by eelzi-ONRR** [comment]
https://fae.disability.illinois.edu/ - a free site checking tool we might want to consider. It will check the entire site up to 3 levels of navigation, so we don't have to go page by page

**Comment by cthomasONRR** [comment]
From a listserv email response to our blog post: 

You may want to install the [ANDI](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssa.gov%2Faccessibility%2Fandi%2Fhelp%2Finstall.html&data=05%7C01%7Cchristine.thomas%40onrr.gov%7C51240aeb7f1a443fa9b608dacbe04749%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638046461390277020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=GE86Wj9N0h3m9f73GsRKQGoT7WfFMnm0fdz9pDWN2H0%3D&reserved=0) browser bookmarklet and check results. It finds some accessibility errors in that blog page. ANDI is  a free and easy-to-“install” bookmarklet sponsored by the Social Security Administration.

Another free utility is the [WAVE](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwave.webaim.org%2F&data=05%7C01%7Cchristine.thomas%40onrr.gov%7C51240aeb7f1a443fa9b608dacbe04749%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638046461390277020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=pFFUPY%2FDA1OJumObC%2Fp%2BYdWi%2FmI%2FnnXVnkaAXMUj3mM%3D&reserved=0) online or brwoser extension from WebAIM. It shows 6 alerts. 
(We use ANDI for even web app testing but sometimes use a scree capture of some WAVE results when briefing managers.)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR do you think we still need this issue? I think the annual assessment forces us to do this more regularly and methodically, and what we discussed this week at sync-up is the plan to get through our backlog

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Yeah I agree this can be closed. Will close now.
