### ISSUE TITLE
bug in hero image 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2309]
https://www.onrr.gov/references/rulemakings/ad00

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/9e1826e7-001b-436e-851a-d6e2c7523df3)

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm going through the rulemakings pages to see if I can find any others that have this issue. It looks like maybe we were testing alt text and forgot to remove it.
