### ISSUE TITLE
Update "Primary Contact" info. under the "Litigation Support Team" Banner

### ISSUE THREAD

**Issue by KristianL3101** [DOI-ONRR/onrr.gov-site#2325]
If your request is to add or update contact information, PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-contact-information)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact location (header) within the webpage where the contact information is located
* Specify if is an update of an existing contact, or a new contact entry
* Specify what contact information (if any) needs to be removed
* Give us the exact updated/new contact information to add

THANK YOU
______________________________________________________________________________________________________________________________________
https://www.onrr.gov/compliance-enforcement/enforcement?tabs=contacts
Under "Litigation Support Team"- "Primary Contact" Please update existing contact Michael Marchetti to Cindy Hergenreder. Email: Cindy.Hergenreder@onrr.gov Phone: 303.231.3557

Thank you.

**Comment by lpgoldstein** [comment]
@KristianL3101 Ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/compliance-contacts?tabs=enforcement-litigation-support

**Comment by KristianL3101** [comment]
Hello,

Michael Marchetti still needs to be listed alongside Cindy as the "Manager" just like he shows above the "Litigation Support" section in "Enforcement Teams".

Cindy is the "Primary Contact", and Michael is the "Manager".

Thank you.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, December 2, 2022 9:46 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update "Primary Contact" info. under the "Litigation Support Team" Banner (Issue #2325)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7Cde3099fd040c4e1c9d3d08dad484ce21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638055964125705633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fWEQAjLU9NQOpSqjvHfcIz0ZxisattL8%2FzkqHFTdgMk%3D&reserved=0> Ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/compliance-contacts?tabs=enforcement-litigation-support<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fcompliance-contacts%3Ftabs%3Denforcement-litigation-support&data=05%7C01%7Ckristian.lee%40onrr.gov%7Cde3099fd040c4e1c9d3d08dad484ce21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638055964125705633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QDKdKV1x3VCKNu%2BWD5Y%2BtEVH2aujdXYaiKPwNIqDaJw%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@KristianL3101 I've changed it back to Program Manager to match the other contact cards  https://dev-onrr-frontend.app.cloud.gov/about/contact/compliance-contacts?tabs=enforcement-litigation-support

**Comment by KristianL3101** [comment]
Thank you. Looks good.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, December 2, 2022 10:06 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update "Primary Contact" info. under the "Litigation Support Team" Banner (Issue #2325)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7C743289875f3c415ece1008dad4877ee9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638055975661372873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SEFwV%2Fy%2FmFSA6Gd8fQVCpOv4XE5%2FRTlpEKlOwHQoscc%3D&reserved=0> I've changed it back to Program Manager to match the other contact cards https://dev-onrr-frontend.app.cloud.gov/about/contact/compliance-contacts?tabs=enforcement-litigation-support<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fcompliance-contacts%3Ftabs%3Denforcement-litigation-support&data=05%7C01%7Ckristian.lee%40onrr.gov%7C743289875f3c415ece1008dad4877ee9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638055975661372873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KisKEGoekcuZ8e9BG96LcEfGFX%2FAc6RRbwMlC1DlfnA%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@KristianL3101 It's live! https://onrr.gov/about/contact/compliance-contacts?tabs=enforcement-litigation-support

**Comment by Maroyafaied** [comment]
Not sure why this issue reopened. closing it again
