### ISSUE TITLE
Discuss plan for standardizing CMS tags

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2455]

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Thanks for meeting up! Here's the excel with total FY22 downloads for onrr.gov:
[onrr_gov_Top_Events_Downloads_FY22.csv](https://github.com/DOI-ONRR/onrr.gov-site/files/10757757/onrr_gov_Top_Events_Downloads_FY22.csv)

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - thanks for the productive meeting and sending that PDF. 

Below are the outcomes from our meeting:

**Tagging within the CMS**: In CMS user guide, update tagging guidance with a few bullet points that discusses using breadcrumbs, tagging with spaces, etc. This will help to create more standardized tagging across documents and images in the CMS.
     **I will create an issue to make these changes to the user guide.**

**Tagging within PDF documents**: We should prioritize the top downloaded documents to incorporate tagging elements that will make them searchable (indexed by Search.gov). This prioritization may also transfer to accessibility improvements within these top documents. 
- PDFs searchable (https://search.gov/indexing/pdf-metadata.html): Adding metadata into PDF using “Document Properties” in Adobe Acrobat with a title, description, key words (separate keywords using a comma)
    **I will create an issue to prioritize PDF documents for tagging.**

**Tagging Discussion with Search.gov**: We will set-up a meeting with someone at Search.gov to discuss tagging documents and using the tags within our current CMS. This conversation should happen in coordination with the topics of Search Engine indexing that @eelzi-ONRR is also researching/working on.
     **I will coordinate with Erin on this meeting and discussion points.**
