### ISSUE TITLE
Research page tags for site indexing in Search.gov

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2456]
Research the location for tags that will allow Search.gov's in-house indexing to read tags and direct users to correct page. This will include tags for 2nd level tabs.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I already created an issue for standardizing existing CMS tags: https://github.com/ONRR/onrr.gov-site/issues/2455

Let's coordinate to see who wants to do what

**Comment by eelzi-ONRR** [comment]
Info on how search.gov uses PDF metadata for indexing https://search.gov/indexing/pdf-metadata.html

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - main takeaways from this article:

- Make PDFs searchable by adding metadata into PDF using “Document Properties” in Adobe Acrobat: Add title, description, key words (separate keywords using a comma)
- Declare file language: in most cases it should be declared as “English”
- Create HTML landing pages for your PDFs: if you are looking to direct traffic to PDFs, you may consider creating an HTML landing page that is SEO-optimized using traditional semantic metadata


I'm also keeping track of tagging information here: 
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/508/Search%20Engine%20Accessibility/Search.gov%20-%20Tag%20Indexing%20and%20Improvement.docx?d=waa9d713daeb34626ba24b802c328d494&csf=1&web=1&e=7ACtDG

**Comment by eelzi-ONRR** [comment]
I've been looking into the search.gov information on metadata, what metadata other search.gov sites have on their pages, and how directus handles metadata. I'm putting my findings, notes, and questions for search.gov in a shared doc: https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EcQ0MtHoq3RBoIiMsXY1Jl4BdZxmXEqr2v710qH8--ZMWA?e=YrSWDP

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - I've edited and added to the document that you put together. Also, I've drafted an email to Search.gov; after you've reviewed on Tuesday (2/28), we can send to Search.gov and schedule a meeting with them!
