### ISSUE TITLE
Test new workflow for publishing content on live site 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2461]

**Comment by eelzi-ONRR** [comment]
@greensomes @Maroyafaied  I added and ran the flow for 511 redirects on Feb 10. None of the ones I've spot checked are working as expected in prod. They are working in dev, so it seems the flow didn't work.

**Comment by eelzi-ONRR** [comment]
Retested redirects after Jeff made changes and now it works!

**Comment by Maroyafaied** [comment]
I tested adding and deleting a link in one of the webpages and everything worked!

**Comment by cthomasONRR** [comment]
Jessica and I added text to a webpage, and the publishing workflow was perfect!

**Comment by lpgoldstein** [comment]
Jessica and I just edited text on a webpage and the publishing workflow was so easy!
