### ISSUE TITLE
Intro to team & sprint meeting - Maroya & Jessica 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2470]

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BD43052B2-199D-4C74-9E7D-42C3C0110D50%7D&file=Meet%20the%20team.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1676302053146&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=bd3ad299-a883-4d2f-927f-4664f937e55c

**Comment by bowlenj** [comment]
I requested access to the share point document so I can review it.  If I close this issue can I still access the link?

**Comment by Maroyafaied** [comment]
@bowlenj  I granted you access. You can download and save the file and yes you can access the link after you close the issue. Thanks
