### ISSUE TITLE
Access & Tour to CMS - Christine & Jessica 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2471]

**Comment by bowlenj** [comment]
Good Morning!  I was able to get access to CMS this morning.  I scanned the QR code and went through the steps on my phone to add the password and it finally gave me the verification code.  I never did get an email.

**Comment by cthomasONRR** [comment]
@bowlenj Awesome, so glad you got in! Sorry it's such a weird process! Please let me know if you have any more questions about the CMS or would like to meet again to do another walk-through!

**Comment by bowlenj** [comment]
No problem, I appreciate all your help getting setup with ZenHub and CMS yesterday!  I think I'm good on the walk through.  Once I'm able to start uploading presentations I think I'll understand more.
