### ISSUE TITLE
Add publishing flows for files & Test 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2474]

**Comment by greensomes** [comment]
The file flow has been added for the four pricing publishing flows.

**Comment by greensomes** [comment]
Publishing flows for the following collections need to be updated to include the file embedded flow:

- Pages (`hero_image`, `file`)
- Report Letters (`file`, `accessible_file`)
- Plant-specific UCA (`file`)

**Comment by greensomes** [comment]
The reporter letters publishing flow has been updated. The flow is called for both the `file` and `accessible_file` fields.

**Comment by greensomes** [comment]
The plant-specific UCA publishing flow has been updated.

**Comment by Maroyafaied** [comment]
@greensomes I'm testing in dev with new files, the icon doesn't show up for a word doc. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/75bcc086-8089-447b-adc3-3b6ea14177ca)
