### ISSUE TITLE
NRRD Content Audit - Explore Data

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2476]

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review

**Comment by Maroyafaied** [comment]
@cthomasONRR great job, I added some comments.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, I just fixed those hierarchy numbers.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks, I had a couple of comments in the content description column.

**Comment by cthomasONRR** [comment]
@Maroyafaied Sorry, the comment indicator is so small! I definitely missed those. I just finished fixing and addressing those comments.

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks for reviewing! Closing this issue now.
