### ISSUE TITLE
Update wiki: release changes to production page 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2479]
@AlexandracmONRR I'm putting this in next sprint for you to take the lead to update this [page ](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Releasing-changes-to-production-for-the-new-CMS) and for @cthomasONRR to review

Update with instructions and a visual showing the workflow.

**Comment by Maroyafaied** [comment]
This is the issue where we had a visual diagram showing the publishing workflow process before https://app.zenhub.com/workspaces/open-data-design--development-5464fa79c3cc8d7f4c384eaf/issues/gh/doi-onrr/onrr.gov-site/1797

**Comment by AlexandracmONRR** [comment]
Draft of updated CMS Userguide Wiki - Release change: 

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Wiki%20Guides/CMS-WikiUpdate-ReleaseChangestoProd-03092023.docx?d=w84a72a6846964f05867c6f14143cefad&csf=1&web=1&e=cNVn2L
