### ISSUE TITLE
Take out production box and reviewed check box in CMS

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2480]
This workflow was meant to be used in preview/staging so there's no need for it. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/4b21d985-055b-4491-b97b-da4e4e836730)

**Comment by greensomes** [comment]
There were two graphQL queries that contained the production field that have been updated. After deploying the code and removing the field from the pages collection config, it was necessary to clear my browser cache to avoid errors.
