### ISSUE TITLE
Change the format of info and alert boxes on federal valuation examples

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2482]
The existing indian examples incorportae the alert and info boxes into the rest of the content, using the full available width for the boxes: https://onrr.gov/references/valuation/ipmp?tabs=detailed-example,pc-03

RV would like 2016 Valuation Rule Federal Processed Gas Reporting and Percent-of-Proceeds (POP) Contract Reporting Pre-2016 to match this formatting instead the current fortting, which has the alert and info boxes in their own column.
https://onrr.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-07&panel=assumptions
https://onrr.gov/references/valuation/pop-example?tabs=detailed-example,disallowed-costs&panel=disallowed-pipeline-plant-fuels

The intent is to reduce scrolling for users. Removing the alert and info moves from their own column will allow the rest of the content to also be full width so the page will be shorter.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Do you have time to review:

2016: https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-03

POP: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example?tabs=detailed-example,net-value-received

**Comment by eelzi-ONRR** [comment]
@cthomasONRR All the alert and info boxes look good! I found a few steps on the POP example where I think it's set correctly to full width, but there's a line break in the content so it doesn't actually go full width.

 https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-03
Steps 2 & 4

https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,transportation-allowance
Step 5

https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,processing-allowance
Step 2

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks for catching! Those are all fixed now if you want to quickly review again.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks great!

**Comment by cthomasONRR** [comment]
Updates are now correct on the live site. Closing issue.
