### ISSUE TITLE
IESC Contact Updates

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2488]
Please update this webpage - https://www.onrr.gov/indian/indian-references?tabs=contacts,indian-energy-service-center-iesc-contacts, as shown on the attached word document.  Please let me know if you have any questions.  I will have Amanda Garrison and Heather Cillessen review for approval once updates are made in Dev.

Thank You
Jessica Bowlen
______________________________________________________________________________________________________________________________________

[IESC Contact Updates.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/10798467/IESC.Contact.Updates.docx)

**Comment by bowlenj** [comment]
@ONRRamandagarrison, This is ready for your review - https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=contacts,indian-energy-service-center-iesc-contacts

**Comment by lpgoldstein** [comment]
Approved via Teams chat. Published.
