### ISSUE TITLE
DISC Contact Update - Share Spreadsheet

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2489]
Please process updates on the shared "Contacts Spreadsheet - To Update" all updates and additions have been highlighted.  Please let me know if you have any questions.

THANK YOU
Jessica Bowlen

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by bowlenj** [comment]
Hi Lindsay,

I found 2 things:

  *   Lease & Agreements - Shannon is still showing as a contact for offshore.  Can we remove her from offshore completely?  It should only have David as primary and Mary as supervisor.
  *   Onshore Production - Companies starting with O, Jeannette Amariles email needed to be changed to show Jeannette's instead of Kerri's.

Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, February 22, 2023 9:43 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Update - Share Spreadsheet (Issue #2489)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ce6d73071da6d41e8eb0308db14f3e31c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638126809941878690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5VzOcOmPdnS1PpyVbLKXjR9z1W%2BLk0bciuQcmJBJjrU%3D&reserved=0> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fproduction-contacts%3Ftabs%3Dcontacts%2Conshore-production&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ce6d73071da6d41e8eb0308db14f3e31c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638126809942034906%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BJqEsWYC4unzYd0Pxl2K3fn1Vd0F3fWuCCkEoqZHOBw%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@bowlenj has approved content and will publish once other contact issue is approved.

**Comment by lpgoldstein** [comment]
Published.
