### ISSUE TITLE
Flow issue - late payment interest

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2501]
We tried to use the flow button to publish a new entry in both late payment interest collections. The flow said it was successful, but the update did not appear on the live site. Maroya had to do a dev>main code update for it to go live. We're not sure if there's something wrong with the flow, or if having a code update in dev (removing the "reviewed" button) affected things.

**Comment by greensomes** [comment]
This issue appears to be resolved. The step to read the item from dev CMS was returning FORBIDDEN for unknown reasons. It's a read-only operation that is available to all users. I changed the step to be a web hook that calls the API directly. Data is being returned as expected and the publish flow completed successfully.

**Comment by Maroyafaied** [comment]
@lpgoldstein please test in the CMS by adding a line in the bottom of the table.
