### ISSUE TITLE
Analyze pricing tables research

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2502]

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @cthomasONRR @AlexandracmONRR @Maroyafaied The spreadsheet has been filled in and is ready for review. I have yet to add the write up, but want to wait to see if any insights or recommendations get added before I do that: 
https://docs.google.com/spreadsheets/d/15xrc08le5mYEllWOoRQQV2o9L6-0xNPXGK5bcI25Zbo/edit?usp=sharing 

Once we're ready to move the sheet to Teams/Wiki, I'll move the notetaking and combinded/dedpued tabs into a separate file since those are our raw notes. That one will live in Teams only, but all the other tabs are good to share on the wiki

**Comment by Maroyafaied** [comment]
@AlexandracmONRR @Maroyafaied  please review

**Comment by AlexandracmONRR** [comment]
I have reviewed and left comments/feedback where necessary. @Maroyafaied - feel free to close after your review.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Great Job. I added a few comments/questions. My comments are in the recommendations tab column A row 2, 3, 6, & 7. Also there is a comments in the groupings & trends tab column E row 4.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @AlexandracmONRR Thank you both so much for your additions and comment! Having fresh eyes catch recommendations and opportunites we missed is exactly what I was hoping for :)

I made adjustments accordingly and replied to each comment. I'll make issues for each recommendation
