### ISSUE TITLE
Test meta title and meta description

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2504]
Test to see if adding a meta title or meta description helps with indexing

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I put this issue in this sprint since I believe its for testing the meta title description in the cms for tabs.

**Comment by eelzi-ONRR** [comment]
Added a meta description to the [Valuation and Pricing page](https://onrr.gov/references/valuation) that includes tab names we know are not currently indexing. Submitted the URL to Google and Bing for reindexing

**Comment by eelzi-ONRR** [comment]
The meta description is showing up in the metadata for the page, but none of the seearch engines have reindexed the page yet. 

Google wants us to mark this URL as canonical, otherwise it indexes the valuation page from the old site instead. I'm going to open a ticket for next sprint to monitor the reindexing and look into marking the URLs from the new site as canonical
