### ISSUE TITLE
Temporary license and training

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2516]
Sid will give @eelzi-ONRR access to a temporary licenses to be able to pull accessibility reports for our website. Sid will also send a training video.

**Comment by eelzi-ONRR** [comment]
Completed the training video and readings, but I think we should wait to get the temporary license until we know we have made enough site improvements to warrant a new report. Especially since Sid went ahead and ran a NRRD report - we're no longer waiting on that.
