### ISSUE TITLE
KAULEY VIRTUAL OUTREACH MEETING                           (Add to Event Calendar)

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2519]
KAULEY VIRTUAL OUTREACH MEETING
Thursday, December 16, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a Virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session. 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Oklahoma region.
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015 prior to the meeting. The OKC Outreach office hours are Mon.- Fri. from 8:00 am-4:30 pm.

CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or our main number at (405) 879-6050.  
EMAIL: [onrroutreachokc@onrr.gov]

FORT WASHAKIE – WIND RIVER IN-PERSON OUTREACH
Wednesday, March 22, 2023
9:00 am - 12:00 pm MST

Location:  Bureau of Indian Affairs, Wind River Agency, 1st & Washakie Street, Fort Washakie, Wyoming, 82514

Description: Representatives from the Office of Natural Resources Revenue will host a Question-and-Answer session for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the BIA, BLM, and the BTFA have been invited to be in attendance to answer questions.

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Fort Washakie, WY, Wind River Reservation, and surrounding areas.

Other Information: Please contact the ONRR Denver Outreach Office at (800) 982-3226 for more information.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.

Contact:  ONRR Denver Outreach Office, Toll Free (800) 982-3226.   Email: [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by eelzi-ONRR** [comment]
@Toddsand21 The Kauley meeting has a date listed of Thursday, December 16, 2022 - is that correct?

**Comment by Toddsand21** [comment]
No. It is Thursday, March 16, 2023

**Comment by eelzi-ONRR** [comment]
@Toddsand21 This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by eelzi-ONRR** [comment]
Approved via Teams

@Toddsand21 This is now live so I'm closing the issue
https://onrr.gov/events
