### ISSUE TITLE
Update Feb NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2522]
Good morning,

Please update the Feb NYMEX prices on onrr.gov according to the attached data.

Thanks!

@sudarr
[NYMEX022023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/10883677/NYMEX022023.xlsx)

**Comment by AlexandracmONRR** [comment]
@boices 

Thanks for the update. Please review the dev site to ensure the update is correct: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

After I receive your approval, I will publish!

Thanks,
Alex

**Comment by boices** [comment]
@AlexandracmONRR that's perfect! Thanks again!

**Comment by AlexandracmONRR** [comment]
@boices Thank you! We are working on an issue for publishing to our live site. Do you need this up by today or can it wait until Monday?

**Comment by boices** [comment]
I think Monday would be just as well.

**Comment by AlexandracmONRR** [comment]
@boices - the NYMEX Feb prices are published - thank you for your patience!
