### ISSUE TITLE
Change tab label tags to <div> so they index correctly in search.gov

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2529]
According to our emails with search.gov, our tab labels need the div tag to index correctly:

![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/a1cd5f50-618d-4eb9-ba9d-0f1f12340c2b)

**Comment by eelzi-ONRR** [comment]
Another email from Amani at search.gov confirming that div tags will improve indexing of tab labels:

![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/0d3a3323-a864-49a9-b8c6-6f7ba50fa5a3)

**Comment by Maroyafaied** [comment]
This is no longer necessary since we added meta descriptions to all the tabs within the CMS.
