### ISSUE TITLE
March 2023 Indian Index Zone prices

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2530]
Hello, the March Indian Index Zone prices are ready for posting to ONRR.gov. The data can be found in the usual file "Data for ONRR.gov.xlsx". Can you please make sure that the prices ending in zero display the price to the thousandths place? Thanks!!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej Here is the spreadsheet that we upload to the CMS. To further reduce chance of error on our end, could you please use this spreadsheet as a template for your monthly prices? We upload an individual spreadsheet each month. Please let me know if you have any questions or Damion is familiar with this as well if you have any questions. 
[2023_02.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/10932291/2023_02.xlsx)

**Comment by penvosej** [comment]
Hi Lindsay,

I was in a class this morning so I'm just getting to it now. I didn't know there was any new procedure and Damion didn't expand much on his spreadsheet. So are we doing a new file every month? Do we upload the file in the GitHub request? Or do we save it somewhere and you access it from there? I thought we used the DataforONRR.gov file because we didn't want unpublished data available for the public to see within GitHub. Am I wrong, or is this not a concern anymore?

Thanks,
Jessica

From: lpgoldstein ***@***.***>
Sent: Thursday, March 9, 2023 6:59 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] March 2023 Indian Index Zone prices (Issue #2530)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cc8a52fc6773149c22c7708db20a671b8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638139671888387601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ry4u9qRX5CcgShF4sSmCLyZFUDRCHDasAvSi%2BnyCPqg%3D&reserved=0> Here is the spreadsheet that we upload to the CMS. To further reduce chance of error on our end, could you please use this spreadsheet as a template for your monthly prices? We upload an individual spreadsheet each month. Please let me know if you have any questions or Damion is familiar with this as well if you have any questions.
2023_02.xlsx<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDOI-ONRR%2Fonrr.gov-site%2Ffiles%2F10932291%2F2023_02.xlsx&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cc8a52fc6773149c22c7708db20a671b8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638139671888387601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zqVa%2BgO7srQysBBtSMGg5rBBgf%2FxkEtJAmzGZ%2FzzJrs%3D&reserved=0>

-

**Comment by lpgoldstein** [comment]
file sent to webmail box and approved via teams chat

**Comment by lpgoldstein** [comment]
live and closing issue.
