### ISSUE TITLE
Review CMS wiki: release changes to production page

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2533]

**Comment by AlexandracmONRR** [comment]
Userguide Wiki Text:
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Wiki%20Guides/CMS-WikiUpdate-ReleaseChangestoProd-03092023.docx?d=w84a72a6846964f05867c6f14143cefad&csf=1&web=1&e=OABfRP

Work Flow PDF: https://doimspp.sharepoint.com/:b:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Wiki%20Guides/CMS-ProdRelease-WorkFlow-V1.pdf?csf=1&web=1&e=ekMcjc

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I really like how you did the diagram . I reviewed and added comments to the text and the diagram, I had to save the diagram as a pdf to be able to comment (attached). We can discuss my comments on Monday after Christine reviews as well. Thanks for working on this! [https://app.zenhub.com/files/210892300/1c51562a-3a9c-44ec-8223-ac814ca0f1c9/download](https://app.zenhub.com/files/210892300/1c51562a-3a9c-44ec-8223-ac814ca0f1c9/download)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I added comments in the word doc and attached are my comments for the PDF. Maybe let's have a short meeting to discuss and make sure we're all in agreement?
[publishflow_CLT.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/10958344/publishflow_CLT.pdf)

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - I've added the new work flow here: https://doimspp.sharepoint.com/:b:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Wiki%20Guides/CMS-ProdRelease-WorkFlow-V2.pdf?csf=1&web=1&e=Q8hIs4

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - I've made updates to the release text and the workflow here: https://github.com/DOI-ONRR/onrr.gov-site/wiki/Releasing-changes-to-production-for-the-new-CMS

When you get the chance, would you review it and let me know what edits I should incorporate into the final draft?

**Comment by cthomasONRR** [comment]
@AlexandracmONRR This looks great!

Would it be possible to make the flow chart image larger? I have to zoom in to read it. (Wish GitHub would open a larger version of the image in another window like the blog does!)

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - thanks for your review!  I agree it was harder to read when the size was reduced. I've made it so that the flow chart is as big as the page permits.

I'm closing this issue now.
