### ISSUE TITLE
Create new onrr.gov powerpoint template 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#2534]

**Comment by eelzi-ONRR** [comment]
@lpgoldstein These are ready for review: https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Template-PowerPoint/ONRR-ONRRgov-PowerPoint-Template%20(1).pptx?d=waf579b9d45dc4f1ba74bf2a20b96170d&csf=1&web=1&e=ystvDn

**Comment by lpgoldstein** [comment]
Thanks @eelzi-ONRR and @AlexandracmONRR . This one looks great!
