### ISSUE TITLE
Revisit User Research for Main Navigation

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2538]
Users avoid using the main navigation because they don't know where to look for what they need

(as per User Research study 13 - Feb '23)

See what we can parse from the previous user reserach on the main nav. Plan for more reserach as necessary

**Comment by Maroyafaied** [comment]
Here are some blogs that might be helpful 

https://blog-nrrd.doi.gov/stakeholders/

https://blog-nrrd.doi.gov/card-sort/

https://blog-nrrd.doi.gov/treetest/
