### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – March 2023

### ISSUE THREAD

**Issue by HammenONRR** [DOI-ONRR/onrr.gov-site#2543]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “March 2023 Lease Agreement XREF.txt" and "March 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 3/13/2023.

[March 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/10958595/March.2023.Lease.Agreement.XREF.txt)
[March 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/10958605/March.2023.Lease.Agreement.XREF.xlsx)

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I assigned this issue to you, please reach out to Lindsay if you need any help. Thanks

**Comment by AlexandracmONRR** [comment]
@HammenONRR - thank you for the update. 

Please review the following link: 
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

After I receive your approval, I will publish to the live site.

Thanks,
Alex

**Comment by HammenONRR** [comment]
Everything looks good. Please move the link to the live site.

Thanks!

**Comment by AlexandracmONRR** [comment]
@HammenONRR - the update is now live. Thank you!
