### ISSUE TITLE
Add meta descriptions to pages with tabs

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2553]
This helps the tab lables to be indexed by Google and search.gov

**Comment by Maroyafaied** [comment]
@Maroyafaied link for content audit.

**Comment by lpgoldstein** [comment]
Done with my sections

**Comment by jessmanko** [comment]
Completed my sections

**Comment by eelzi-ONRR** [comment]
Completed my sections and double checked  Jessica and Lindsay's pages. 

@lpgoldstein can you check the ones I did?

**Comment by lpgoldstein** [comment]
@eelzi-ONRR looks good!
