### ISSUE TITLE
Update DISC Contacts

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2558]
Please process updates on the shared "Contacts Spreadsheet - To Update" all updates and additions have been highlighted. Please let me know if you have any questions.

THANK YOU
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

These contact updates are in dev: https://dev-onrr-frontend.app.cloud.gov/about/contact
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great! These changes are now live: https://onrr.gov/about/contact

Closing this issue now.
