### ISSUE TITLE
CHOCTAW CITIZENS CENTER OUTREACH

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2561]
CHOCTAW CITIZENS CENTER OUTREACH
Thursday, April 5TH, 2023
10:30 am to 1:00 pm CST

Location:  Choctaw Senior Citizen’s Center, 707 Bond Street, Crowder, OK 

Description: The Office of Natural Resources Revenue (ONRR) will attend the Choctaw Senior Citizens Center in Crowder, Oklahoma to hold outreach sessions with Choctaw senior citizens who are Indian mineral owners, IIM account holders, Indian Trust property owners. Representatives from and the Bureau of Indian Affairs (BIA) will also be in attendance. The ONRR & BIA representatives will be available from 10:30 am – 1:00 pm to discuss topics regarding Indian oil & gas leases, and Indian trust property and realty issues.  Owners will have an opportunity to ask questions with the representatives during that time.  Please bring any documents or correspondence with you that you want to discuss.

Who Should Attend:  Choctaw senior citizens who are Indian mineral owners, IIM account holders and or Indian trust property owners in the Crowder, OK and surrounding areas.
Other Information: To get more information on this event please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 8:00 am-4:30 pm.

Contact: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or Main No.
(405) 879-6050.  EMAIL: [onrroutreachokc@onrr.gov]

Fargo, ND – Sisseton-Wahpeton In-Person Outreach
Wednesday, April 5, 2023
5:00 pm - 7:00 pm CST

Location:  Wingate by Wyndham, Meeting Room, 4429 19th Avenue South, Fargo, ND  58103
Description: Representatives from the Office of Natural Resources Revenue will host a Question-and-Answer session for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions.
Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Fargo, ND, Lake Traverse Reservation, Sisseton-Wahpeton Agency, Minnesota Agency, Fort Totten Agency, and surrounding areas.
Other Information: Please contact the ONRR Denver Outreach Office at (800) 982-3226 for more information.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.
Contact:  ONRR Denver Outreach Office, 
Toll Free (800) 982-3226, [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

SHAWNEE AREA VIRTUAL OUTREACH
Thursday, April 20, 2022 
1:00 PM– 2:00 PM CST

LOCATION: By Telephone

Description: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office.  Representatives from each of the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and agency updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

Who Should Attend: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains region in Oklahoma. 

Other Information: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. Office hours are Mon- Fri., 8:00 am-4:30 pm CST. 

Contact: ONRR OKC Outreach Office, PHONE: (800) 354-7015 (toll-free)
EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

CONCHO AREA VIRTUAL MEETING
Thursday, April 27, 2023
1:00 pm to 2:00 pm CST

Location:  By Telephone

Description: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian oil & gas leases, IIM accounts, and Indian trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

Who Should Attend:  Indian mineral owners, IIM account holders and other Indian trust property owners in the Concho Agency area or any Indian mineral owners in the Southern Plains area in Oklahoma.
  
Other Information: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 8:00 am-4:30 pm.

Contact: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or Main No.
(405)879-6050.  EMAIL: [onrroutreachokc@onrr.gov]

**Comment by eelzi-ONRR** [comment]
@Toddsand21 This is ready for review and approval to push live

https://dev-onrr-frontend.app.cloud.gov/events

Thanks!

**Comment by Toddsand21** [comment]
Take out "and" in this first paragraph in the Description under Choctaw that reads   " Representatives from and the Bureau "

**Comment by eelzi-ONRR** [comment]
@Toddsand21 The "and" has been removed

https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
Just at a glance everything looks good.  Can we make changes after it goes live?

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Absolutely! I'll push live now and we can always review again on Monday

**Comment by Toddsand21** [comment]
Sounds good! Lets do it! Thanks!

**Comment by eelzi-ONRR** [comment]
@Toddsand21 All four events are now on the live page so I'm closing this issue: https://onrr.gov/events

Thanks!
