### ISSUE TITLE
Update FIMO contacts 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2562]
@lpgoldstein this request came through the IT help desk, I emailed Michelle and included you.

 Description: https://www.onrr.gov/indian/indian-references?tabs=contacts,federal-indian-minerals-office-fimo-contacts&panel=fimo-headquarters-contacts
 
Please add the following people to the FIMO Auditor (ONRR) contacts:
 
Cynthia Alexandar
han.alexander@onrr.gov
 
Sandra Ashford
sandra.ashford@onrr.gov
 
Also, please remove Annette Ahill from the FIMO Lease Administration (BIA) as she has retired.
 
Please let me know if you have any questions.
Thank you!!

**Comment by lpgoldstein** [comment]
Approved via email.
