### ISSUE TITLE
Valuation and Pricing webpage - contacts

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#2567]
We recently found that pricing questions are not being diverted to MSA.  On the 'Valuation & Pricing' page we realized that to see the contacts tab, users will have to know to scroll to the right and they may not see this.

I found that with my browser set at 100%, I need to scroll to the right to see the contacts...but if I reduce the size to 90% in MS Edge, then the contacts tab fits on the webpage. For Chrome, I need to reduce the size to 80% for the contacts tab to fit on the webpage.

One solution that was discussed was to place the contact email on the 'Pricing', 'Unbundling', and 'Valuation Regulations' tabs for each of the three different groups.  For instance, on the 'Pricing' tab, above the tabs for the individual prices, we could have the MSA email contact for questions in regard to pricing.

If you have any alternate thoughts on how we can ensure the users will be able to contact each group for their questions, then we would be grateful to hear them.

Thanks,
Cory Forgrave
@sudarr

**Comment by eelzi-ONRR** [comment]
@forgravec Thanks for letting us know there's an issue with users finding the contacts they need for pricing questions. Let me talke a couple days to try out your suggestion and see if I come up with any other ideas. I'll get some drafts to you later this week.

-Erin

**Comment by forgravec** [comment]
Thanks, I appreciate it.

Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, March 28, 2023 12:59 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Valuation and Pricing webpage - contacts (Issue #2567)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7C8e30979c10ef45b7751c08db2fbe8e94%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638156267706170626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5%2FHLgukZlVUNYe6UADf%2BhVk8M02E2OhXXrM34TxeiUs%3D&reserved=0> Thanks for letting us know there's an issue with users finding the contacts they need for pricing questions. Let me talke a couple days to try out your suggestion and see if I come up with any other ideas. I'll get some drafts to you later this week.

-Erin

**Comment by eelzi-ONRR** [comment]
@forgravec We looked at this and decided that it deserves additional research. However, in the meantime we still want to make sure users can more easily find the contact info they need, so we added a simple contact statement to the pricing, unbundling, and valuation tabs - similar to what you suggested.

https://dev-onrr-frontend.app.cloud.gov/references/valuation

**Comment by forgravec** [comment]
Erin,

I spoke with Robert and he is satisfied with what you have done to place the contact info on each of the tabs.  If what you have done does not fit well with your teams vision and you want to continue to search for an alternate solution, then we will not resist. But what you have done meets our goal of what we wanted.

Thanks,
Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Erin Elzi ***@***.***>
Sent: Friday, March 31, 2023 7:22 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Valuation and Pricing webpage - contacts (Issue #2567)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7Cb18f2c23842b42bd8dde08db31eaf18e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638158657365957523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mdH%2B8ul4DvxvI2XzY0H0vZzc8vmTOPRd%2FZT6TTU2Iws%3D&reserved=0> We looked at this and decided that it deserves additional research. However, in the meantime we still want to make sure users can more easily find the contact info they need, so we added a simple contact statement to the pricing, unbundling, and valuation tabs - similar to what you suggested.

https://dev-onrr-frontend.app.cloud.gov/references/valuation<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation&data=05%7C01%7Ccory.forgrave%40onrr.gov%7Cb18f2c23842b42bd8dde08db31eaf18e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638158657365957523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ccZc%2BkjnH60pD8XApcLfaOti5BWFuBzkXNhjNILDCbM%3D&reserved=0>

**Comment by eelzi-ONRR** [comment]
@forgravec Great! I've pushed these changes live. 

https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

I may reach out to you as we keep thinking about bigger solutions for this part of the website. It receives more traffic that any other page, so if users are having trouble with it we want to look more into that. 

Thanks! Have a great weekend!
