### ISSUE TITLE
Fill out IDP

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2571]
Opening this issue for next sprint. It's required to fill out the Individual Development Plan (IDP) this year.

The Workforce Development Office (WDO) is excited to announce the ONRR Individual Development Plan window for fiscal year 2024 is OPEN!   The IDP window will close April 30th.

The IDP is a tool to assist you in your career development. WDO uses the IDP results to align training and development opportunities to meet the needs of ONRR employees and the mission of ONRR.

Start your IDP here: https://idp.onrr.local/  (You must log in to Ivanti / Pulse Secure)

**Comment by lpgoldstein** [comment]
Done

**Comment by eelzi-ONRR** [comment]
Mine is submitted
