### ISSUE TITLE
Add section about Collections in CMS user guide

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2575]
There's already detailed sections for specific collections but I'd like to add a general section for collections regarding how to add an entry, ensuring the new entry is on top and other entries are in order , and how to publish an entry.

**Comment by AlexandracmONRR** [comment]
The "Updating collections" section has been created here: https://github.com/DOI-ONRR/onrr.gov-site/wiki/CMS-User-Guide/_edit#updating-collections

When you get the chance @Maroyafaied , could you review it?

**Comment by Maroyafaied** [comment]
@AlexandracmONRR this is perfect, I have no changes. Thanks! https://github.com/DOI-ONRR/onrr.gov-site/wiki/CMS-user-guide#Updating-collections
