### ISSUE TITLE
100% Fed Agmt

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2580]
Please replace the 100% Federal Agreements with the Same Royalty Rate & Royalty Distributions spreadsheet on the Reference Lists card here - https://onrr.gov/reporting/revenue?tabs=references, with the attached spreadsheet.

Also please change the date from 1/01/2023 to 4/04/203.

Thank You
Jessica Bowlen
[fedagmts.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11160951/fedagmts.xlsx)

**Comment by cthomasONRR** [comment]
@bowlenj 

This update is on the dev site: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

Please review and give us approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great, approve to push live and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, April 5, 2023 11:27 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] 100% Fed Agmt (Issue #2580)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

This update is on the dev site: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great! This is now live: https://onrr.gov/reporting/revenue?tabs=references

Closing issue.
