### ISSUE TITLE
Please update March NYMEX on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2581]
Good morning,

Please update the NYMEX prices on onrr.gov according to the attachment.

Thanks!
@sudarr

[NYMEX032023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11172272/NYMEX032023.xlsx)

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by cthomasONRR** [comment]
@boices 

Great! These changes are now live: https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices

Closing this issue.
