### ISSUE TITLE
Indian Index Zone prices - April 

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#2582]
The Indian Index Zone prices are ready to be added to ONRR.gov.
I will email the spreadsheet with the prices to the onrrweb@onrr.gov address.

Thanks,
Cory Forgrave
@sudarr

**Comment by eelzi-ONRR** [comment]
@forgravec The April Index Zone prices have been added and are ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2023

Thanks!

**Comment by forgravec** [comment]
Prices look good.
Thanks
Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Erin Elzi ***@***.***>
Sent: Thursday, April 6, 2023 2:57 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Indian Index Zone prices - April (Issue #2582)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://github.com/forgravec> The April Index Zone prices have been added and are ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2023

Thanks!

**Comment by eelzi-ONRR** [comment]
@forgravec Great! These have been pushed live and I'm closing the issue: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone 

-Erin
