### ISSUE TITLE
Update Gas_Plant_Listing.xlsx within onrr.gov

### ISSUE THREAD

**Issue by Jared-ONRR** [DOI-ONRR/onrr.gov-site#2594]
Good Afternoon,

I have a file that needs updated on ONRR.GOV. The direct link for the file is as follows: https://www.onrr.gov/document/Gas_Plant_Listing.xlsx
The update file is attached (same file name) and needs the "as of" date on the website updated to DD/MM/YYYY (use same date as on the file header).

Thank you very much,

Jared Good
[Gas_Plant_Listing.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11216089/Gas_Plant_Listing.xlsx)

**Comment by lpgoldstein** [comment]
@Jared-ONRR Can you please tell me what the updated date is? I don't see it in the file.

**Comment by Jared-ONRR** [comment]
It's as of 04/12/2023.  Sorry about that.  I was writing an instruction set for the upload process and didn't correct my template.

Again, sorry for that.

Jared

Jared Good
Minerals Revenue Specialist - Onshore Production
Data Intake, Validation, and Indian Coordination Team 1
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3319
Hours: 7:30 - 4:00  MTN time

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, April 12, 2023 3:34 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Good, Jared R ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Gas_Plant_Listing.xlsx within onrr.gov (Issue #2594)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Jared-ONRR<https://github.com/Jared-ONRR> Can you please tell me what the updated date is? I don't see it in the file.

**Comment by lpgoldstein** [comment]
@Jared-ONRR Thanks! This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

**Comment by Jared-ONRR** [comment]
I think it looks good and we can push it out.


Jared Good
Minerals Revenue Specialist - Onshore Production
Data Intake, Validation, and Indian Coordination Team 1
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3319
Hours: 7:30 - 4:00  MTN time

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, April 12, 2023 3:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Good, Jared R ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Gas_Plant_Listing.xlsx within onrr.gov (Issue #2594)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Jared-ONRR<https://github.com/Jared-ONRR> Thanks! This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

**Comment by lpgoldstein** [comment]
@Jared-ONRR This is live! https://onrr.gov/references/reference-lists?tabs=production-reporting-references
