### ISSUE TITLE
Review ARIA roles & capture screenshots

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2595]
@greensomes implemented a fix in dev. I would like us to test all the pages that were identified in the OCIO report with this issue. @lpgoldstein can you make a list of all the pages in this issue and I will help you to test them. For example I just tested this page and got 100% score in dev and the score on the live site is 77%

https://dev-onrr-frontend.app.cloud.gov/references/valuation

 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/e2a6e3cd-e47d-43c5-a94d-d5bec0cb1fe7)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/2799cfb4-3ef2-4100-a480-7238966e6c7c)

**Comment by lpgoldstein** [comment]
@Maroyafaied Sure!

**Comment by lpgoldstein** [comment]
@Maroyafaied There are 150 locations on onrr.gov that have ARIA errors. I created a spreadsheet that has the location name but not the URL. It seems specific enough to be able to find and test but I will add URLs as I go. I can start from the bottom if you want to start from the top? 

https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/508/onrr.gov%20website%20accessibility/ARIA%20errors.xlsx?d=w6477f8cb82974382985a4b39de1357e4&csf=1&web=1&e=czEnba

**Comment by Maroyafaied** [comment]
@lpgoldstein I didn't realize the amount of pages, I think there's no need to check every single page. We can do a random check and if you can capture a few screen shots of dev vs live to use in presentations that would be great. I already checked several pages and I know Jeff has checked as well.

**Comment by lpgoldstein** [comment]
@greensomes @Maroyafaied I'm comfortable releasing these changes whenever you all are ready. I checked 15 pages and have 6 comparison screenshots. I'm getting between 98-100 on lighthouse scores on the updated pages in dev.
