### ISSUE TITLE
Reporter Letter

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2601]
Please add the attached Reporter Letter with the date 4/17/2023 to this page on onrr.gov - https://onrr.gov/references/reporter-letters

Topic - DC and PC Reporting Requirements for Flaring and Venting on the OGOR and 2014

[Dear Reporter Letter Flaring and Venting 04-17-2023.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11261574/Dear.Reporter.Letter.Flaring.and.Venting.04-17-2023.pdf)

**Comment by Maroyafaied** [comment]
@AlexandracmONRR please work on this request and let me know if you need any help.  This will be a new entry in the Reporter Letter collection in the CMS https://dev-onrr-cms.app.cloud.gov/admin/content/reporter_letters

**Comment by AlexandracmONRR** [comment]
@bowlenj - can you attach the word document of this reporter letter? We will post an accessible version to post along with the signed version.

**Comment by bowlenj** [comment]
I sent you both the pdf un-signed and the word via chat!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Alexandra C McNally ***@***.***>
Sent: Tuesday, April 18, 2023 7:28 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Reporter Letter (Issue #2601)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> - can you attach the word document of this reporter letter? We will post an accessible version to post along with the signed version.

**Comment by AlexandracmONRR** [comment]
@bowlenj - Please review the dev site link: https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

After I receive your approval, I will publish to the live site. Thank you!

**Comment by bowlenj** [comment]
Hi Alexandra,

Can we change the title to read Flaring and Venting and then leave the topic like you have it for both versions.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Alexandra C McNally ***@***.***>
Sent: Tuesday, April 18, 2023 8:37 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Reporter Letter (Issue #2601)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> - Please review the dev site link: https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

After I receive your approval, I will publish to the live site. Thank you!

**Comment by Maroyafaied** [comment]
@bowlenj I made these updates for you since Alex is on leave this afternoon. Please review the dev site again https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters 
Thanks!

**Comment by bowlenj** [comment]
This looks great, thank you!  Approved to publish and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, April 18, 2023 2:13 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Reporter Letter (Issue #2601)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> I made these updates for you since Alex is on leave this afternoon. Please review the dev site again https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters
Thanks!

**Comment by Maroyafaied** [comment]
@bowlenj Great, it's live!
