### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – April 2023

### ISSUE THREAD

**Issue by HammenONRR** [DOI-ONRR/onrr.gov-site#2603]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “April 2023 Lease Agreement XREF.txt" and "April 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 4/18/2023.
[April 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/11264979/April.2023.Lease.Agreement.XREF.txt)
[April 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11264989/April.2023.Lease.Agreement.XREF.xlsx)

**Comment by lpgoldstein** [comment]
@hammenONRR ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by HammenONRR** [comment]
Everything looks good! Please move the link to the live site.

Thanks!

**Comment by lpgoldstein** [comment]
@HammenONRR it's live https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
