### ISSUE TITLE
Audit of pages with tabs

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2604]
Note pages where there is no title/heading under a tab.

**Comment by cthomasONRR** [comment]
- [ ] https://www.onrr.gov/getting-started/new-reporter-checklist (all tabs here)

The 4 tabs within the new reporter checklist are the only tabs that did not have a heading.

I added the "h2" headings here: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Do you want to review?

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks good! I checked for spelling and made sure all 4 are h2

**Comment by cthomasONRR** [comment]
@Maroyafaied I ran the flow to publish the updates on the New Reporter Checklist page, but the changes didn't go live. I tried clearing browsing data and Ctrl+F5 but not seeing them live. Please let me know if I should try running CircleCi or just wait. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR you can go ahead an run circle ci if no one is waiting for approvals in dev. It probably didn't work since new content blocks were added, we have an issue open for Jeff to look into that.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks! It's now live! Closing this issue.
