### ISSUE TITLE
Update Howard's role as Director 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2610]
@AlexandracmONRR . Please update content for Howard, please remove anything related to "acting" or "Deputy Director"  in this tab https://onrr.gov/about/organization and send the dev site to Christina Mathers for her review before publishing. I will cc you in my response to Christina so you can respond to her.  Please let me know if you need any help. Thanks

**Comment by AlexandracmONRR** [comment]
Christina Mathers approved of edits, so this change was published.
