### ISSUE TITLE
Replace document for Flaring and venting reporting disposition codes

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2622]
Please delete the existing pdf titled "Flaring and venting reporting disposition codes" and replace it with the attached document in the Reporting Codes box on this page - https://onrr.gov/references/reference-lists?tabs=production-reporting-references

We would like the title for the new document to match the file name - Dear Reporter Letter Flaring and Venting 04-17-2023.

I've included both the signed and un-signed accessible copy here.  We don't need both posted to this location so if you agree we can just post the unsigned version since that is accessible and both are already posted under Reporter Letters.

[Dear Reporter Letter Flaring and Venting 04-17-2023.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11314717/Dear.Reporter.Letter.Flaring.and.Venting.04-17-2023.pdf)
[Dear Reporter Letter Flaring and Venting 04-17-2023.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11314725/Dear.Reporter.Letter.Flaring.and.Venting.04-17-2023.pdf)

Please let me know if you have any questions!  Thank you, Jessica

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

Also, I changed the card width  on the second row - @AlexandracmONRR or @eelzi-ONRR - are you okay with these changes? https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

**Comment by bowlenj** [comment]
Good Morning,

This looks great and I like the new card widths as well!  Approved to publish and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, April 24, 2023 7:35 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Replace document for Flaring and venting reporting disposition codes (Issue #2622)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

Also, I changed the card width on the second row - @AlexandracmONRR<https://github.com/AlexandracmONRR> or @eelzi-ONRR<https://github.com/eelzi-ONRR> - are you okay with these changes? https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=production-reporting-references

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - I think the way that you changed the card width is great!

**Comment by lpgoldstein** [comment]
@AlexandracmONRR @eelzi-ONRR Thank you!

@bowlenj it's live!https://onrr.gov/references/reference-lists?tabs=production-reporting-references
