### ISSUE TITLE
Develop Impact Expo powerpoint - Plain Language 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2624]

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review. Powerpoint located [here](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/ONRR%20Impact%20Expo%202023?csf=1&web=1&e=qazb7k). Let me know if you'd rather have a chat to discuss or if you're ok with adding comments to slides. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR I reviewed and left two minor comments. Looks great overall.
