### ISSUE TITLE
Homepage Cards User Research - Plan

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2625]
- Look at analytics for the previous site to understand which pages are used most often 

- Restructure cards 

- Can prototype this and include in the user research 

- Idea to prototype/explore - making getting started a card on the home page and moving those links to the lists to the main nav options make sense (can do for both main nav research and cards research) 

- Include a question or two about main nav – try to get info on why users don’t like to use it  

- Aim to recruit a use of mix of people who haven’t done our studies on this topic before, and people who participated in the studies that led to this design.

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR and @lpgoldstein - I've done another review of the [research plan](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/User%20Research/Studies/15_Homepage_QuickLink_Cards/15%20-%20Homepage%20Quick%20Link%20Cards%20-%20Context%20and%20Interview%20Script.docx?d=wcdb532ee86054baabc264c3ed5a61957&csf=1&web=1&e=Dj4oAA) and added just a bit of content/edits.
