### ISSUE TITLE
Fix spelling for "guidance"

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2626]
![image](https://user-images.githubusercontent.com/40175688/234630805-cc9aa6d4-64ab-4813-8deb-de63a512bd57.png)

**Comment by Maroyafaied** [comment]
This is misspelled in the unbundling and the valuation & regulations tabs as well. 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f50079df-8fb4-4394-9119-e977d1d528a3)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/357313de-0304-4275-8352-2182f3a4636f)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied this is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by Maroyafaied** [comment]
@eelzi-ONRR  Looks good

**Comment by eelzi-ONRR** [comment]
Changes are live: https://onrr.gov/references/valuation?tabs=valuation-regulations
