### ISSUE TITLE
Updates to ONRR.govs Federal Register Notices Page 

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2627]
Hello,

On the Federal Register Notices webpage: https://onrr.gov/references/frns

Under Major Portion Prices and Due Date, please update the existing Most Recent Annual Publication PDF with the link below
https://www.federalregister.gov/documents/2023/04/24/2023-08594/major-portion-prices-and-due-date-for-additional-royalty-payments-on-gas-produced-from-indian-lands 

Please let me know if you have any questions.
Thank you.

**Comment by gingerhensley** [comment]
Looks good, approved, thank you!

**Comment by AlexandracmONRR** [comment]
Great, this change has been published to the live site: https://onrr.gov/references/frns
