### ISSUE TITLE
Updates to ONRR.govs Information Collection Requests Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2628]
Hello, 

On the Information Collection Requests OMB Control Number 1012-0004 page https://www.onrr.gov/references/icrs/1012-0004

Please update the first bullet under Federal Register Publications to show as below.

60-Day Agency Information Collection - (88 FR 5916-- January 30, 2023)

Please let me know if you have any questions. 
Thanks

**Comment by Maroyafaied** [comment]
@gingerhensley please review https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0004

**Comment by Maroyafaied** [comment]
@gingerhensley Thanks, the change is now live.
