### ISSUE TITLE
    SALT LAKE CITY OUTREACH                                                      

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2635]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

SALT LAKE CITY OUTREACH 
May 1, 2023 
5:00 pm - 7:00 pm MST

Location:  Holiday Inn and Suites Salt Lake City Airport West, 5001 West Wiley Post Way, Salt Lake City, UT 84116

Description: Representatives from the Office of Natural Resources Revenue (ONRR), will host an in-person Question and Answer session for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions. 
Who Should Attend: IIM account holders, Indian mineral owners, and Indian trust property owners in the Salt Lake City area in Utah.  
Other Information: Please contact the ONRR Denver Outreach Office at (800) 982-3226 for more information.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 
Contact: ONRR Denver Outreach Office, Toll Free (800) 982-3226
Email: [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

FORT HALL OUTREACH
May 2, 2023 
2:00 pm - 4:00 pm MST

Location:  Bureau of Indian Affairs, Fort Hall Agency, 49 Bannock Avenue, Fort Hall, Idaho 83203

Description: Representatives from the Office of Natural Resources Revenue (ONRR), will host an in-person Question and Answer session for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions. 
Who Should Attend: IIM account holders, Indian mineral owners, and Indian trust property owners in the Fort Hall area in Idaho.  
Other Information: Please contact the ONRR Denver Outreach Office at (800) 982-3226 for more information.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30 am-4:00 pm. MST
Contact: ONRR Denver Outreach Office, Toll Free (800) 982-3226
Email: [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

UPPER FRUITLAND CHAPTER HOUSE OUTREACH
May 4, 2023
10:00 am – 1:00 pm MST

Location: Upper Fruitland Chapter House, Upper Fruitland, NM

Description: The Federal Indian Minerals Office (FIMO) will conduct ‘One-to-One’ type sessions for mineral/landowners with questions regarding their oil & gas royalties, any letters they may have received from oil & gas companies, and letters from BIA regarding their trust land.  Representatives from Eastern Navajo Agency, BIA, Probates Office will be available to discuss topics regarding probate status and the American Indian Probate Reform Act.  Information booklets will be available.
Who Should Attend: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area, or any mineral owners located in the Four Corners Region.
Other Information: The FIMO office hours are Monday through Friday, 8:00 am to 12:00 pm MST, and closed during the lunch hour; re-open 1:00 pm to 4:00 pm MST.  
Email: [leona.begay@onrr.gov](mailto:leona.begay@onrr.gov), [jennifer.benally@onrr.gov](mailto:jennifer.benally@onrr.gov)

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
 to be added to the "Indian Outreach and Events" tab under the Indian Resources Page

**Comment by AlexandracmONRR** [comment]
@Toddsand21 - thank you for submitting this request. 

Please review the following link to make sure that these updates are correct: https://dev-onrr-frontend.app.cloud.gov/events

If you approve of the changes, please approve and then I will publish the changes to the live site.

**Comment by Toddsand21** [comment]
Can we put the commas in the Location address for the Salt Lake City one?  As in the one below:
Holiday INN and Suites, Salt Lake City Airport West, 5001 West Wiley Post Way, Salt Lake City, UT 84116

Those are the only edits I can see.  The rest looks fine.

**Comment by AlexandracmONRR** [comment]
No problem - I made that edit and published the changes to the live site here: https://onrr.gov/events

Thank you!

**Comment by Toddsand21** [comment]
They look fine and ready to post.
