### ISSUE TITLE
Review performance.gov re-write/summary of website redesign blog

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2639]
The perfomance.gov team will send a draft next week for our review as well as ask us for pictures & quotes. The plan to publish this by end of June.

**Comment by Maroyafaied** [comment]
I sent performance.gov draft by email, I also included Howard and Chris. Let me know if you have any edits

**Comment by Maroyafaied** [comment]
Let's gather all the edits in one doc. Here's Chris's edit "One other edit is the say “Department of Interior” instead of “Department of the Interior” and Howard sent an edit by email.

**Comment by cthomasONRR** [comment]
@Maroyafaied 

I read through the document with Howard's edits. Other than removing the "44444444" Howard accidentally added on page 3, I think it looks good.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/5c471255-1ba8-40cc-be46-d03403fa33f5)

I have 2 minor questions that probably don't require edits:

For the title, should we replace Interior with Office of Natural Resources Revenue? This would be in-line with Howard's comment on page 3. But, it would be very wordy.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/bdf0cdfe-584f-46f7-ba7f-27c43b1421c6)


In the second paragraph- should it be "Department of Interior's Office of Natural Resources Revenue"? (The change would be making Interior possessive.) "Department of Interior Office of Natural Resources Revenue" reads kind of weird to me, but I don't think it's an actual grammar issue.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/c5b28769-3127-4cc5-a1a3-aaf9e59083af)

**Comment by cthomasONRR** [comment]
@Maroyafaied I like that change to the second paragraph.

For the title: "How a Small Team Redesigned a Federal Website With Users at the Department of **Interior's** Office of Natural Resources Revenue" OR remove DOI completely and just have ONRR in the title.

**Comment by Maroyafaied** [comment]
@cthomasONRR ok I'll make that change and suggest removing DOI completely

**Comment by Maroyafaied** [comment]
I sent the edits and asked for a 2nd version of the draft per the Director's request
