### ISSUE TITLE
Update May Indian Index Zone prices

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2641]
Good afternoon,

Please update the May Indian Index Zone prices on onrr.gov according to the attachment. Thank you!

[Indian_Index_Zone_2023_05.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11391509/Indian_Index_Zone_2023_05.xlsx)

@sudarr

**Comment by Maroyafaied** [comment]
@boices please review https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by Maroyafaied** [comment]
@boices it's live. Thanks
