### ISSUE TITLE
April 2023 NYMEX Prices

### ISSUE THREAD

**Issue by WW-Git-Hub** [DOI-ONRR/onrr.gov-site#2643]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

 April 2023	
 NYMEX CMA Price	$79.44 
 NYMEX Roll	($0.17)
 NYMEX + Roll	$79.27 

[NYMEX042023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11400459/NYMEX042023.xlsx)

@Sudarr

**Comment by cthomasONRR** [comment]
@WW-Git-Hub 

The April NYMEX prices are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by WW-Git-Hub** [comment]
Approved.

Thank you!

@Sudarr

**Comment by cthomasONRR** [comment]
@WW-Git-Hub 

Great, these changes are now live: https://www.onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices

Closing this issue.

Thanks,
Christine
