### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – May 2023

### ISSUE THREAD

**Issue by HammenONRR** [DOI-ONRR/onrr.gov-site#2645]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “May 2023 Lease Agreement XREF.txt" and "May 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 5/5/2023.
[May 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11406559/May.2023.Lease.Agreement.XREF.xlsx)
[May 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/11406566/May.2023.Lease.Agreement.XREF.txt)

**Comment by cthomasONRR** [comment]
@HammenONRR 

Good morning, these updates are now in the dev site: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@HammenONRR 

Great! These changes are now live: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Closing this issue now.

Thanks,
Christine
