### ISSUE TITLE
Final sitemap cleanup 3.6 to 6.0

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2646]

**Comment by AlexandracmONRR** [comment]
Go through the comments on site map draft (approximately 45 of 90)

**Comment by AlexandracmONRR** [comment]
**File and Video Collections/Lists:**

- Cards with file downloads and video collections should use the orange stacked boxes considered "collections or lists"
- We will label list box with: title, number of links/downloads, type of content (file download vs. video list)

**Comment by AlexandracmONRR** [comment]
sections 3.6 to 6.0 are drafted with the new updates.
