### ISSUE TITLE
Update 2021 major portion prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2649]
Good afternoon,

Please update the major portion prices for Fort Berthold, Fort Peck, Navajo Allotted, and Turtle Mountain according to the attached spreadsheet.
[Maj_Portion_FinalPrices_2021.xls](https://github.com/DOI-ONRR/onrr.gov-site/files/11424740/Maj_Portion_FinalPrices_2021.xls)

Thanks,
Sean

@sudarr

**Comment by boices** [comment]
Also, sorry I neglected to add it to that sheet but, if there's a section on the website for a due date for prices, it will be June 30, 2023.

**Comment by Maroyafaied** [comment]
@boices Hi, thanks for submitting this update. With the new Content Management System, we will need a file for each month formatted like this attached file. This will allow us to upload the file directly without having to manually enter prices. Please let me know if you have any questions. Thanks
[https://app.zenhub.com/files/210892300/43df2cda-c1e9-48c8-a9e4-7cd1960575a8/download](https://app.zenhub.com/files/210892300/43df2cda-c1e9-48c8-a9e4-7cd1960575a8/download)

**Comment by boices** [comment]
Good morning, I'm not able to access that file without a zenhub login...is that something I need to sign up for?

**Comment by boices** [comment]
[Indian_Gas_Major_Portion_Jan_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431915/Indian_Gas_Major_Portion_Jan_2021.xlsx)
[Indian_Gas_Major_Portion_Feb_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431919/Indian_Gas_Major_Portion_Feb_2021.xlsx)
[Indian_Gas_Major_Portion_Mar_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431920/Indian_Gas_Major_Portion_Mar_2021.xlsx)
[Indian_Gas_Major_Portion_Apr_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431921/Indian_Gas_Major_Portion_Apr_2021.xlsx)
[Indian_Gas_Major_Portion_May_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431922/Indian_Gas_Major_Portion_May_2021.xlsx)
[Indian_Gas_Major_Portion_Jun_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431924/Indian_Gas_Major_Portion_Jun_2021.xlsx)
[Indian_Gas_Major_Portion_Jul_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431927/Indian_Gas_Major_Portion_Jul_2021.xlsx)
[Indian_Gas_Major_Portion_Aug_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431929/Indian_Gas_Major_Portion_Aug_2021.xlsx)
[Indian_Gas_Major_Portion_Sep_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431933/Indian_Gas_Major_Portion_Sep_2021.xlsx)
[Indian_Gas_Major_Portion_Oct_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431935/Indian_Gas_Major_Portion_Oct_2021.xlsx)
[Indian_Gas_Major_Portion_Nov_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431937/Indian_Gas_Major_Portion_Nov_2021.xlsx)
[Indian_Gas_Major_Portion_Dec_2021.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11431938/Indian_Gas_Major_Portion_Dec_2021.xlsx)

**Comment by Maroyafaied** [comment]
@boices Thank you so much for providing these files. The prices are ready for you to review in the dev site https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-major-portion

**Comment by boices** [comment]
Not a problem. Prices look perfect--thanks again!

**Comment by Maroyafaied** [comment]
@boices Awesome, they are now live. Thanks https://onrr.gov/references/valuation?tabs=pricing,indian-gas-major-portion
