### ISSUE TITLE
Indian Gas Index Examples for Valuation Examples page

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2651]
If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

Hello!

Attached are the PDFs for the 6 Indian Gas index examples that are "coming soon" on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-dedicated-contract

There are 3 labeled "ALDC" for "arm's-length dedicated" and 3 labeled ALNDC for "arm's-length non-dedicated".  I realize it will need to be put on a priority list to make these interactive (and finish making the major portion examples interactive).  Would you like to include that as part of this or have me make it another request?  

As with the other examples, we will label the boxes and make the link the title from the document.  

In the arm's-length dedicated section, the boxes should be:
Processed Gas (column header)
Alternative Dual Accounting
Actual Dual Accounting

Unprocessed Gas (column header)
Alternative Dual Accounting
Actual Dual Accounting (contact royaltyvaluation@onrr.gov)

In the arm's-length non-dedicated section, the boxes should be:
Processed Gas (column header)
Alternative Dual Accounting
Actual Dual Accounting

Unprocessed Gas (column header)
Alternative Dual Accounting
Actual Dual Accounting (contact royaltyvaluation@onrr.gov)

Please let me know if you need other information!  Thanks!

Jodie
[Processed Gas ALDC Index Actual DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443073/Processed.Gas.ALDC.Index.Actual.DA.pdf)
[Processed Gas ALDC Index Alt DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443074/Processed.Gas.ALDC.Index.Alt.DA.pdf)
[Processed Gas ALNDC Index Actual DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443075/Processed.Gas.ALNDC.Index.Actual.DA.pdf)
[Processed Gas ALNDC Index Alt DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443076/Processed.Gas.ALNDC.Index.Alt.DA.pdf)
[Unprocessed Gas ALDC Index Alt DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443078/Unprocessed.Gas.ALDC.Index.Alt.DA.pdf)
[Unprocessed Gas ALNDC Index Alt DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11443079/Unprocessed.Gas.ALNDC.Index.Alt.DA.pdf)

**Comment by Maroyafaied** [comment]
@jpetersononrr I assigned Erin to this issue, we can work on getting the pdfs on the site this week.  We will need to make another issue for making the examples interactive as that will take up time and we didn't plan for it this sprint, we are also traveling to a conference next week.  
@eelzi-ONRR I checked all 6 docs for accessibility to help you out a tiny bit and they all passed.

**Comment by jpetersononrr** [comment]
That sounds great!  Thank you!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr 

The page is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-examples,indian
