### ISSUE TITLE
Update to Minerals Production Reporter Handbook - Appendix B and Appendix I

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2653]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Hello,
Updated versions of Appendix B and Appendix I for the Minerals Production Reporter Handbook are attached. I did not do the previous updates, so I do not know what the prior file names were and cannot provide them.  These versions need to replace the current versions located in the Table of Contents Tab at: https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=table-of-contents
The versions located on the Supplemental Information Tab also need updating:  https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information
[Appendix I working draftV4 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453561/Appendix.I.working.draftV4.508.pass.pdf)
[MPRH-Appendix-B updated lease conversion number 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453563/MPRH-Appendix-B.updated.lease.conversion.number.508.pass.pdf)

**Comment by NSweeneyonrr** [comment]
@lpgoldstein  - here is the full version.  Please let me know if you have any questions.  Thanks!
[MPRH-AllDocs-Combined -508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11454982/MPRH-AllDocs-Combined.-508.pass.pdf)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr This is live so I'll close out the issue.
