### ISSUE TITLE
Minerals Revenue Reporter Handbook update

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2654]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Hello,

The Minerals Revenue Reporter Handbook has been updated.  Please update the full handbook located at:  https://www.onrr.gov/references/handbooks
Additionally, under the title "Minerals Revenue Reporter Handbook" please update the version from 4.0 to 4.2
[Minerals.Revenue.Handbook_4.2 version 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453730/Minerals.Revenue.Handbook_4.2.version.508.pass.pdf)

**Comment by Maroyafaied** [comment]
@NSweeneyonrr please review https://dev-onrr-frontend.app.cloud.gov/references/handbooks

**Comment by NSweeneyonrr** [comment]
I've reviewed this update in Dev and it looks good and is ready for the live site. 

Thank you!
Nicole

**Comment by Maroyafaied** [comment]
This is live
