### ISSUE TITLE
Minerals Revenue Reporter Handbook - Chapter 2 updates

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2655]
If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:
Chapter 2 of the Minerals Revenue Reporter Handbook has been updated.  A new section has been added to the chapter.  Section 12.12 is titled "Step-Scale and Sliding-Scale Royalty Rates"  this section needs to be added to the Table of Contents directing users to page 2-20 to access the chapter: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=table-of-contents

The current Chapter 2 needs to be updated with the attached version.  It is located at: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=chapters

[MRRH-Chapter-2 version 4.2 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453785/MRRH-Chapter-2.version.4.2.508.pass.pdf)

**Comment by Maroyafaied** [comment]
@NSweeneyonrr please review https://dev-onrr-frontend.app.cloud.gov/references/handbooks

**Comment by NSweeneyonrr** [comment]
Hello,

The Chapter update looks good and is ready for the live site.  However, the Table of Contents for Chapter 2 still needs to be updated to include the new section 12.12 "Step-Scale and Sliding-Scale Royalty Rates" (hopefully the attached screen shot makes sense)
![Ch 2  Section 12 12](https://github.com/DOI-ONRR/onrr.gov-site/assets/112106225/66e46853-6b87-4034-8392-4a3a1c3958a6)
 that was added.  The new section begins on page 2-20.

**Comment by Maroyafaied** [comment]
@NSweeneyonrr sorry about that, please review again https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=table-of-contents

**Comment by NSweeneyonrr** [comment]
Thanks!  That looks good.  It's ready for the live site.

**Comment by Maroyafaied** [comment]
This is live
