### ISSUE TITLE
Minerals Revenue Reporter Handbook - Chapter 4 Update

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2656]
If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

Chapter 4 of the Minerals Revenue Reporter Handbook has been updated.  Please update the version currently located at: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=chapters

Additionally, please ensure that the Table of Contents for Chapter 4 "quicklinks" points to this updated version. 

[RRM-Chapter.4 version 4.2 - 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453876/RRM-Chapter.4.version.4.2.-.508.pass.pdf)

**Comment by Maroyafaied** [comment]
@NSweeneyonrr please review https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=chapters

**Comment by NSweeneyonrr** [comment]
Thanks!  This looks good in DEV and is ready for the live site.

**Comment by Maroyafaied** [comment]
This is live
