### ISSUE TITLE
Minerals Revenue Reporter Handbook updates - Appendix B and Appendix C

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2657]
If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:
Hello,

Appendix B and Appendix C of the Minerals Revenue Reporter Handbook have been update
[Appendix B (Final)_MLRS update_Mineral Revenue version 4.2 update  508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453967/Appendix.B.Final._MLRS.update_Mineral.Revenue.version.4.2.update.508.pass.pdf)
[Appendix C - 2023 update 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11453969/Appendix.C.-.2023.update.508.pass.pdf)
d.  Please update the versions that are located in the Table of Contents that users can use quicklinks to go directly to the Appendices: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook
Also, please update the versions currently displayed on the "Supplemental Information" tab: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=supplemental-information

**Comment by Maroyafaied** [comment]
@NSweeneyonrr please review https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=supplemental-information

**Comment by NSweeneyonrr** [comment]
Hello,

These update look good in DEV and are ready to be placed on the live site. 

Thanks!
