### ISSUE TITLE
Contact Update for RRCM shared spreadsheet

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2658]
Please update the contacts for Lease & Agreements, Oil & Gas Production, and Oil & Gas Royalty using the shared spreadsheet.  There are several changes to existing cards contacts, all changes are highlighted in yellow.  Please note that new cards will need to be added for the below:

**Oil & Gas Royalty:**
Change card U & V to show only U
Add card for V
Remove card for Conoco Phillips
Change card G & H to show only G
Add card for H

**Oil & Gas Production:**
Add card for Hilcorp Alaska LLC
Add card for Hilcorp Energy Company

Please let me know if you have any questions.

Thank you
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj Hi Jessica,

Our entire team is away this week on a conference. We'll get to this issue when we have time next week.

Thanks,
Christine

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts also leases and onshore production are ready as well.

**Comment by bowlenj** [comment]
Good Morning,

This looks great, thank you!  Approved for live and to close.

Hope you all had a great time at the conference!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, May 18, 2023 8:21 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Contact Update for RRCM shared spreadsheet (Issue #2658)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> This is ready for your review https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts also leases and onshore production are ready as well.
