### ISSUE TITLE
Update to Minerals Revenue Reporter Handbook

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2661]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

Hello,

The Minerals Revenue Reporter Handbook needs to have the attached, updated version made available on the website.  The current version that was approved last week had some typos in it.  Please replace the version located at: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook

Thank you, 
Nicole
[Minerals.Revenue.Handbook_4.2 version 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11518663/Minerals.Revenue.Handbook_4.2.version.508.pass.pdf)

**Comment by NSweeneyonrr** [comment]
Hi Christine,

Thank you!  So sorry, but I found ONE more typo.  Can you please use the version attached here instead?  My apologies.

Thanks,
Nicole
[Minerals.Revenue.Handbook_4.2 version 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11518897/Minerals.Revenue.Handbook_4.2.version.508.pass.pdf)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

No worries- the latest version is now on dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
Please review again.

Thanks,
Christine

**Comment by NSweeneyonrr** [comment]
Perfect, looks good!  It's ready for the live site.  

Thanks, 
Nicole

**Comment by cthomasONRR** [comment]
@NSweeneyonrr Great! These changes are now live: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook

Thanks,
Christine
