### ISSUE TITLE
Updated versions of Chapter 2 and Chapter 4 of Minerals Revenue Reporter Handbook

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2664]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Good Morning,

There were a few typos in Chapter 2 and Chapter 4 of the Minerals Revenue Reporter Handbook. 

Each needs to be updated respectively at this link: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=chapters

Please let me know if you have any questions. 

Thanks,
Nicole
[MRRH-Chapter-2 version 4.2 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11532162/MRRH-Chapter-2.version.4.2.508.pass.pdf)
[RRM-Chapter.4 version 4.2 - 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11532163/RRM-Chapter.4.version.4.2.-.508.pass.pdf)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook

dev is being a little fussy - so please try reloading if the page won't load.

**Comment by lpgoldstein** [comment]
@NSweeneyonrr This is just the full handbook - which I believe I need to update the TOC anyway and those directions do make sense. Can you please send me just Chapter 4 as well. I'll get the handbook and TOC updated in the meantime.

**Comment by NSweeneyonrr** [comment]
@lpgoldstein Sorry about that! Here is just Chapter 4. 
[RRM-Chapter.4 version 4.2 - 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11537225/RRM-Chapter.4.version.4.2.-.508.pass.pdf)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr Both the new Chapter 2, 4 and full handbook are updated. There's no easy way to update the TOC so I'll have that ready for you to review tomorrow morning.

**Comment by lpgoldstein** [comment]
@NSweeneyonrr I think this should be 4.1 in the full handbook and chapter 4 - I'm sorry I know how hard it is to take over a project! 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/9a495a4e-22ef-4d3b-9a2a-cbe3d3fe67d6)

**Comment by NSweeneyonrr** [comment]
Thanks @lpgoldstein - let me take a look at that and see if it needs to be 4.1 :-)

**Comment by NSweeneyonrr** [comment]
Thanks @lpgoldstein I concur that it does need to be 4.1  - Attached is the updated Chapter 4 and Full Handbook with that correction. 

Thank you!
[Minerals.Revenue.Handbook_4.2 version 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11545068/Minerals.Revenue.Handbook_4.2.version.508.pass.pdf)
[RRM-Chapter.4 version 4.2 - 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11545071/RRM-Chapter.4.version.4.2.-.508.pass.pdf)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr documents are updated. Still trying to figure out how to update TOC easily - I may have to manually update all page numbers. Not a big deal but it will just take longer.

**Comment by NSweeneyonrr** [comment]
@lpgoldstein TOC looks good in dev and is ready for the live site.  Thank you for all your help on this!!!!

**Comment by lpgoldstein** [comment]
@NSweeneyonrr It's live! Happy to help.
