### ISSUE TITLE
Post Pipeline Fuel Reporter Letter

### ISSUE THREAD

**Issue by chriscareyONRR** [DOI-ONRR/onrr.gov-site#2665]
We updated the pipeline fuel reporter letter and would like to post it on onrr.gov. Here is the relevant information:

Location: https://onrr.gov/references/reporter-letters
Title: Updated: Royalty on Gas Used or Lost Along a Pipeline Prior to the Point of Sale
Topics: Federal Gas, Indian Gas, Oil & Gas Revenue
Date: 5/17/2023

The file is attached and is 508 compliant.  Please let me know if you need anything else from me!  Thank you!

[Revised Pipeline Fuel Loss DRL FINAL signed 2023-05-17.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11537403/Revised.Pipeline.Fuel.Loss.DRL.FINAL.signed.2023-05-17.pdf)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR please work on this request. I added @jessmanko if you both have time then you can show her how we work onrr.gov requests. Thanks!

**Comment by eelzi-ONRR** [comment]
@chriscareyONRR The letter has been added and is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

**Comment by eelzi-ONRR** [comment]
@chriscareyONRR Great! This has been pushed live and I'm closing out the issue: https://onrr.gov/references/reporter-letters
