### ISSUE TITLE
CHOOSING ASSISTANCE TAB   (Under Indian Resources tab)

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2666]
Please delete only the following portion in first paragraph after **Indian Outreach** where it reads...
"and sensitive to Covid restrictions,"  

and leave the rest of the paragraph.  I've attached a copy of the tab and the paragraph.
**Follow these directions:**

* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS **Follow these directions:**

[Choosing Assistance Tab.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11548121/Choosing.Assistance.Tab.pdf)

Let me know if you have questions.

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
HERE:**

**Comment by Maroyafaied** [comment]
@Toddsand21 please review , I will push the changes live once you approve. Thanks

https://dev-onrr-frontend.app.cloud.gov/indian/assistance

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/01f4e975-9572-450d-8d36-49f0d7022794)

**Comment by Toddsand21** [comment]
It looks fine Maroya.  Good to post!  Thanks.

**Comment by Maroyafaied** [comment]
Thanks, this is live.

**Comment by Toddsand21** [comment]
Thanks for the quick response.  Looks great!
