### ISSUE TITLE
Document update "Data Elements by Transaction Code"

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2668]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Hello,

The attached document has been updated and needs to replace the current document named "Data Elements by Transaction Code" that is located under the sub-heading "Reporting Codes" located at this link:  https://www.onrr.gov/reporting/revenue?tabs=references

Please let me know if you have any questions.

Thanks, 
Nicole 
[Data Elements by Transaction Code 05242023 508 pass.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11557823/Data.Elements.by.Transaction.Code.05242023.508.pass.pdf)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr ready for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by NSweeneyonrr** [comment]
@lpgoldstein thank you, looks good.  I approve for the live site.  :-)

**Comment by lpgoldstein** [comment]
@NSweeneyonrr It's live!
