### ISSUE TITLE
Full panel/interactive example for Minimum NGL value

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2670]
Please create a full panel/interactive example for the Minimum NGL value example on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=major-portion-area and based on this example:  https://onrr.gov/document/Minimum.NGL.Value.pdf.  The sample statement is at the end of the example.  Thank you!

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Images are already in the CMS, located here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/d54faa20-3ee2-4e32-8a92-6103772961bb

**Comment by lpgoldstein** [comment]
@eelzi-ONRR please review: https://dev-onrr-frontend.app.cloud.gov/references/valuation/minngl?tabs=overview&panel=assumptions-indian-example-minimum-value-provision-for-ngls-arms-length-sales

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Great job so far! You really had a complicated one and my comments are pretty minimal, especially this being your first one!

**Overview:**

- one of the lists is formatted as such, but this one is not:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTA0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0b55042286fd462af17043ee39d891385e526277/image.png)

- Indian needs to be bold

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmM0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c23ec87ffb30c0e200acf1a56aa19232538ab49/image.png)


- This content you have in the assumptions panel but on the other examples it's in the overview: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2M0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bcbf144836d98adf4c91c056f478953730ec6898/image.png)

**Detailed Example:**

- Substeps (1a, 1b, etc) should be H5

- I think the info boxes are supposed to be full width like the caution boxes are. Like in this one: https://onrr.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-07 

- PC07 Note - this is a purely aesthetic choice, but if you want the card to not have all that white space you can uncheck Equal Col Height Enabled

- PC07, Transportation Allowance - on the other examples we have made Here's what the Royalty Reporting Looks like So Far an H4

- Royalty Value Less Allowances - Previous Tab link doesn't work

**Scenarios**

- Downstream and minus need to be italicized in these highlighted instances [Private Zenhub Image] (https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGs0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--377f009d256b483540081e86193ffe3c4d4d1628/image.png)

-  I know this is RV's language but we can't use the word above here or in the other scenarios. Maybe say something like "previously calculated"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHc0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c4a65e4b879ad0d5eaaf49cc7e38577a1c783fce/image.png)

- Sample statement - if possible we should make the bubbles blue and write a note indicating what the important ones are for this example. Alex and I had to change our image too. If you want to do it in photoshop the color replacement tool makes it pretty quick and easy. Or Alex or I an show you next week

**Comment by lpgoldstein** [comment]
@jpetersononrr This is ready for your review. Note that the sample statement doesn't have any explanation because there isn't any in the file. When you are ready we can work together to create this. https://dev-onrr-frontend.app.cloud.gov/references/valuation/minngl?tabs=overview&panel=assumptions-indian-example-minimum-value-provision-for-ngls-arms-length-sales

**Comment by jpetersononrr** [comment]
Hello!

I have 2 quick typos: 

Overview:  Paragraph that begins "For Form ONRR-2014 reporting purposes" ends with a pr and the next paragraph starts with "ices".  Should be one paragraph.

Second bullet step 1 Transportation allowance:  space after 6,774

When I click on the "previous" and "next" tab links, the assumptions reopen even if I've closed them.  Possible to keep them closed?  Okay if not!  Just curious!

Thanks!

**Comment by lpgoldstein** [comment]
@jpetersononrr Thank you! Will get the typos fixed quickly. We have the assumption set to stay open. Would you prefer that I have them set to closed?

**Comment by lpgoldstein** [comment]
@jpetersononrr typos fixed.

**Comment by lpgoldstein** [comment]
@jpetersononrr Thank you!

**Comment by lpgoldstein** [comment]
@jpetersononrr this is live! https://www.onrr.gov/references/valuation/minngl 
Closing out the issue but happy to make updates anytime.
