### ISSUE TITLE
Full panel/interactive example Unprocessed Gas Alternative DA Non-dedicated

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2676]
Please complete a full panel/interactive example for Unprocessed Non-dedicated Alternative Dual Accounting on this page: https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-non-dedicated-contract using this example: https://onrr.gov/document/Unprocessed.Gas.ALNDC.Index.Alt.DA.pdf. The sample statement is the same as for the unprocessed major portion examples.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Acronym: "UND-Alt" (Unprocessed Gas, Non-Dedicated Contract, Alternative Dual Accounting)

Image file folder: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/64b5024d-ee64-488a-ae4b-43aee5e612ae

**Comment by lpgoldstein** [comment]
Ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation/und-alt?tabs=overview
Does anyone have time to review? @AlexandracmONRR @eelzi-ONRR @cthomasONRR Happy to return the favor.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein This one was a joy to review after the complicated one I've been working on! 

Overview
- Make "ONRR Reporter and Payor Handbooks" a link to the handbooks page
- Downloadable Example should be H3

Detailed Example
- I think you can remove "from ONRR.gov" from assumption 6
- On Dual Accounting Requirement Alternative - I don't think BLM is mentioned prior to this so it should be spelled out
- In the Step 1 image, there's an "e" that's highlighted in blue
- Step 3 - add the word Zone to the link and remove the word "web"
- In some examples we have made Here is what the final royalty reporting looks like:" a heading and in others it's not. I'm not sure which is correct. To me a heading makes sense since it's the result of Step 6 but not part of it

Sample Statement
- In the older examples we link to a PDF of the statement below the image. I've noticed in the more recent ones that's not the case. Not sure which is correct.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I Thank you! don't have the actual PDF of the sample statement and I don't think the quality is good enough to create one from the image so I'm leaving it out.

**Comment by lpgoldstein** [comment]
@jpetersononrr ready for your review https://dev-onrr-frontend.app.cloud.gov/references/valuation/und-alt?tabs=overview

**Comment by lpgoldstein** [comment]
@AlexandracmONRR thanks! All fixed.

**Comment by lpgoldstein** [comment]
@jpetersononrr ready for your review as well: https://dev-onrr-frontend.app.cloud.gov/references/valuation/und-alt?tabs=overview

**Comment by jpetersononrr** [comment]
Thank you!

Under the detailed example tab, just a couple things:
Let's move this language from "dual accounting requirement" to "Determining Dual accounting" :
Assume, for this example, that the lessee chose alternative dual accounting.
If you elected actual dual accounting for your unprocessed gas, you must use §1206.181 to establish processing costs when neither you nor someone acting on your behalf processes the gas. Under §1206.181, you must use the first applicable of the four given methods to establish processing costs for dual accounting purposes. Please also be mindful of the additional regulatory requirements in this section (§§1206.176, 179, 180). Collectively, all of these obligations must be satisfied in order to use actual dual accounting. For assistance in ensuring you meet all these obligations, please contact [royaltyvaluation@onrr.gov](mailto:royaltyvaluation@onrr.gov).

Then the language that's on the "determining" tab can be the intro to the calculations tab.  Does that make sense?

Otherwise it looks great!  Thank you!

**Comment by jpetersononrr** [comment]
On second thought, let's just eliminate the second tab and put everything regarding dual accounting in the first then the line about RMP on the "calculations" if that works for you!  Thanks!

**Comment by lpgoldstein** [comment]
@jpetersononrr Hopefully I understood correctly - https://dev-onrr-frontend.app.cloud.gov/references/valuation/und-alt?tabs=detailed-example,determining-dual-accounting

**Comment by jpetersononrr** [comment]
That will work :).  Thank you!

**Comment by lpgoldstein** [comment]
@jpetersononrr This is live! https://onrr.gov/references/valuation/und-alt
