### ISSUE TITLE
Full panel/interactive example for Dedicated Actual DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2678]
Please complete a full panel/interactive example for Dedicated Actual DA on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-dedicated-contract using this example:  https://onrr.gov/document/Processed.Gas.ALDC.Index.Actual.DA.pdf.  The statement is the same as the major portion examples.

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Acronym: "PD-Act" (Processed Gas, Dedicated Contract, Actual Dual Accounting)

Image file folder here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/cbe82b84-e7d1-4a90-bf0b-2f2ec8ffd1b2

**Comment by jpetersononrr** [comment]
Here is the statement for this example.  Thanks!
[Indian Example processed gas plant statement (3).pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12882661/Indian.Example.processed.gas.plant.statement.3.pdf)

**Comment by AlexandracmONRR** [comment]
Sample Statement in CMS with alternative text:
https://dev-onrr-cms.app.cloud.gov/admin/files/b0843d92-ca4f-4ece-a03f-10eaec9103dd

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Thank you for offering to review! https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks for your work on this one- it's a beast. I found a few minor things below. I used ANDI to check headings and images, and also tested all links.

The highlighted words should be bolded:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/6d23033b-1fe3-43b2-aad7-6505be7f7e59)

This text is a weird light grey color. I know you put it in the list of issues with the editor. I think to get rid of it you have to delete it out and either manually type it or paste as plain text. I'm seeing it in a few other places as well.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/ae9f89ba-9232-483b-8b41-a63605ef1be8)

Make these letters blue and bold:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/07f71940-36d2-4741-9166-906d2979687d)

Part A, PC07, table has some extra letters:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/53e860f3-ee53-4d87-a264-29901b57d326)

**Comment by lpgoldstein** [comment]
Posting these so I don't lose them. Will continue to review. There's a lot here. 
In first detailed example tab whichever is the greater should be bolded as well [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de38a7f84d1fc6a78faebcb10e87587742532327/image.png)

also suggest that this be a link [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51b2443d7cf727fc4f16d148ed9b7a9a6ef14fe0/image.png)

**Comment by jpetersononrr** [comment]
Thank you all for tackling these!  This one is a LOT.  If anyone is curious, it's why we strongly recommend people don't elect actual dual accounting.  So...much...math.

**Comment by jpetersononrr** [comment]
Just a couple tiny things (I don't need to look it over again--I trust you!). 

1.  On tab "Part A PC 03", step 2 bullet 2 has grey text. 
2. Same for Step 5 bullet 1
3. In Part A PC 07, Step 2a, bullet 5, also grey text
4. This one may be something I have to fix and send to you.  Part B, step 4.  Graphic says step 3.  Step 5 after it refers to step 3 numbers, but it's really step 4.
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/64428541/4d8ce00d-c242-4ca9-8739-114af0534bff)

I pulled the PDF and yes, I did have to fix it there for #4, so it's fixed and attached here!  Thank you!
[Processed.Gas.ALDC.Index.Actual.DA.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/13055186/Processed.Gas.ALDC.Index.Actual.DA.pdf)

**Comment by eelzi-ONRR** [comment]
@jpetersononrr These changes have been made. I also updated the PDF link on the overview tab to go to the new file you sent
https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act

**Comment by jpetersononrr** [comment]
Thank you!

The title on the top need's a hyphen in "arm's-length".
Same in the assumptions drop down on the example tab.

On Part A 07, the tab has grey text on the "regulatory minimum price"
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/64428541/9ef03b07-e1b4-4243-a3e6-19d5318598c7)

That's all I see!  Thank you!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr Thank you so much for catching that! That gray text has been fixed. Once you review again I can push live: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act?tabs=detailed-example,part-a-pc-07

**Comment by jpetersononrr** [comment]
Just one quick thing:  Arm's-length needs hyphens in the title and on the Assumptions drop down.  Thanks!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr hyphens added: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act?tabs=detailed-example,part-a-pc-07

**Comment by jpetersononrr** [comment]
Looks great!  Thank you!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr Great! This is now live, as well as the link to it from the valuation examples landing page:

https://onrr.gov/references/valuation/pd-act

https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-dedicated-contract
