### ISSUE TITLE
Full panel/interactive example Unprocessed Dedicated Alt DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2679]
Please complete a full panel/interactive example for Unprocessed Dedicated Alt DA on this page:  https://onrr.gov/references/valuation?tabs=valuation-examples,indian&panel=index-zone-arms-length-dedicated-contract using this example:  https://onrr.gov/document/Unprocessed.Gas.ALDC.Index.Alt.DA.pdf.  The statement is the same as the unprocessed major portion example. 

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by cthomasONRR** [comment]
Acronym: "UD-Alt" (Unprocessed, Dedicated Contract, Alternative Dual Accounting)

Image file folder here: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/23af8f77-544f-4caa-ab58-65f915114196

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - thanks for helping to review this example!
https://dev-onrr-frontend.app.cloud.gov/references/valuation/ud-alt

**Comment by lpgoldstein** [comment]
@AlexandracmONRR looks great! Just a few things - 
1. Assumptions need to be expanded automatically
2. Central Rocky Mountain should have an "s" in Assumptions  step 1
3. Detailed Example Tab: Determining Dual Accounting - Check out what Erin did for Part A-C intro https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act?tabs=detailed-example,determining-dual-accounting then we can be consistent
4. Detailed Example Tab - Determining Dual Accounting Tab is missing the next tab link - as are the rest of the tabs - no connecting links

**Comment by lpgoldstein** [comment]
@AlexandracmONRR looks great! Just a few things - 
1. Assumptions need to be expanded automatically
2. Central Rocky Mountain should have an "s" in Assumptions  step 1
3. Detailed Example Tab: Determining Dual Accounting - Check out what Erin did for Part A-C intro https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-act?tabs=detailed-example,determining-dual-accounting then we can be consistent
4. Detailed Example Tab - Determining Dual Accounting Tab is missing the next tab link - as are the rest of the tabs - no connecting links

**Comment by jpetersononrr** [comment]
This looks splendid!

Just one quick thing.  On the others that had parts A, B, and C, you bolded "Complete" on the list of those parts.  Could you do that on this one too?  Totally minor!

Thank you!!

**Comment by AlexandracmONRR** [comment]
@jpetersononrr - thanks for your review! I've made the change you requested [here](https://dev-onrr-frontend.app.cloud.gov/references/valuation/ud-alt). Please let me know if there are any other edits needed. If not, I'll go ahead and post live!

**Comment by jpetersononrr** [comment]
Thank you!!  Looks good to me!

**Comment by AlexandracmONRR** [comment]
@jpetersononrr - great, the page is now live: https://onrr.gov/references/valuation/ud-alt
