### ISSUE TITLE
37TH RED EARTH FESTIVAL OUTREACH 

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2681]
37TH RED EARTH FESTIVAL OUTREACH 
June 2, 9:00 am to 6:00 pm
June 3, 9:00 am to 6:00 pm

LOCATION: NATIONAL COWBOY & WESTERN HERITAGE MUSEUM, 
1700 NE 63rd Street, Oklahoma City, OK.   (ONRR Booth will be located at the entrance to the Red Earth Art Exhibit in the lobby area)

DESCRIPTION:  The Office of Natural Resources Revenue (ONRR) Indian Outreach Office will have a booth to meet with Indian mineral owners and Indian trust property owners that attend the festival who may have questions on their Oil & Gas leases and Indian trust properties.  ONRR Outreach Information booklets will be available.
WHO SHOULD ATTEND: IIM account holders, Indian mineral owners with oil & gas leases, and other Indian Trust property owners in Oklahoma, or any Indian trust property owners from any state.
OTHER INFORMATION:  Indian Trust property owners who live outside the Oklahoma City area will be able to visit with the ONRR Outreach staff and ask questions who may benefit by speaking to a staff member on their specific Indian trust property questions.  Information booklets will be available to take to help understand the oil & gas leasing process.  ONRR has Outreach offices in Denver, CO and Farmington, NM who work with owners and their inquiries in their specific areas.  For more information please contact the ONRR Outreach Office at the numbers below. The OKC Outreach Office hours are Mon.- Fri. from 8:00 am-4:30 pm.
CONTACT: ONRR OKC Outreach Office, Phone: Toll-free (800) 354-7015 or main number at (405) 879-6050.  EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

SAN JUAN COLLEGE, SCHOOL OF ENERGY OUTREACH

June 6, 2023
       Tuesday at 10:00 am MST
       Tuesday at 1:00 pm MST

LOCATION: San Juan College, School of Energy, Farmington, NM

DESCRIPTION: The Federal Indian Minerals Office (FIMO) will conduct ‘One-to-One’ type sessions for mineral/landowners with questions regarding their oil & gas royalties, any letters they may have received from oil & gas companies, and letters from BIA regarding their trust land.  Representatives from Eastern Navajo Agency, Bureau of Indian Affairs, Probates Office will be available to discuss topics regarding probate status and the American Indian Probate Reform Act.  Information booklets will be available.
WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area, or any mineral owners located in the Four Corners Region.
OTHER INFORMATION: The Federal Indian Minerals Office is open from Monday through Friday, 8:00AM to 12:00PM (MST), closed during the lunch hour; re-open 1:00PM to 4:00PM (MST).  ONRR has Outreach offices in Oklahoma City, OK, and Denver, CO, who work with inquiries from Indian Trust property owners in their areas.
CONTACT: Federal Indian Minerals Office, (800) 283-2839
EMAIL: [leona.begay@onrr.gov](mailto:leona.begay@onrr.gov), [jennifer.benally@onrr.gov](mailto:jennifer.benally@onrr.gov)

OJO ENCINO CHAPTER HOUSE OUTREACH
June 8, 2023
Thursday, 10:00 am – 1:00 pm MST

LOCATION: Ojo Encino Chapter House, Ojo Encino, NM

DESCRIPTION: The Federal Indian Minerals Office (FIMO) will conduct ‘One-to-One’ type sessions for mineral/landowners with questions regarding their oil & gas royalties, any letters they may have received from oil & gas companies, and letters from BIA regarding their trust land.  Representatives from Eastern Navajo Agency, Bureau of Indian Affairs, Probates Office will be available to discuss topics regarding probate status and the American Indian Probate Reform Act.  Information booklets will be available.
WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area, or any mineral owners located in the Four Corners Region.
OTHER INFORMATION: The Federal Indian Minerals Office is open from Monday through Friday, 8:00AM to 12:00PM (MST), closed during the lunch hour; re-open 1:00PM to 4:00PM (MST).  ONRR has Outreach offices in Oklahoma City, OK, and Denver, CO, who work with inquiries from Indian Trust property owners in their areas.
CONTACT: Federal Indian Minerals Office, (800) 283-2839
EMAIL: [leona.begay@onrr.gov](mailto:leona.begay@onrr.gov), [jennifer.benally@onrr.gov](mailto:jennifer.benally@onrr.gov)

PUEBLO PINTADO CHAPTER HOUSE OUTREACH
June 13, 2023
Tuesday, 10:00 am – 1:00 pm MST

LOCATION: Pueblo Pintado Chapter House, Pueblo Pintado, NM

DESCRIPTION: The Federal Indian Minerals Office (FIMO) will conduct ‘One-to-One’ type sessions for mineral/landowners with questions regarding their oil & gas royalties, any letters they may have received from oil & gas companies, and letters from BIA regarding their trust land.  Representatives from Eastern Navajo Agency, Bureau of Indian Affairs, Probates Office will be available to discuss topics regarding probate status and the American Indian Probate Reform Act.  Information booklets will be available.
WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area, or any mineral owners located in the Four Corners Region.
OTHER INFORMATION: The Federal Indian Minerals Office is open from Monday through Friday, 8:00AM to 12:00PM (MST), closed during the lunch hour; re-open 1:00PM to 4:00PM (MST).  ONRR has Outreach offices in Oklahoma City, OK, and Denver, CO, who work with inquiries from Indian Trust property owners in their areas.
Contact: Federal Indian Minerals Office, (800) 283-2839
Email: [leona.begay@onrr.gov](mailto:leona.begay@onrr.gov), [jennifer.benally@onrr.gov](mailto:jennifer.benally@onrr.gov)

KAULEY VIRTUAL OUTREACH MEETING
Thursday, June 15, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with a brief introduction by the ONRR representative followed by updates from agency representatives.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 
WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Southern Plains region.
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015 prior to the meeting. The OKC Outreach Office hours are Mon.- Fri. from 8:00 am-4:30 pm.
CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or our main number at (405) 879-6050.  EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

SHIPROCK CHAPTER HOUSE OUTREACH
June 20, 2023
2 Sessions – Tuesday at 10:00 am MST or,
  Tuesday at 1:00 pm MST

Location: Shiprock Chapter House, Shiprock, NM
[EVENT CAL JUNE 2023 OKC FINAL.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/11569915/EVENT.CAL.JUNE.2023.OKC.FINAL.docx)

Description: The Federal Indian Minerals Office (FIMO) will conduct ‘One-to-One’ type sessions for mineral/landowners with questions regarding their oil & gas royalties, any letters they may have received from oil & gas companies, and letters from BIA regarding their trust land.  Representatives from Eastern Navajo Agency, Bureau of Indian Affairs, Probates Office will be available to discuss topics regarding probate status and the American Indian Probate Reform Act.  Information booklets will be available.
Who Should Attend: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area, or any mineral owners located in the Four Corners Region.
Other Information: The Federal Indian Minerals Office is open from Monday through Friday, 8:00AM to 12:00PM (MST), closed during the lunch hour; re-open 1:00PM to 4:00PM (MST).  ONRR has Outreach offices in Oklahoma City, OK, and Denver, CO, who work with inquiries from Indian Trust property owners in their areas.
Contact: Federal Indian Minerals Office, (800) 283-2839
Email: [leona.begay@onrr.gov](mailto:leona.begay@onrr.gov), [jennifer.benally@onrr.gov](mailto:jennifer.benally@onrr.gov)

**Comment by Maroyafaied** [comment]
@Toddsand21 Thanks for submitting a request, @eelzi-ONRR will work on this tomorrow (5/26). Thanks

**Comment by eelzi-ONRR** [comment]
@Toddsand21 For June 6 at San Juan College - is that one session from 10 am - 1 pm, or should it be listed as two sessions like June 20th Shiprock is?

**Comment by eelzi-ONRR** [comment]
@Toddsand21 This is ready for review. I made the San Juan college one session, but we can easily change then when you review. I figured you probably want to get this live today before the long weekend.

https://dev-onrr-frontend.app.cloud.gov/events

**Comment by eelzi-ONRR** [comment]
Discussed via email and pushed live

@Toddsand21 I'll leave this issue open until Tuesday when you can review https://onrr.gov/events

**Comment by Toddsand21** [comment]
Thanks Erin, what I've seen looks good.  I'll take a better look at it on Tuesday.
