### ISSUE TITLE
[Security] Vulnerability 

### ISSUE THREAD

**Issue by 3t4n-bf** [DOI-ONRR/onrr.gov-site#2691]
Hey ONRR Team, we would like to report a vulnerability directly to your team, bugcrowd.com triangulation team seems to be ineffective.  Email communication should be okay!

**Comment by Maroyafaied** [comment]
@3t4n-bf please feel free to email onrrweb@onrr.gov. Thanks

**Comment by Maroyafaied** [comment]
Moving this to backlog since we haven't heard back.

**Comment by Maroyafaied** [comment]
Closing this issue since there's no response.
