### ISSUE TITLE
Update May NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2696]
Good afternoon,

Please update onrr.gov with the May NYMEX prices according to the attachment.

Thank you!

@sudarr
[NYMEX052023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11657811/NYMEX052023.xlsx)

**Comment by lpgoldstein** [comment]
@boices Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices live https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices!
