### ISSUE TITLE
Indian Index Zone prices for June 2023

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2697]
Good morning! I'm writing to request that the June 2023 Indian Index Zone prices be posted to the ONRR.gov website. The file with the information will be sent momentarily. Thank you! @sudarr

**Comment by lpgoldstein** [comment]
@penvosej Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2023

**Comment by lpgoldstein** [comment]
@penvosej live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
