### ISSUE TITLE
Compare analytics with outreach events

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2698]
Look at our site visits, behavior, aquisition, and bounce rates across months and compare any spikes with the timing of our outreach efforts

**Comment by eelzi-ONRR** [comment]
@Maroyafaied [Pageviews and Outreach](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Outreach/Analytics%20and%20outreach.xlsx?d=w5b9c2cb800c647f8858ee3fede244811&csf=1&web=1&e=wKoHk0)

The most consistent outreach related increases in use seem to come from blog posts. There is a presentation or two that also correlated with a spike but for the most part those don't seem to increase page views enough to make a difference in the graphs. 

We can also use these graphs to analyze the spikes that don't seem outreach related.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Wow this is more than awesome, we should make this comparison more regularly everytime we publish a blog or at least on annual basis. I'll take a deeper look at the graphs and will def include some in the FY23 performance visual sheet.
