### ISSUE TITLE
Review About page against web content requirements

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2699]
https://digital.gov/resources/required-web-content-and-links/?=checklist#about-page-2

About Page

You are required to have an “About” page on your site.

On your primary agency site, you would include information about the agency with descriptions of the agency organization structure, mission, and statutory authority, and links to the following information:

1. the agency’s strategic plan and annual performance plans;
2. the agency’s Privacy Program Page;
3. the agency point of contact as required by the Small Business Paperwork Relief Act of 2002
4. the agency’s Open Government Page;
5. the agency’s Plain Writing Page;
6. information as required under the No Fear Act of 2002;
7. information associated with the agency’s implementation of the Information Quality Act.

Required on:
Your principal website
Any known sub-agency site
Any known major entry points to your sites
Required by:
OMB M-17-06, Policies for Federal Agency Public Websites and Digital Services (PDF, 1.2 MB, 18 pages, November 2016)

**Comment by cthomasONRR** [comment]
I have a working audit document located [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/About%20page%20audit.docx?d=w637a23bbad9c44d29bc4cd88169d3555&csf=1&web=1&e=zZtkAM)

**Comment by cthomasONRR** [comment]
@lpgoldstein and @eelzi-ONRR The onrr about page is ready for your review. https://dev-onrr-frontend.app.cloud.gov/about. For the contact card, I added it in the same format as the other information request contact cards, and it's a bit annoying that there's only 5 cards to a page. This is the 6th card so there's pagination now. I'm not sure if we can modify this without developer help.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Everything looks good!

**Comment by lpgoldstein** [comment]
@cthomasONRR looks great!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein Thanks! I might hold off publishing this until Maroya is back for final review. I'm also thinking about sending it to Heidi for review.

I have a PR out for making the same updates in NRRD. I'll tag yall when it's ready for review.

**Comment by cthomasONRR** [comment]
Updates are live. Closing this issue.
