### ISSUE TITLE
DISC ONRR.gov Contact Updates

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2703]
Please update the Leases & Agreements and Oil & Gas Production contacts located here - https://www.onrr.gov/about/contact.

All changes are highlighted in yellow on the shared contacts spreadsheet.  There is one update on the Oil & Gas Production tab.  There are several changes on the Leases & Agreements tab.  Please let me know if you have any questions.

Thank You
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/about/contact
Please review and give us your approval to go live. 

Thanks!
Christine

**Comment by bowlenj** [comment]
You are so fast, thank you!!!!!!!!!!!!

This looks great, approve to push live and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, June 7, 2023 10:45 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC ONRR.gov Contact Updates (Issue #2703)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/about/contact
Please review and give us your approval to go live.

Thanks!
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Thanks! These changes are now live: https://www.onrr.gov/about/contact.

Closing this issue now,
Christine
