### ISSUE TITLE
Form ONRR-2014 Edit Listing tab loading with spelling error

### ISSUE THREAD

**Issue by NSweeneyonrr** [DOI-ONRR/onrr.gov-site#2705]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Hello!
When I click on the link for the document titled, "Form ONRR-2014 - Complete List of Edits" located here: https://www.onrr.gov/reporting/revenue?tabs=references  The tab at the top of my screen shows "Forn ONRR-2014 Edit Listing" (see attached screen shot).  Can this be updated to change Forn to Form?  
Thank you!!!
[Form ONRR-2014 Edit listing spelling correction.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/11681825/Form.ONRR-2014.Edit.listing.spelling.correction.docx)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Hello, this typo is actually in the PDF title. You can make this edit within the PDF.
Since we are not the document owner, and I believe you submitted an updated version of this document in March, could you please make this edit? You can send the corrected PDF to me through this issue and I will upload it on the website.

Thanks!
Christine

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

You can make this edit in the PDF by opening the document, and then going to file > properties. Attached is a screen grab of where to change the title.

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/f128d50a-1faf-42bd-943c-7a391b36930d)

**Comment by NSweeneyonrr** [comment]
Thanks @cthomasONRR
The screen shot helped a ton.  I think I have it fixed.  Thank you so much for the insight on how/where to update it.  I think it should be good to go now!
[Form ONRR-2014 Edit Listing - March 2023 Version.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/11681957/Form.ONRR-2014.Edit.Listing.-.March.2023.Version.pdf)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

The PDF looks great!
The update is in dev for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references
Please let me know if you approve to go live.

Thanks,
Christine

**Comment by NSweeneyonrr** [comment]
@cthomasONRR 

Thanks!  I've confirmed it looks good in dev and is ready for the live site.

Thank you for your help on this!
