### ISSUE TITLE
Begin with IGNACIO, CO IN-PERSON OUTREACH MEETING           

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2707]
To add to June Events

[EVENT CAL DEN JUNE 2023.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/11707717/EVENT.CAL.DEN.JUNE.2023.docx)

Please let me know if I need to paste the whole file here or will this file is all you need.  Thanks,

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Do you want the June 14 & 15 in-person outreach formatted like the multi-event trips we did last month? Or do you want a separate entry for each one?

And do you want the June events that have passed to be taken off the page?

**Comment by Toddsand21** [comment]
Leave the June events up so our managers can see them in case they are out at this time.

**Comment by eelzi-ONRR** [comment]
@Toddsand21 This is ready for review: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
It looks good and ready to post.  Thanks for your help!

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Great! It's live so I'll close out this issue. https://onrr.gov/events

**Comment by Toddsand21** [comment]
LOOKS GREAT. THANKS!

Sandra Todd
Minerals Revenue Specialist
Office of Natural Resources Revenue
Oklahoma Indian Outreach
Direct (405) 879-6052
Main (405) 879-6050
Toll-free (800) 354-7015
________________________________
From: Erin Elzi ***@***.***>
Sent: Friday, June 9, 2023 3:00 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Todd, Sandra L. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Begin with IGNACIO, CO IN-PERSON OUTREACH MEETING (Issue #2707)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2707<https://github.com/DOI-ONRR/onrr.gov-site/issues/2707> as completed.
