### ISSUE TITLE
Change "Operator's" to "Operations" in all references to the OGOR

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2709]
This request came through email. 

Can you and your team please look at all applicable references and links on onrr.gov and ensure that the OGOR is reflected as the Oil and Gas Operations Report” and not referred to as the Oil and Gas Operator’s Report”?

**Comment by lpgoldstein** [comment]
<img width="824" alt="image001" src="https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/c5c23ddc-ef6b-4cb5-9a10-8961433e3952">
