### ISSUE TITLE
Webpage Update - New Lease Agreement XREF file for onrr.gov - June 2023

### ISSUE THREAD

**Issue by hasketta** [DOI-ONRR/onrr.gov-site#2712]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “June 2023 Lease Agreement XREF.txt" and "June 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 6/14/2023.

[June 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/11749822/June.2023.Lease.Agreement.XREF.txt)
[June 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11749830/June.2023.Lease.Agreement.XREF.xlsx)

**Comment by lpgoldstein** [comment]
@hasketta Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by hasketta** [comment]
Everything looks good.  Please move the link to the live site.

Thanks!

**Comment by lpgoldstein** [comment]
@hasketta live! https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
