### ISSUE TITLE
Updating to paying page 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2713]
This request came through email

Can you please consider adding "30" in front of this citation CFR §1218.51 (b) on the top of the paying page at: https://www.onrr.gov/paying.

I would consider linking it to the CFR online at: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1218/subpart-B/section-1218.51.

 

Please let me know if you have any questions.

Thanks,

**Comment by lpgoldstein** [comment]
Sent to review via email: https://dev-onrr-frontend.app.cloud.gov/paying

**Comment by lpgoldstein** [comment]
Approved via email and live.
