### ISSUE TITLE
Add payment option tab

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2719]
This came through email

I would like to request another payment option tab with the following information attached for Renewable Energy Payments. I would love to go over it with someone.  Please let me know what I can do to help with this process.  Thanks!

The link to the payment options is: 

https://www.onrr.gov/paying/payment-options

**Comment by lpgoldstein** [comment]
Coordinating via email.

**Comment by lpgoldstein** [comment]
[Renewable Energy Payment Instructions.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/11834884/Renewable.Energy.Payment.Instructions.docx)
 Creating a new tab under payment options named "Renewable Energy"
