### ISSUE TITLE
Zipcode for payments by check & Public Affair's phone number 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2723]
This request came through email.

ONRR website (https://onrr.gov/paying/payment-options?tabs=check-payments) shows that payment by check can be mailed to:

U.S. Mail Address
Office of Natural Resources Revenue
PO Box 25627
Denver CO 80225-2562
 
One company (who is not a payor) pointed out that the zip code 80225-25627 has 5 digits following after the dash (after the first 5 digits of the zip code).  This person questions whether this information is correct.  Would you please verify and confirm whether the (10-digit) Zip Code in the above address is correct?

(Separately, I also noted that the phone number shown for  (ONRR Public Affairs contact) is not a working number.  See https://onrr.gov/about/public-affairs?tabs=contact-social-media.  Profile in Teams shows that his phone number is (202) 513-0614.)

**Comment by cthomasONRR** [comment]
Zip code and Chris Mentasti's phone number are both fixed, and the requestor was notified.
