### ISSUE TITLE
onrr.gov site won't load in Chrome while connected to Ivanti

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2731]
This started on Thursday 6/29/23. When I'm connected to Ivanti, the live onrr.gov site won't load in Chrome. It will load in all other browsers, and I can get the dev site to load in Chrome. This seems specific to the live site, Chrome, and being connected to Ivanti. It's continuing into Friday 6/30/32. I've restarted, cleared browsing data, used "Ctrl-F5", but still can't get it to load. We haven't gotten any user complaints yet, but I'm putting this as high-priority. Thanks.

**Comment by Maroyafaied** [comment]
@cthomasONRR which server are you connected to on Ivanti? It's working form on the California server but I haven't tried other servers 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/1ffee831-43c3-4948-8571-512eadf5f008)

**Comment by lpgoldstein** [comment]
@cthomasONRR @Maroyafaied it's working for me now too. It's happened before but always resolves itself.

**Comment by Maroyafaied** [comment]
@cthomasONRR let's test this out throughout this sprint and see if it's still an issue, if it is then I'll add @greensomes to the issue but for now I took Jeff off this issue .

**Comment by Maroyafaied** [comment]
@cthomasONRR let's test this out throughout this sprint and see if it's still an issue, if it is then I'll add @greensomes to the issue but for now I took Jeff off this issue .

**Comment by Maroyafaied** [comment]
I tested this out today and the website is loading while connected to VPN. I'll check a couple more random times throughout the week then close the issue if everything loads as expected.

**Comment by cthomasONRR** [comment]
I've been testing as well and it's loading fine while connected to VPN this week.

**Comment by Maroyafaied** [comment]
Tested again this morning and it's loading fine. Will close this issue since it doesn't seem to be an issue for now.
