### ISSUE TITLE
Update contact

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2733]
Contact needs to be updated on ONRR.Gov under Geothermal Contacts "Federal Accounts Receivable".
https://onrr.gov/about/contact/geothermal-contacts?tabs=contacts

The Primary Contact should read as the below picture. 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72033999/209e2093-2e19-4fc3-852f-dcb1201ae797)

Thank you!

**Comment by lpgoldstein** [comment]
@Sheetsj ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/geothermal-contacts?tabs=contacts

**Comment by Sheetsj** [comment]
Looks great! Good to go live.

Thank you :)

**Comment by lpgoldstein** [comment]
@Sheetsj updated! https://onrr.gov/about/contact/geothermal-contacts?tabs=contacts
