### ISSUE TITLE
June 2023 NYMEX prices ready for ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2736]
Hello, could we please have the June 2023 NYMEX price information added to the ONRR.gov website? The file with the data is attached. @sudarr
[NYMEX062023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11971801/NYMEX062023.xlsx)

**Comment by lpgoldstein** [comment]
@penvosej ready for your review https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by penvosej** [comment]
Hi Lindsay,

The website looks good! Thanks for taking care of this so quickly!

Jessica

From: lpgoldstein ***@***.***>
Sent: Thursday, July 6, 2023 2:26 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] June 2023 NYMEX prices ready for ONRR.gov (Issue #2736)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> ready for your review https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

-

**Comment by lpgoldstein** [comment]
@penvosej live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
