### ISSUE TITLE
Update July Indian Index Zone prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2737]
Good afternoon,

Please update the July prices according to the attached sheet. --Thank you!

@sudarr
[Indian_Index_Zone_2023_07.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11971965/Indian_Index_Zone_2023_07.xlsx)

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by boices** [comment]
Perfect--thanks again.

**Comment by lpgoldstein** [comment]
@boices live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
