### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – July 2023

### ISSUE THREAD

**Issue by Daphnesmum** [DOI-ONRR/onrr.gov-site#2740]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “July 2023 Lease Agreement XREF.txt" and "July 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 7/11/2023.
[July 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/12015951/July.2023.Lease.Agreement.XREF.txt)
[July 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12015955/July.2023.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@Daphnesmum 

These changes are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Daphnesmum** [comment]
The files have been reviewed in dev and are correct, please move files to the live site.

**Comment by cthomasONRR** [comment]
@Daphnesmum 
Great! These changes are now live: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
Thanks,
Christine
