### ISSUE TITLE
Updates to ONRR.gov's Indian Allowance Forms

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2741]
Good morning, 

I am requesting updates to his page https://onrr.gov/references/forms?tabs=oil-gas-revenue-reporting

Under Gas Transportation Allowance Report, please update the form ONRR-4295 with the attached document below which has a new expiration date.

[4295 8.3.2022 accessible.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12029938/4295.8.3.2022.accessible.pdf)

Please let me know if you have any questions. 
Thank you!

**Comment by cthomasONRR** [comment]
@gingerhensley 

This document is now updated: https://www.onrr.gov/references/forms?tabs=oil-gas-revenue-reporting. Please let me know if you want additional updates.

Thanks,
Christine
