### ISSUE TITLE
Updates to ONRR.gov's Solid Minerals Reporting Page 

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2742]
Good morning,

I am requesting updates to his page https://onrr.gov/references/forms?tabs=solid-minerals-reporting 

Under Paper Production & Royalty (P&R) Report please update the paper form ONRR-4430 with the attached document below which has a new expiration date.

[Form 4430 2023.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12030414/Form.4430.2023.pdf)

Please let me know if you have any questions.
Thank you!

**Comment by cthomasONRR** [comment]
@gingerhensley

This document is now updated: https://www.onrr.gov/references/forms?tabs=solid-minerals-reporting. Please let me know if you want additional updates.

Thanks,
Christine

**Comment by gingerhensley** [comment]
Thanks Christine!
