### ISSUE TITLE
Add tips for using contacts search

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2745]
As per user study 15 and issue #2528, users struggle with contacts search. While we work on improving the search, we can add some tips to the contacts search pages to help user with the way contacts search currently works.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I think this looks great!!!! Thanks :)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR There's two "the" in this sentence 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/40175688/3264549e-39c9-4fb1-801e-de80189ed176)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Fixed! Thanks for catching that

**Comment by Maroyafaied** [comment]
@eelzi-ONRR looks good
