### ISSUE TITLE
Make mailing address / general ONRR office contacts easier to find

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2746]
As per user study 15, contacts and addresses for each ONRR office is buried and difficult to find: https://onrr.gov/about/office-locations

Possible solutions include adding a link to this page in the footer, reworking one of the announcement cards to include general contact info, moving the Mailing Addresses link on the contact us page further up the page and/or linking it something else

**Comment by AlexandracmONRR** [comment]
Previous Research
- Study 15 Homepage Quick Links: Two of 11 participants had a hard time finding contacts. Two other participants discussed questions or concerns related to the contacts search function.
- Study 02 Homepage Concepts: There was some general discussion of the use of contact us on the homepage. One participant discussed their expectation that Contact Us page would contain department/region.
- Additional Requests: Request that Denver location is listed as the main office in case people mail documents to ONRR.

Potential Solutions with Prioritization

- Add address and phone number to the website footer (**High Priority - 1**)
- At bottom footer include the Contact link (already there) with the Office Location link (not there) (**High Priority - 2**)
- Contacts page to include in prominent location Denver office + general phone number + move Mailing Address link up (**High Priority - 3**)
- Make contacts button, events button, glossary button, revenue data button larger (**Medium Priority**)
This would likely happen in tandem with banner image being reduced in size.
- Rework one of the announcement cards to include general contact info (**Low Priority**)


Examples from Other Agencies
- BOEM
- DOI
- BLM
- BSEE


Link to document with [details about contact visibility on homepage information](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/[Contact-Homepage-Revisit-Oct2023](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/Contact-Homepage-Revisit-Oct2023?csf=1&web=1&e=pf940P)?csf=1&web=1&e=pf940P).


I will follow up with Implementation and Additional Questions for this later today.

**Comment by AlexandracmONRR** [comment]
After discussion, we are going to move forward with High Priority 1 and High Priority 2:

1. We will add the ONRR's address to the footer.
2. We will change the bottom "Contact Us" link to "Contacts" and we will add "Office Locations" link to the gray banner above the footer.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - thanks for making the "Contact Us" to "Contacts". Last night, I had tried to fix it in the CMS, but when I changed the label, the entire label disappeared... I tried many iterations, so I'm wondering what I had wrong.

Also, thanks for adding the address.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR , the "contacts" change needed to be done in the CMS as well as needed a code change, so you didn't do anything wrong but both had to be done. I removed the address from the header and adjusted the font in the footer (thanks to Jeff's help). Please review and if it looks good then you can show the dev site compared to the live site in demo for these changes.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied thank you for figuring that out!

I've reviewed both changes and they look good except that I noticed when you click on "Office Locations" or "Contacts" in the footer, it brings you to the bottom of the page (for both pages), is it an incorrect setting in the CMS or is that on purpose since you are in the footer?

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I'm not sure. Do other footer links open the same way? If not, then maybe Jeff would know how to fix it.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - this is actually happening inconsistently for me... so I don't think it's an issue at all. I tried with other footer links and it didn't happen and then when I went back to the Office Locations, it worked like how I would expect it to. I don't think it is a problem.

I think we are good to push these edits live.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I'll leave it in dev and will push live after demo. Thanks

**Comment by Maroyafaied** [comment]
@AlexandracmONRR the changes are on the live site. Feel free to close this issue after you review. Thanks

**Comment by AlexandracmONRR** [comment]
Changes look good. Thank you!
