### ISSUE TITLE
Add contact to trouble shooting pages for questions not answered by the listed topics

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2747]
As per user study 15, add a contact on each troubleshooting page for who to contact if the existing topic accrdions do not address their question or task

https://onrr.gov/getting-started/system-access?tabs=troubleshooting
https://onrr.gov/reporting/production?tabs=troubleshooting
https://onrr.gov/reporting/revenue?tabs=troubleshooting
https://onrr.gov/reporting/solids?tabs=troubleshooting
https://onrr.gov/reporting/geothermal?tabs=troubleshooting
https://onrr.gov/paying/contacts-paying?tabs=troubleshooting - this one has a contacts tab on the page, so it might not need anything additional

**Comment by lpgoldstein** [comment]
@eelzi-ONRR all of these trouble shooting tabs also have adjacent contact tabs? It's now seeming redundant to add more ways to contact someone. But.....what do you think about adding and additional accordion at the bottom of each troubleshooting tab that says "My issues isn't listed here" or "I still need help" and then another link to the contact page?

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I like "My issue isn't listed here" as a new accordion and a link to contacts is great!

**Comment by lpgoldstein** [comment]
- [ ] https://onrr.gov/getting-started/system-access?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/production?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/revenue?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/solids?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/geothermal?tabs=troubleshooting
- [ ] https://onrr.gov/paying/contacts-paying?tabs=troubleshooting

**Comment by lpgoldstein** [comment]
For reviewer:
- [ ] https://onrr.gov/getting-started/system-access?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/production?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/revenue?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/solids?tabs=troubleshooting
- [ ] https://onrr.gov/reporting/geothermal?tabs=troubleshooting
- [ ] https://onrr.gov/paying/contacts-paying?tabs=troubleshooting

**Comment by eelzi-ONRR** [comment]
@lpgoldstein All the accordions and links work as expected. My only suggestion is to avoid using the word "see". Maybe "visit" instead?

**Comment by lpgoldstein** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXhzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ebcc54b0f143bec2266733a3edefacc10b51d706/image.png)
[Private Zenhub Image]
[Private Zenhub Image]
[Private Zenhub Image]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a558416b65a5e163f75ac7f02f5ed854f335ce3c/image.png)
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalJzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a918e410778bf73162925af6c5ba4365045c4bba/image.png)
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakJzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--42288167e4488bec4a67b9340c178c25cc4dc2e7/image.png)
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTVzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb2ef3e924e43e464f672d34119af9b57f8019c3/image.png)

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Looks good!

**Comment by lpgoldstein** [comment]
Done.
