### ISSUE TITLE
Site search improvement: test searches and revist search.gov answers

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2753]
Users report they want to use the site search but don't find it gives them the results the expect. Start with running test searches and revising the discussions we had with search.gov

as per user research 15

**Comment by eelzi-ONRR** [comment]
@cthomasONRR If you have time to look at column D on sheet 1 that would be great - especially the ones highlighted in yellow. I'm open to feedback about anything on the spreadsheet, but especially the "expected results"

https://doimspp-my.sharepoint.com/:x:/g/personal/elzie_mms_gov/EVXHGAPePh1Jj-IJFyTUi7IBWdcrmgwn-GgHVBHbVvzeqQ?e=wAfiYy

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Attached is my downloaded version of the doc. I highlighted cells where I put comments in green. Let me know if you have any questions, or need more information. Thanks!

[Search.gov testing_clt edits.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12305747/Search.gov.testing_clt.edits.xlsx)

**Comment by eelzi-ONRR** [comment]
Ran test searches for the top 30 searches in search.gov for the past 2 months and reviewed our notes from search.gov and our options in the search.gov admin. The spreadsheet also has some notes and options to explore as solutions to improve results and ranking. https://doimspp-my.sharepoint.com/:x:/g/personal/elzie_mms_gov/EVXHGAPePh1Jj-IJFyTUi7IBWdcrmgwn-GgHVBHbVvzeqQ?e=zR0pQo
