### ISSUE TITLE
Webpage Update (Active Leases)

### ISSUE THREAD

**Issue by merrellc** [DOI-ONRR/onrr.gov-site#2758]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Please update the following webpage www.onrr.gov/ReportPay/CrossRef with the attached Excel file.
Active Lease - Sorted by State and Agency Lease. Also update the date to read 07/01/2023.
Thank you!
[ACTIVE_LEASES.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12089659/ACTIVE_LEASES.xlsx)

**Comment by lpgoldstein** [comment]
@merrellc ready for your review https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by merrellc** [comment]
Hello, ready to go live. Thank you!



Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
303-231-3517
***@***.***


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.


________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, July 19, 2023 5:02 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Webpage Update (Active Leases) (Issue #2758)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://github.com/merrellc> ready for your review https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by lpgoldstein** [comment]
It's live @merrellc
