### ISSUE TITLE
Updates to ONRR.govs Forms Page 

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2759]
Good morning, 

I am requesting updates to this page https://onrr.gov/references/forms

Under Designation Form for Royalty Payment Responsibility please update the pdf ONRR-4425 with the new attached document below 

[ONRR Form 4425 and instr_508 Compliant_05.08.2023.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12096256/ONRR.Form.4425.and.instr_508.Compliant_05.08.2023.pdf)

Please let me know if you have any questions. 
Thanks!

**Comment by lpgoldstein** [comment]
@gingerhensley The pdf doesn't pass the accessibility requirements. Here is the report to assist remediation. 
[Acrobat Accessibility Report_4425.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/12096498/Acrobat.Accessibility.Report_4425.pdf)

**Comment by lpgoldstein** [comment]
@gingerhensley This one looks good. One question - does the revision date need to be updated in the document? It reads 7/31/2021.

**Comment by gingerhensley** [comment]
The only thing that was updated was the Privacy Act language, and just a citation. The DOI clearance officer mentioned it's not a substantive change, so I don't think we need to update the revision date.

**Comment by lpgoldstein** [comment]
@gingerhensley Got it - ready for review: https://dev-onrr-frontend.app.cloud.gov/references/forms

**Comment by gingerhensley** [comment]
Looks great, thanks!
