### ISSUE TITLE
Update Reference Lists

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2762]
Please replace the existing spreadsheet in Reference Lists on the following webpage - https://www.onrr.gov/reporting/revenue?tabs=references, with the attached spreadsheet.

100% Federal Agreements with the Same Royalty Rate & Royalty Distributions
Also please change the date (updated 04/04/2023) to (updated 07/24/2023)

[fedagmts.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12147902/fedagmts.xlsx)

Thank You
Jessica

**Comment by cthomasONRR** [comment]
@bowlenj Great! These changes are now live: https://www.onrr.gov/reporting/revenue?tabs=references
