### ISSUE TITLE
Add indication of focus to interactive elements - buttons 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#2768]
![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/a7451c2f-d224-46de-b330-c2f4de07ca09)![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/b87103b3-bc72-4cd0-8db7-2938bbb648cd)

All buttons on the site 

![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/012f96b7-8e48-4101-a273-abe9063803ba)

**Comment by eelzi-ONRR** [comment]
See issue #2964 for info about using USWDS buttons

**Comment by greensomes** [comment]
This is ready in [preview](https://preview-onrr-frontend.app.cloud.gov/).

**Comment by eelzi-ONRR** [comment]
It's perfect! Checked all buttons and links on the home page
