### ISSUE TITLE
Fix ambiguous link titles - links within text

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#2772]
examples -"download" on NYMEX 
view "press release document"

https:/"onrr.gov/about/public-affairs
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanF0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca9abf2ca28df91cab35e64ae252fa16b4951f10/image.png)

"view all"
https://onrr.gov/
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam10IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c10cf3f2184c36413341141435313f05d8770699/image.png)

**Comment by cthomasONRR** [comment]
Revising this issue to be for ambiguous links that are NOT part of a collection or formatted as a button. Issue numbers #3221 and #3178 address those as they are currently blocked.
