### ISSUE TITLE
Updates to ONRR.gov's Rulemaking Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2787]
Good afternoon,
I am requesting updates to this page https://onrr.gov/references/rulemakings

Under Rulemakings, please add a rule to the top of the list. The rule should read as follows:

Final Publication Date RIN Rule Title Topics
2023-07-21       1012-AA34            Partial Repeal of Consolidated Federal Oil & Gas and Federal & Indian Coal Reform        Federal Oil, Federal Gas, Federal Coal, Indian Coal

Please add a new RIN page as a hyperlink to the "Partial Repeal of Consolidated Federal Oil & Gas and Federal & Indian Coal Reform" consistent with other RIN pages.
On the RIN page, please create this below:
"Regulation Identifier Number 1012-AA34
Partial Repeal of Consolidated Federal Oil & Gas and Federal & Indian Coal Reform
30 CFR Parts 1202 and 1206
Abstract: ONRR is republishing and revising certain subparts of its regulations to implement an order and judgment from the United States District Court for the District of Wyoming that vacated the Federal and Indian coal valuation provisions of the 2016 Consolidated Federal Oil & Gas and Federal & Indian Coal Valuation Reform rule. ONRR is further making non-substantive punctuation and grammatical corrections as part of this republication.

Please then add the following bullet:

"Final Rulemaking: 88 FR47003 (7/21/2023)

Please add this hyperlink to the language above https://www.federalregister.gov/documents/2023/07/21/2023-15310/partial-repeal-of-consolidated-federal-oil-and-gas-and-federal-and-indian-coal-reform

Please let me know if you have any questions.
Ginger Hensley

**Comment by cthomasONRR** [comment]
@gingerhensley 

These updates are in dev for your review:
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa34

Please let me know if you approve for these to go live.

Thanks,
Christine

**Comment by gingerhensley** [comment]
Looks great, approve! 
Thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley Great! This is now live:
https://www.onrr.gov/references/rulemakings
https://www.onrr.gov/references/rulemakings/aa34

Thanks,
Christine
