### ISSUE TITLE
Wind River IBMP Price Changes for PC63 for April 2017 to December 2022

### ISSUE THREAD

**Issue by damionschulte** [DOI-ONRR/onrr.gov-site#2793]
Hi All,  We recently had to recalculate the IBMP prices for Wind River PC63 from April 2017 – December 2022.  Attached is a sheet with the new IBMP prices for Wind River PC63 for these months.  Please let me know if there is anything else you need me to do.  

Thanks 
[Price Corrections for GitHub.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12314899/Price.Corrections.for.GitHub.xlsx)

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion&designated_area=Wind%20River

**Comment by damionschulte** [comment]
All the prices you look good except for August 2020. The price in the system is $34.76 and it should be $36.41

From: lpgoldstein ***@***.***>
Sent: Monday, August 14, 2023 7:51 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Wind River IBMP Price Changes for PC63 for April 2017 to December 2022 (Issue #2793)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion&designated_area=Wind%20River

-

**Comment by lpgoldstein** [comment]
@damionschulte great - fixed and please review -https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion&designated_area=Wind%20River&years=2020

**Comment by damionschulte** [comment]
These look good thank you.

From: lpgoldstein ***@***.***>
Sent: Monday, August 14, 2023 10:43 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Wind River IBMP Price Changes for PC63 for April 2017 to December 2022 (Issue #2793)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> great - fixed and please review -https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion&designated_area=Wind%20River&years=2020

-

**Comment by lpgoldstein** [comment]
@damionschulte It's live!

**Comment by damionschulte** [comment]
It looks like the new prices have not hit the website yet?  Will it take a little bit?


From: lpgoldstein ***@***.***>
Sent: Monday, August 14, 2023 11:28 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Wind River IBMP Price Changes for PC63 for April 2017 to December 2022 (Issue #2793)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> It's live!

-

**Comment by lpgoldstein** [comment]
@damionschulte I see them on the live site. Try refreshing and then clearing cache and refreshing if you still don't see it. There shouldn't be a delay.

**Comment by damionschulte** [comment]
They are still not showing up for me. Not sure what is going on

From: lpgoldstein ***@***.***>
Sent: Monday, August 14, 2023 12:32 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Wind River IBMP Price Changes for PC63 for April 2017 to December 2022 (Issue #2793)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> I see them on the live site. Try refreshing and then clearing cache and refreshing if you still don't see it. There shouldn't be a delay.

-

**Comment by damionschulte** [comment]
Never mind.  The prices are good.  I was linking to the old site and didn't realize what was going on.  Thanks again for all the work and sorry for the confusion.

From: lpgoldstein ***@***.***>
Sent: Monday, August 14, 2023 12:32 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Wind River IBMP Price Changes for PC63 for April 2017 to December 2022 (Issue #2793)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> I see them on the live site. Try refreshing and then clearing cache and refreshing if you still don't see it. There shouldn't be a delay.

-

**Comment by lpgoldstein** [comment]
@damionschulte Great, thanks for letting me know.
