### ISSUE TITLE
Lease & Agreement Contact Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2799]
Please update the onrr.gov contacts on the following page using the shared "Contact Spreadsheet" - https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

All changes are on the Leases & Agreements tab of the spreadsheet and are highlighted in yellow.  Please not that an additional line has been added for Offshore Leases, it's now been split between the different regions.  Also please note that Unidentified Lines has been removed from the spreadsheet.  We no longer need the Unidentified Lines for Federal and Indian on ONRR.gov.

Please let me or Candace Merrell know if you have any questions.

Thank you
Jessica Bowlen

**Comment by Maroyafaied** [comment]
@bowlenj we will need a developer to look at this since the request is asking for an additional line to be added and that requires code change. It might take some time since we don't have a full-time developer but I will keep you updated. Thanks

**Comment by bowlenj** [comment]
Thank you, please let me know if you need anything additional from me.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, August 14, 2023 12:48 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Lease & Agreement Contact Update (Issue #2799)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> we will need a developer to look at this since the request is asking for an additional line to be added and that requires code change. It might take some time since we don't have a full-time developer but I will keep you updated. Thanks

**Comment by bowlenj** [comment]
That's perfect!!!  Thank you 🙂

Approved for live and to close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, August 14, 2023 1:53 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Lease & Agreement Contact Update (Issue #2799)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> Yes, that works! Please review and let me know if it's ready to go live https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by Maroyafaied** [comment]
This is live. Thanks
