### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov - August 2023

### ISSUE THREAD

**Issue by hasketta** [DOI-ONRR/onrr.gov-site#2804]
______________________________________________________________________________________________________________________________________
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “August 2023 Lease Agreement XREF.txt" and "August 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 8/17/2023.
[August 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/12373049/August.2023.Lease.Agreement.XREF.txt)
[August 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12373051/August.2023.Lease.Agreement.XREF.xlsx)

**Comment by eelzi-ONRR** [comment]
@hasketta The files have been replaced and the Updated date changed to today. This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by hasketta** [comment]
The files have been reviewed and are correct.  Please move files to live site.

**Comment by eelzi-ONRR** [comment]
@hasketta This is now live: https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Have a great weekend!
