### ISSUE TITLE
Oklahoma map for pricing page - 508 compliant pdf and add to onrr.gov

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#2810]
Work with Jessica on MSA to make the pdf compliant.

**Comment by lpgoldstein** [comment]
[Oklahoma_Counties_Index_Zones_Updated_Colors.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa05TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--13665abe56ecb4208e84ca86e1882eedc7b7b633/Oklahoma_Counties_Index_Zones_Updated_Colors.pdf)

**Comment by lpgoldstein** [comment]
@jessmanko ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&panel=counties-for-oklahoma-index-zones

**Comment by lpgoldstein** [comment]
Jess is out of the office until next sprint so moving issue.

**Comment by jessmanko** [comment]
@lpgoldstein Looks great, thank you!!
