### ISSUE TITLE
Reach out to MSA and users to update them on pricing table enhancements

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2815]
- [x] @cthomasONRR will reach out to MSA
- [x] @lpgoldstein will reach out to users

**Comment by cthomasONRR** [comment]
I found MSA's initial email from reviewing the Beta site in September 2022. I responded to this email chain in the onrr.gov inbox:

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/b9774ecf-bbe9-4e3e-bb6e-5199e7a4b991)

**Comment by lpgoldstein** [comment]
Sent an email to 12 users that had interest in the pricing tables and recorded communication in the Research Participant Pool - including email to Cory.
