### ISSUE TITLE
EVENT CALENDAR  under Indian Resources Tab

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2817]
Please see the attached file for my new issue to be added for September Events.____________________________________________________________
Please email if you have questions.  I will be out tomorrrow but I will check my mail periodically.  Must be posted by September 1 and no later than 9/05.  Thanks

[EVENT CAL_SEP 2023_OUTREACH .docx](https://github.com/DOI-ONRR/onrr.gov-site/files/12490845/EVENT.CAL_SEP.2023_OUTREACH.docx)

**Comment by Toddsand21** [comment]
I will check my email tomorrow to proof and make corrections if needed. You can text me at 405.820.3444 anytime. Thanks.

**Comment by lpgoldstein** [comment]
@Toddsand21 This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
Please add on the Location for Seminole Nation Days,, add...to read:   Location:  Seminole Nation Mekusukey Mission before the address  Also add in the directions in the parenthesis to read: (Near the Seminole Nation Mekusukey Mission Gym, 1 mi south of Seminole on Hwy 59 West)

**Comment by Toddsand21** [comment]
In the Kauley Meeting Heading take out the word "Virtual"

**Comment by Toddsand21** [comment]
For the Kauley Meeting please add the following after the last sentence in the Description. 
Please call to reserve a space at this meeting.  See contact information below.

**Comment by lpgoldstein** [comment]
@toddsand21 Ready for your review again.

**Comment by Toddsand21** [comment]
Did you send a link?

**Comment by lpgoldstein** [comment]
@Toddsand21 Sorry, it's the same as before: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
Can you add the following sentence the end of the end of paragraph for Other Information on both of these events. for Seminole and Comanche Fair?
The OKC Outreach Office hours are Mon.- Fri. from 8:00 am-4:30 pm.
Everything else is fine.

**Comment by lpgoldstein** [comment]
@Toddsand21 Added and published.

**Comment by Toddsand21** [comment]
I'll take a look at it once it does post but I thought I would just shorten the paragraph and replace it with this paragraph on Other Information for those 2 events with the following.  
Information booklets will be available for owners to take with information on where to contact an ONRR office. ONRR also has Outreach offices in Denver, CO, Farmington, NM and Oklahoma City, OK, who work with Indian Trust property owners in their areas.  The OKC Outreach Office hours are Mon.- Fri. from 8:00 am-4:30 pm

But no problem if it's already posted we will just go with the last update you posted.  Maybe we'll make changes, if necessary, at a later date.

**Comment by lpgoldstein** [comment]
@Toddsand21 edited and published. Have a great weekend!

**Comment by Toddsand21** [comment]
On Other Information I did see a mistake on that first sentence on those 2 events for Seminole Days and Comanche Fair.  The sentence should read and end with ,,,
and Indian Trust properties.   
and not end with...... Indian Trust property owners.

**Comment by Toddsand21** [comment]
I seen the edited verson on our site.  It looks good!  Thanks you for posting i last minute.. Enjoy your holiday weekend!
