### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – September 2023

### ISSUE THREAD

**Issue by Daphnesmum** [DOI-ONRR/onrr.gov-site#2819]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “September 2023 Lease Agreement XREF.txt" and "September 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 9/5/2023.
______________________________________________________________________________________________________________________________________

[September 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12524410/September.2023.Lease.Agreement.XREF.xlsx)
[September 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/12524424/September.2023.Lease.Agreement.XREF.txt)

**Comment by lpgoldstein** [comment]
@Daphnesmum ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by lpgoldstein** [comment]
@Daphnesmum ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by lpgoldstein** [comment]
Noting that Donna is out of the office so not sure when she will review.

**Comment by Daphnesmum** [comment]
My apologies, I sent this data out for peer review on Tuesday morning and have not received a reply from that Analyst. I will follow up this morning.

Donna Galloway, Program Analyst
Information and Data Management
Data Optimization, Retrieval, and Coordination (DORC)
Office of Natural Resources Revenue (ONRR)
(303) 231-3353  ***@***.******@***.***>

DORC email:
***@***.******@***.***>

________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, September 6, 2023 10:45 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Galloway, Donna J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Webpage Update - New Lease Agreement XREF files for onrr.gov – September 2023 (Issue #2819)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Noting that Donna is out of the office so not sure when she will review.

**Comment by lpgoldstein** [comment]
@Daphnesmum thanks for letting me know.

**Comment by Daphnesmum** [comment]
The files have been reviewed in dev this morning and are correct, please move files to the live site.

**Comment by lpgoldstein** [comment]
@daphnesmum this is live - https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
