### ISSUE TITLE
DISC Contact Page Updates

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2821]
Please update the DISC contacts using the shared spreadsheet for each section as shown below:

Lease & Agreements - all updates needed have been highlighted in yellow
Onshore Production - all updates needed have been highlighted in yellow
Offshore - this section had a complete overhaul with new contacts for each code.  It may be best to upload the entire spreadsheet, I did not highlight the changes since everything pretty much changed.

Please let me know if you have any questions or need additional information.

Thank you
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

These are ready for your review in dev:

- [ ] https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
- [ ] https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
- [ ] https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Please let us know if you approve to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great!  I approve to push to Live and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, September 5, 2023 11:57 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Page Updates (Issue #2821)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

These are ready for your review in dev:

  *    https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
  *    https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
  *    https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Please let us know if you approve to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these are now live:

- [ ] https://www.onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
- [ ] https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
- [ ] https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Thanks,
Christine

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, September 5, 2023 6:26:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Page Updates (Issue #2821)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

Great, these are now live:

  *    https://www.onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
  *    https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
  *    https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Thanks,
Christine
