### ISSUE TITLE
Update Interest Calculator and Interest on site

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2822]
Hello,
On the late Payment & Underpayment Interest Table page, at https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas, please make the following updates:

Add a new line at the top of the Late Payment & Underpayment table for Period 10/1/2023-12/31/2023. Oil and gas has changed to 8%.         

On the Late Payment & Underpayment Interest Table page, at https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal

Add a new line at the top of the Late Payment & Underpayment table for Period 10/1/2023-12/31/2023. Solid's remains the same at 3%.   

Replace the Interest Calculator excel file at https://onrr.gov/paying/interest?tabs=interest-calculator with the attached below:

[Interest_Calculator_Master_v2.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12526430/Interest_Calculator_Master_v2.xlsx)

Thank you,
Jessica

**Comment by lpgoldstein** [comment]
@Sheetsj This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,oil-gas
https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal
https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-calculator
