### ISSUE TITLE
September 2023 Indian Index Zone prices

### ISSUE THREAD

**Issue by WW-Git-Hub** [DOI-ONRR/onrr.gov-site#2824]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
The subject prices are ready for uploading.
[Indian_Index_Zone_2023_09.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12538181/Indian_Index_Zone_2023_09.xlsx)

**Comment by cthomasONRR** [comment]
@WW-Git-Hub 

These prices are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

Please review and give us approval to go live.

Thanks,
Christine

**Comment by WW-Git-Hub** [comment]
The prices are correct and ready to be posted.


Thanks,

Walter



From: Christine Thomas ***@***.***>
Sent: Wednesday, September 6, 2023 9:33 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Weathersby, Walter B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] September 2023 Indian Index Zone prices (Issue #2824)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@WW-Git-Hub<https://github.com/WW-Git-Hub>

These prices are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

Please review and give us approval to go live.

Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@WW-Git-Hub 

Great! These changes are now live: https://www.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

Thanks,
Christine
