### ISSUE TITLE
Add August NYMEX prices to ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2828]
The August 2023 NYMEX prices are ready to be posted to ONRR.gov. The file with the data is attached. Thank you!”
@sudarr
[NYMEX082023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12542952/NYMEX082023.xlsx)

**Comment by lpgoldstein** [comment]
@penvosej ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by penvosej** [comment]
Hi, Lindsay,

The ONRR.gov page with the NYMEX price looks good. Thanks for taking care of this!

Jessica

From: lpgoldstein ***@***.***>
Sent: Wednesday, September 6, 2023 4:51 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add August NYMEX prices to ONRR.gov (Issue #2828)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

-

**Comment by lpgoldstein** [comment]
@penvosej live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
