### ISSUE TITLE
Update's to ONRR.gov's Information Collection Request Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2838]
Hello,

I am requesting updates to this page https://onrr.gov/references/icrs/1012-0006

Please add a new bullet under "Federal Register Publications" with the below: 

60-Day Agency Information Collection - (88 FR 63973--September 18, 2023)

Please add the hyperlink below to "Agency Information Collection" 
https://www.federalregister.gov/documents/2023/09/18/2023-20090/agency-information-collection-activities-suspensions-pending-appeal-and-bonding

Thank you!

**Comment by lpgoldstein** [comment]
@gingerhensley ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0006

**Comment by gingerhensley** [comment]
Approved. Thank you!

**Comment by lpgoldstein** [comment]
@gingerhensley This is live! https://onrr.gov/references/icrs/1012-0006
