### ISSUE TITLE
Complete Survey on Prototypes/Sketches ideas

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2839]

**Comment by Maroyafaied** [comment]
I accidently filled out two surveys. The first one I submitted only has answers for page 4 and the second I submitted has my answers for pages 1-3.

**Comment by cthomasONRR** [comment]
I completed & submitted my survey.

**Comment by lpgoldstein** [comment]
Done

**Comment by eelzi-ONRR** [comment]
Done.

The survey closes this afternoon and everyone that's working today has responded so I'm closing the issue
