### ISSUE TITLE
Prepare a shutdown banner/message

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2840]
This is the message that was user previously on NRRD.
"Due to the government shutdown, we are not able to update this site. We will resume work on the site when the shutdown ends."

**Comment by eelzi-ONRR** [comment]
I added a notice with the shutdown warning to the page data model in the CMS. 

Adding Jeff to the issue - ends up he needs to query since it was adding a new field
