### ISSUE TITLE
EVENT CALENDAR                                                          (ADD to existing September Calendar

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2842]
Please see the attached file to be added to the existing 
[EVENT CAL_SEP ADDL 2023 DEN.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/12701470/EVENT.CAL_SEP.ADDL.2023.DEN.docx)
Event Calendar for September.

**Comment by Maroyafaied** [comment]
@Toddsand21 Please review https://dev-onrr-frontend.app.cloud.gov/events. Just FYI, everyone is off today on the team but I will check back later if you approved this to get it to the live site. Thanks!

**Comment by Toddsand21** [comment]
It looks good.  Thank you so much Maroya, and for getting this done on such short notice.
