### ISSUE TITLE
Federal Onshore Terminable leases

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2857]
Please replace the existing document with the attached excel on the following page - https://www.onrr.gov/references/reference-lists?tabs=revenue-reporting-references, on the Reference Lists card

Federal Onshore Terminable Leases - sorted by Due Date, please also change (9/5/2023) to read (updated 10/02/2023)

THANK YOU
[20231002.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12786394/20231002.xlsx)

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by bowlenj** [comment]
Perfect!  Approve for live and to close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, October 2, 2023 2:59 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Federal Onshore Terminable leases (Issue #2857)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references
