### ISSUE TITLE
Onshore Production ONRR.gov Contacts

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2858]
Please update the phone number for ONRR.gov contact for Onshore Production as highlighted in yellow on she shared contacts spreadsheet on the following page - https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Kerri Gallant's phone number should be 303-231-3154, I think it's on 3 cards.

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj 

This is ready for review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Thanks!

**Comment by bowlenj** [comment]
This looks great, thank you! Approve for live and to close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Monday, October 2, 2023 3:39 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Onshore Production ONRR.gov Contacts (Issue #2858)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj>

This is ready for review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Thanks!

**Comment by eelzi-ONRR** [comment]
@bowlenj This is now live. Have a great day! https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, October 3, 2023 1:50:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Onshore Production ONRR.gov Contacts (Issue #2858)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> This is now live. Have a great day! https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
