### ISSUE TITLE
Active Agreements Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2859]
Please replace the Active Agreements spreadsheet on this webpage - https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers, active-agreements, with the attached updated spreadsheet.

Please also change the updated date from 7/1/2023 to 10/2/2023.

THANK YOU
Jessica Bowlen
[saaname.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12792820/saaname.xlsx)

**Comment by AlexandracmONRR** [comment]
Hi @bowlenj  - thanks for your request! I've updated the active agreements spreadsheet with the one you attached.

Please review [this link](https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,active-agreements), and if you don't have any edits, I will post live.

**Comment by bowlenj** [comment]
Perfect, thank you!  Approved for live and to close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Alexandra C McNally ***@***.***>
Sent: Tuesday, October 3, 2023 8:16 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Active Agreements Update (Issue #2859)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj> - thanks for your request! I've updated the active agreements spreadsheet with the one you attached.

Please review this link<https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,active-agreements>, and if you don't have any edits, I will post live.

**Comment by AlexandracmONRR** [comment]
The update is now live.

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: Alexandra C McNally ***@***.***>
Sent: Tuesday, October 3, 2023 3:05:52 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Active Agreements Update (Issue #2859)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2859<https://github.com/DOI-ONRR/onrr.gov-site/issues/2859> as completed.
