### ISSUE TITLE
Geothermal Lease & Agreement Maintenance Contact Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2864]
Please update the Lease & Agreement Maintenance Geothermal contact located at this webpage - https://onrr.gov/about/contact/geothermal-contacts?tabs=contacts, as shown below.

Remove Sandra Allen and Maggie Gallegos as Primary Contact and replace with:

Christen Watkins - Primary Contact
christen.watkins@onrr.gov
303-231-3243

Kyle Kitchen - Supervisor
kyle.kitchen@onrr.gov
303-231-3558

Please let me know if you have any questions.

THANK YOU
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

Good morning,
This update is not in dev: https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=contacts.
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great, thank you for getting this done so quickly!  Approved for live and to close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 4, 2023 6:36 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Geothermal Lease & Agreement Maintenance Contact Update (Issue #2864)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

Good morning,
This update is not in dev: https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=contacts.
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 
Great! This is now live: https://www.onrr.gov/reporting/geothermal?tabs=contacts
Have a good day,
Christine

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 4, 2023 12:54:42 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Geothermal Lease & Agreement Maintenance Contact Update (Issue #2864)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>
Great! This is now live: https://www.onrr.gov/reporting/geothermal?tabs=contacts
Have a good day,
Christine
