### ISSUE TITLE
ONRR FY 23 analytics

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2865]
Pull FY23 analytics, and also update the analytics archive by moving FY22 monthly data there.

**Comment by lpgoldstein** [comment]
@cthomasONRR looks great! Do you think the overall jump in numbers from FY22 is due to bug crowd and VDP or are they real users? Because even if we completely remove 10/22 completely we are still way higher than previous years.

**Comment by cthomasONRR** [comment]
Yeah 10/22 jump was definitely VDP/BugCrowd. But after that, I believe we do see an increase of users because of the new website redesign and the attention it got. I think there's VDP/BugCrowd type checks happening monthly, but I don't think the increase is solely because of that.
