### ISSUE TITLE
Update Sep NYMEX price on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#2866]
Please update the NYMEX price according to the attachment.

Thanks!
- Sean
[NYMEX092023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12807923/NYMEX092023.xlsx)

@sudarr

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by boices** [comment]
Perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
