### ISSUE TITLE
New Page on ONRR.gov for Refund Request

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2868]
Hello,

I would like to have a page created for companies to know how to request a refund from ONRR, along with information that they need. It can be part of the "Payment" page. Links to contact and the handbook would be good to. I have attached the things that need to be stated on the page. I just don't know how to make it look nice. 
[Requesting a Refund with ONRR.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/12821137/Requesting.a.Refund.with.ONRR.docx)

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - here is the link to the drafted design of the [refunds page](https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds) (based on the word document). 

Aside from general review, there are a few things that I could use your input on:

- tab label
- I added 2 links within the body of the content (Debt Collection Improvement Act of 1996 and Royalty Simplification and Fairness Act of 1996 (RSFA)). does it make sense to include these links?
- I added a card for the "note"

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I like the simple tab label. The links make sense but Jessica can weigh in. Also think a card for the note helps separate the content. Just two tiny edits: bold $100 and delete 5b in the note since it's the same as 6. Looks great!
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/83109d2b-0080-4808-903d-9d08907e9b44)

**Comment by Sheetsj** [comment]
Also under notes number 2. There are two periods.

**Comment by AlexandracmONRR** [comment]
@Sheetsj - I've made the edits that you and Lindsay identified - thank you for sending them.

Please review the [updated refund tab on the dev site](https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds), and if there are no additional edits, send your approval for it to go live.

Thanks,
Alex

**Comment by Sheetsj** [comment]
It looks great! Now the companies can't say we didn't tell them what is needed and the rules. lol

**Comment by AlexandracmONRR** [comment]
@Sheetsj - the update is now live! Please see here: https://onrr.gov/paying/payment-options?tabs=refunds

**Comment by Sheetsj** [comment]
Thank you :)
