### ISSUE TITLE
October Indian Index Zone prices

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2871]
Hello! October Indian Index Zone prices for October are ready to be posted on ONRR.gov. A separate email with data will be sent. Can you please make sure that the prices ending in zero display the price to the thousandths place? Thanks!!
@sudarr

**Comment by eelzi-ONRR** [comment]
Hi @penvosej This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Hi, Erin,

The webpage with the new Indian Index Zone numbers looks good! Thanks for taking care of this!

- Jessica

From: Erin Elzi ***@***.***>
Sent: Thursday, October 5, 2023 3:55 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] October Indian Index Zone prices (Issue #2871)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @penvosej<https://github.com/penvosej> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by eelzi-ONRR** [comment]
@penvosej  Great! This is now live so I'll close out the issue: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
