### ISSUE TITLE
EVENT CALENDAR                                                   (To be added to existing calendar for events)

### ISSUE THREAD

**Issue by Toddsand21** [DOI-ONRR/onrr.gov-site#2878]
PLEASE ADDTHE FOLLOWING TO OUR EVENT CALENDAR.  PLEASE EMAIL OR CALL IF YOU HAVE QUESTIONS.
THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
[FY 24 EVENT CAL OCT  2023 FINAL.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/12861830/FY.24.EVENT.CAL.OCT.2023.FINAL.docx)

**Comment by eelzi-ONRR** [comment]
Hi @Toddsand21 These two events have ben added and are ready for review: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
Fargo Meeting is MST. The otherlooks fine and ready to post after that.

**Comment by Toddsand21** [comment]
thanks!

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Great - I made the change and pushed live since one of the events is tomorrow: https://onrr.gov/events

**Comment by Toddsand21** [comment]
I saw that it was up yesterday. I do appreciate the swift service you provided.
Thanks Erin!  I guess this is closed.
