### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – October 2023

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#2880]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “SOctober 2023 Lease Agreement XREF.txt" and "October 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 10/11/2023.
[October 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/12874459/October.2023.Lease.Agreement.XREF.txt)
[October 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/12874468/October.2023.Lease.Agreement.XREF.xlsx)

**Comment by AlexandracmONRR** [comment]
@StaceyKaiser - thanks for sending this update. 

Could you please review both links on the [dev site](https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers), to ensure that they are correct? If you do not have any edits, I will publish live tonight.

**Comment by StaceyKaiser** [comment]
Good morning. Both files look good, we have no edits.  Thanks!
