### ISSUE TITLE
Demo to Jeff all CMS issues with editor 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2881]
I'd like to go through all the open issues related to the CMS editor and demo to Jeff the difficulty of using it so we can prioritize how to enhance certain features.

**Comment by eelzi-ONRR** [comment]
Starting a list of things to demo:  

- Sometimes pasted in text is gray or a different font, with no option to change to black text or the standard font
- Can't nest anything with a list (including indented bullets/lists)
- Can't adjust list numbers (or use letters, etc.)
- Can't add line breaks (have to use a paragraph break)

**Comment by cthomasONRR** [comment]
The [CMS Announcements collection](https://dev-onrr-cms.app.cloud.gov/admin/content/announcements) has a well-functioning text editor. It doesn't have everything we need in it (like a table builder) but this would be a good place to start. It would be great if we could apply what's existing in the Announcements collection to all text boxes (within content/tab/card/expansion blocks).

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/1a81c4cd-0fe2-482c-8355-3ef9ec743e95)

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/cbdbd4dc-1b59-4d7b-b601-c7d0e24ee007)
