### ISSUE TITLE
Draft email to GS15s requesting webpage SMEs

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2885]

**Comment by cthomasONRR** [comment]
@Maroyafaied What do you think?

Subject: Update needed: onrr.gov webpage SMEs for your program

Hello,

It’s been over a year since we last needed SME review on the newly redesigned onrr.gov webpages. Thank you again for all your help!

Since it has been a while and there has been staffing updates, **I would like you to designate who in your program should be the SME contact(s) for your webpages.** 

We are about to commence our first content audit of the new website. For this audit, we will ask your SME(s) to verify that the information on your webpages is correct and up to date. We are happy to cc you on these emails as well.

We will also be making minor updates to all webpages for Section 508 compliance. We plan to get SME input on whether they prefer PDF documents to open in a new tab or within the same window. 

Please let me know by [DATE] who you would like to be your SME(s) for your designated webpages.

Thanks for your time and cooperation!

**Comment by cthomasONRR** [comment]
@Maroyafaied I started an excel with the ONRR Program , Leader, and previous SMEs (the ones I could find). Maybe we could send this with the email to remind the 15s who reviewed the website?

[ONRR SME List](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/FY24/onrr.gov%20SME%20list.xlsx?d=w7dfd588567a6437e8cb37b2a43c97ecf&csf=1&web=1&e=uBzFHB)

**Comment by Maroyafaied** [comment]
@cthomasONRR the email draft looks good, do you think we should attach the SME list excel sheet in the email so the program managers can see who was assigned previously? I still need to review that excel sheet, I'll try to get it done today.

**Comment by cthomasONRR** [comment]
@Maroyafaied Yeah, my hope is we can complete the SME list excel sheet and attach it to the email. That way we aren't asking them to start from scratch. They can consider who helped last time, if those people are even still in their program due to the reorgs, and decide from there. I've added all the people I could find in my emails but there are some programs that I need help with.

**Comment by Maroyafaied** [comment]
@cthomasONRR sounds good, then we'll have to edit the email to mention the excel sheet, otherwise it looks good.

**Comment by Maroyafaied** [comment]
@cthomasONRR sorry for the multiple comments, I forgot to mention that I added as much detail as I can find in my emails in the excel sheet and added a column for the webpages SEMs reviewed. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied Here is an updated email including a mention of the attachment:

Subject: Update needed: onrr.gov webpage SMEs for your program

Hello,

It’s been over a year since we last needed SME review on the newly redesigned onrr.gov webpages. Thank you again for all your help!

Since it has been a while and there has been staffing updates, **I would like you to designate who in your program should be the SME contact(s) for your webpages.** 

Attached is a spreadsheet of pervious SMEs and which webpages they reviewed to help you make your decisions.

We are about to commence our first content audit of the new website. For this audit, we will ask your SME(s) to verify that the information on your webpages is correct and up to date. We are happy to cc you on these emails as well.

We will also be making minor updates to all webpages for Section 508 compliance. We plan to get SME input on whether they prefer PDF documents to open in a new tab or within the same window. 
Please let me know by [DATE] who you would like to be your SME(s) for your designated webpages.

Thanks for your time and cooperation!

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good, feel free to close this issue and we can create another one for next sprint to send out the email and update the SMEs as we get responses.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks. I changed this work to a 2 since we ended up making the excel SME list.
