### ISSUE TITLE
Implement external link indicator function in CMS

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2886]
Based on research done in issue #2564, we need a way to indicate external links on onrr.gov within the CMS.
This should probably be done in conjunction with the other inline link editor issue (#2495).

**Comment by greensomes** [comment]
The hyperlink plugin for the editor has been updated to add the `usa-link--external` class to external links. Also, a conversion script has been run in preview to add the class to existing external links found in card blocks and content blocks.
