### ISSUE TITLE
Email program leads to identify webpage SMEs

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2889]
Email and excel in issue #2885

**Comment by cthomasONRR** [comment]
@Maroyafaied Do you want to send out this email? I think we're good with the SME list, but we might want to send it to someone other than Howard for Deputy Director group?

**Comment by Maroyafaied** [comment]
@cthomasONRR I don't have a preference who sends it out, feel free to send it or if you'd like me to do it then I will later this afternoon or tomorrow. For Howard, we skip emailing this group since we know all the SMEs are still with ONRR.

**Comment by cthomasONRR** [comment]
@Maroyafaied OK, I'll send the email and CC you

**Comment by cthomasONRR** [comment]
Email sent with program manager response deadline of Friday, November 17.
