### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – November 2023

### ISSUE THREAD

**Issue by Daphnesmum** [DOI-ONRR/onrr.gov-site#2892]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “November 2023 Lease Agreement XREF.txt" and "November 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 11/2/2023.

THANK YOU
___________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

[November 2023 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/13239404/November.2023.Lease.Agreement.XREF.txt)

[November 2023 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13239436/November.2023.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@Daphnesmum 

Good morning,

These updates are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@Daphnesmum 
Great! These changes are now live: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Have a great weekend,
Christine
