### ISSUE TITLE
Fix left navigation menu for Government Initiatives page

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2894]
https://onrr.gov/government-initiatives-laws?tabs=plain-language

Left navigation menu says "null Home".

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/122935097/92bef65d-2d29-497f-a736-6756e61f838f)

**Comment by greensomes** [comment]
@AlexandracmONRR, This page does not have an associated left nav.  I see a few options here. We could not render anything for the left nav or we can render "Government Initiatives and Laws Home". This text would be a link to the current page, which provides no additional value. What would you like me to do? Thanks!

**Comment by AlexandracmONRR** [comment]
@greensomes - I think we should just not render anything. 

If we choose to not render anything, will it still maintain the margins where they are, or will everything shift to the left (in place of the left nav panel)?
