### ISSUE TITLE
October 2023 NYMEX

### ISSUE THREAD

**Issue by damionschulte** [DOI-ONRR/onrr.gov-site#2896]
All, I've attached the October 2023 NYMEX prices. Can you please have them posted to the website?  Please let me know if I and missing anything or you need something different.  I haven't done this request in a while :) Thanks 
[NYMEX102023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13270484/NYMEX102023.xlsx)

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by damionschulte** [comment]
This looks great! Thank you

From: lpgoldstein ***@***.***>
Sent: Monday, November 6, 2023 10:56 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] October 2023 NYMEX (Issue #2896)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

-

**Comment by lpgoldstein** [comment]
@damionschulte live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
