### ISSUE TITLE
Indian Index Zone prices - November - ONRR.gov website

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#2898]
The November Indian Index Zone gas prices are ready to be published on the ONRR.gov website. The spreadsheet is attached.
[Indian_Index_Zone_2023_11.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13271912/Indian_Index_Zone_2023_11.xlsx)

Thanks
Cory
@Sudarr

**Comment by eelzi-ONRR** [comment]
Hi @forgravec. This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by forgravec** [comment]
The prices look correct.

Thanks,
Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Erin Elzi ***@***.***>
Sent: Monday, November 6, 2023 1:20 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Indian Index Zone prices - November - ONRR.gov website (Issue #2898)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @forgravec<https://github.com/forgravec>. This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by eelzi-ONRR** [comment]
@forgravec Great! This is now live: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
