### ISSUE TITLE
Update DISC Contacts on ONRR.gov

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2900]
Please update our contacts on the pages listed below as shown on our shared spreadsheet.  All updates are highlighted in yellow, highlighted cells that are blank indicate contacts that are being removed.

https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/royalty-contacts?tabs=contacts

Please let me know if you have any questions.

Thank You
Jessica Bowlen

**Comment by lpgoldstein** [comment]
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
@bowlenj ready for your review.

**Comment by bowlenj** [comment]
These look great, thank you!  Approved for live and to close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, November 8, 2023 6:36 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update DISC Contacts on ONRR.gov (Issue #2900)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
@bowlenj<https://github.com/bowlenj> ready for your review.

**Comment by lpgoldstein** [comment]
@bowlenj This is live! 
https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/royalty-contacts?tabs=contacts
