### ISSUE TITLE
DISC Contact Header Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2901]
Please update the header  for the contact data to show the alpha in front, this way the companies listed individually will be listed alphabetically when they're not grouped into the alpha "H".

Below are the pages in onrr.gov that need the update, please see the shared spreadsheet, the updated headers are highlighted:

https://onrr.gov/about/contact/royalty-contacts?tabs=contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Please let me know if you have any questions!

Thank You
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj This is ready for review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

**Comment by bowlenj** [comment]
This looks great!  Thank you so much!!!

Approved to push live and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Thursday, November 9, 2023 2:24 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Header Update (Issue #2901)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj> This is ready for review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

**Comment by eelzi-ONRR** [comment]
@bowlenj Great! This is now live: https://onrr.gov/about/contact/royalty-contacts?tabs=contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
