### ISSUE TITLE
DISC Contact Title Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2902]
Please update the contact cards on the below page in onrr.gov to read Backup instead of Back up, the shared spreadsheet has the changes highlighted.

https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

Please let me know if you have any questions!

Thank You
Jessica Bowlen

**Comment by Maroyafaied** [comment]
@bowlenj Please review the title update, also all the contacts should be updated now as they were. Apologies for the site showing outdated contacts this afternoon. https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by bowlenj** [comment]
Good Morning,

The title update to Backup from Back Up looks great!

I did notice a few things listed below:

  *   Lease & Agreement page - Lease & Agreement Contacts | Office of Natural Resources Revenue (onrr.gov)<https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts>, the card title has been updated but for the supervisors that are listed as backup still show as Back up, can these be corrected to backup?
  *   Onshore Production page - Oil & Gas Production Contacts | Office of Natural Resources Revenue (onrr.gov)<https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production>, the title for "A" is missing the A after Companies that begin with.  Can the A be added to the title after with?
  *   Royalty Page - Oil & Gas Royalty Contacts | Office of Natural Resources Revenue (onrr.gov)<https://onrr.gov/about/contact/royalty-contacts?tabs=contacts>, the titles still show Companies starting with A, instead of A: Companies that begin with A.  Can this pages titles be updated like Onshore Production?


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, November 13, 2023 5:11 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Title Update (Issue #2902)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> Please review the title update, also all the contacts should be updated now as they were. Apologies for the site showing outdated contacts this afternoon. https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by bowlenj** [comment]
This looks great!  Approved to close.  THANK YOU!!!
