### ISSUE TITLE
Plan onrr.gov SME outreach for webpage review

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2905]

**Comment by cthomasONRR** [comment]
@Maroyafaied Here's a link to the prototype [DISC approval sheet](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/FY24/FY24%20Content%20Audit/SME%20Approvals/DISC_FY24_ONRR_Approval.xlsx?d=w04852b258741435781ada4659ca86b2d&csf=1&web=1&e=v3pgT7).

Please let me know if you have questions/comments/modifications. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR This looks great, I left one comment in column G. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied I have all the SME approval spreadsheets [here](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/FY24/FY24%20Content%20Audit/SME%20Approvals?csf=1&web=1&e=zzDi0F).

Here's a draft of the email I'll send with it:

Subject: onrr.gov webpage review - due [DATE]

Hello,

If you are on this email, your program's leadership identified you as a SME for your program's onrr.gov webpages.

It’s been over a year since we launched the newly redesigned onrr.gov, and we are asking SMEs to do an annual review.
 
For this review, please verify that the information on your webpages is correct and up to date.
 
Attached is a spreadsheet that lists the webpages your program is responsible for. This spreadsheet includes space for you to either approve the pages as-is, or detail updates that you would like to make. 

Also within the spreadsheet is an accessibility question- we would like to get your input on whether you prefer PDF documents to open in a new tab or within the same window.

Please feel free to contact me with any questions. If your SME group would like to have a meeting, we will be happy to organize that as well.
 
Please provide your review by [DATE].
 
Thanks for your time and cooperation!

**Comment by cthomasONRR** [comment]
I'm waiting to email SMEs til next week, lots of people are out of office this week.

- This sprint - DISC, Deputy Director, and Financial Services.
- Then - Audit, Compliance, & Indian Outreach
- Then - Enforcement, RV, Appeals/Regs, and MSA

**Comment by cthomasONRR** [comment]
I emailed DISC, Deputy Director, and Financial Services with a review deadline of December 8.
