### ISSUE TITLE
Review sitemap 6.0 - 9.0

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2908]

**Comment by AlexandracmONRR** [comment]
Hi Christine, please see the site map for review of 6.0 - end:
https://71ccqt.axshare.com/?id=jl5r59&p=primary_nav&g=1

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I'm done reviewing. Please let me know if you have any questions. Thanks!
