### ISSUE TITLE
Update DISC Contact on ONRR.gov

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2910]
Please update the below pages on ONRR.gov using the shared spreadsheet.  The updates are on the Onshore Production tab and Offshore Production tab only and they're highlighted:

https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Thank You
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj This is ready for review: 

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

**Comment by bowlenj** [comment]
This looks great!  Approved to publish and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Monday, November 20, 2023 12:37 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update DISC Contact on ONRR.gov (Issue #2910)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj> This is ready for review:

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

**Comment by eelzi-ONRR** [comment]
@bowlenj This is now live: 

https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Have a great day!
