### ISSUE TITLE
Add Deputy Director tab and update org chart

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2911]
- Reach out to April for pic & bio

**Comment by Maroyafaied** [comment]
Sent April an email and cc'd @cthomasONRR

**Comment by Maroyafaied** [comment]
@cthomasONRR April emailed the bio and pic. Please send her the link to dev after you create the deputy director tab.  Please also update the organizational chart tab. Thanks!

**Comment by cthomasONRR** [comment]
Sent via email to April for review.

The Org Chart image and powerpoint are also updated.

**Comment by cthomasONRR** [comment]
@Maroyafaied Should we hold off publishing until December 3rd? The org chart is already live because image and doc updates go live immediately...

**Comment by Maroyafaied** [comment]
@cthomasONRR sure, let's hold off. I don't think the org chart is a big deal or do you think we revert it?

**Comment by cthomasONRR** [comment]
@Maroyafaied I'd say leave org chart as-is.

**Comment by cthomasONRR** [comment]
Closing this issue. I have #2913 open to publish the DD tab on Dec. 3.
