### ISSUE TITLE
Add zenhub label info to wiki and more details about when to use each label in the label description

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2914]

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Here's the list of wiki pages I think would benefit from having information about issues labels added: https://doimspp-my.sharepoint.com/:x:/r/personal/elzie_mms_gov/Documents/Book%203.xlsx?d=w0b79fc0f1aa946d7be3370e8a0a60119&csf=1&web=1&e=SWVPVl

Line 25 has a specific question for you

**Comment by lpgoldstein** [comment]
@eelzi-ONRR this all makes sense to me. I also added in a note on line 25. Thanks for working on this.

**Comment by eelzi-ONRR** [comment]
Updated 18 wiki pages and 4 labels
