### ISSUE TITLE
Updates to ONRR.gov's Federal Register Notice Pages 

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#2917]
Good afternoon, 

I am requesting updates to his page https://onrr.gov/references/frns

Under State Accounting and Auditing Relief please update the hyperlink to the "Most recent annual publication" with the hyperlink below 

https://www.federalregister.gov/documents/2023/11/22/2023-25795/states-decisions-on-participating-in-accounting-and-auditing-relief-for-federal-oil-and-gas-marginal

Please let me know if you have any questions. 

Thank you!

**Comment by eelzi-ONRR** [comment]
Hi @gingerhensley, This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/frns

**Comment by gingerhensley** [comment]
Great! Thanks, approved.

**Comment by eelzi-ONRR** [comment]
@gingerhensley This is now live: https://onrr.gov/references/frns

Have a good night!
