### ISSUE TITLE
Add a Link to Production Reference Page and Revenue Reporting page

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2919]
We would like to add a link titled, "View Sample OGOR Layouts", to to the Oil & Gas Production page on the References tab and a link titled, "View Sample 2014 Layouts", to the Oil & Gas Revenue Reporting page on the References tab to the cards "How to Use Reporting Systems".  We would the links to take the user to the forms tab on the subject page where the sample layouts are listed.

Please see attached document for screenshots, below are the pages we're requesting the update be made on:

Oil & Gas Production, References tab - https://onrr.gov/reporting/production?tabs=references
Oil & Gas Revenue, References tab - https://onrr.gov/reporting/revenue?tabs=references

[Production_Revenue Page Updates_11-30-23.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/13513402/Production_Revenue.Page.Updates_11-30-23.docx)

**Comment by lpgoldstein** [comment]
https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references @bowlenj ready for your review

**Comment by lpgoldstein** [comment]
@bowlenj both are live!

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, November 30, 2023 4:28:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add a Link to Production Reference Page and Revenue Reporting page (Issue #2919)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2919<https://github.com/DOI-ONRR/onrr.gov-site/issues/2919> as completed.

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, November 30, 2023 4:28:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add a Link to Production Reference Page and Revenue Reporting page (Issue #2919)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> both are live!
