### ISSUE TITLE
Valuation Resources - Indian

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#2923]
As we discussed in October (sorry for the delay...), RV would like to add a tab to "Valuation and Pricing" (https://onrr.gov/references/valuation) for "Valuation Resources."  Inside it, we'd like to split into Federal and Indian like we did for the examples.  I will attach the document we discussed here as well.  I have also included the document in its almost complete (being read by 2 more people for grammar misses, hypens in the right spot, etc.) form so you can see what we intend to publish.  As I understand it, it may have to go up to the solicitor, but that has yet to be confirmed.  Please let me know if we need to meet to talk through anything!  We in RV appreciate your help and expertise so much!!

[Layout for Valuation Resources.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/13516939/Layout.for.Valuation.Resources.docx)
[Valuation Resources for Indian Leases.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/13517185/Valuation.Resources.for.Indian.Leases.docx)

If your request is to add new content, PLEASE [read through this example on our wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-add-new-content)

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:

**Comment by AlexandracmONRR** [comment]
Should update the link as "Indian Valuation resources" under Indian Pricing.

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/122935097/89c961da-4c5c-4716-bfa5-7abd94c35d9c)

**Comment by cthomasONRR** [comment]
Completed in Issue #3177
