### ISSUE TITLE
Final review of ONRR.gov site map

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2927]

**Comment by AlexandracmONRR** [comment]
The older version of the sitemap that has Christine's comments: https://71ccqt.axshare.com/

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I'm only able to see two of Christine's comments using the link above.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I checked several pages within sections 6 to 9.0 and left a few comments. Great job overall, it's a big task and lots of details!!

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I reviewed sections 1-4 and left comments within Axure. Kudos on this huge undertaking! Thank you for working on this.
