### ISSUE TITLE
November 2023 Nymex Prices

### ISSUE THREAD

**Issue by damionschulte** [DOI-ONRR/onrr.gov-site#2931]
All, Attached is the Nymex Prices for November 2023. Can you please publish them to the website? Please let me know if you need anything else from me.  Thanks 

Damion 
[NYMEX112023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13572928/NYMEX112023.xlsx)

@sudarr

**Comment by damionschulte** [comment]
These look great! Thank you so much.

From: lpgoldstein ***@***.***>
Sent: Tuesday, December 5, 2023 2:15 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] November 2023 Nymex Prices (Issue #2931)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

-

**Comment by lpgoldstein** [comment]
@damionschulte live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
