### ISSUE TITLE
ONRR.gov Indian Index Zone Prices - December

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#2932]
The December Indian Gas Index Zone prices for December are ready to be posted on ONRR.gov.  The prices are attached.

Thanks
Cory Forgrave
@Sudarr
[Indian_Index_Zone_2023_12.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13573487/Indian_Index_Zone_2023_12.xlsx)

**Comment by eelzi-ONRR** [comment]
Hi @forgravec - this is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by forgravec** [comment]
The prices look good.

Thanks,
Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, December 5, 2023 3:29 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] ONRR.gov Indian Index Zone Prices - December (Issue #2932)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @forgravec<https://github.com/forgravec> - this is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by eelzi-ONRR** [comment]
@forgravec Great! It's now live: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
