### ISSUE TITLE
Update troubleshooting card link titles

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2944]
In the following troubleshooting cards, there are 2 links with the same name, "MLRS" that go to different places. However, there are "MLRS" and "Serial Register Page" that lead to the same url.

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/122935097/28cbdd28-95c9-416c-9aea-ad701a49465b)

Request review/feedback from Cody.

**Comment by AlexandracmONRR** [comment]
_Proposed rewrite:_

Check the references in the list below or find the lease or agreement and additional information in the [MLRS](https://mlrs.blm.gov/s/).
Note: LR2000 is no longer updated by BLM; this information is available on the [MLRS Reports Page](https://reports.blm.gov/reports/MLRS/).

<img width="319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenQwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--073becd76d74709fee42b8435d87168816e8d9cd/image.png" alt="image.png" />


See [Lease & Agreement Contacts](https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts) if this doesn't answer your question.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - could you review the changes in language, consolidation of links, and correctness of links for this proposed re-write of this trouble shooting card?

After your changes/edits, I'll ask for Cody's input.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

This looks good- I'd relabel the "MLRS Reports Page" to "Serial Register Page". 

Everywhere else on the site, we label that link (https://reports.blm.gov/reports/MLRS/) the Serial Register Page, and the other link (https://mlrs.blm.gov/s/) MLRS. So I'm trying to be consistent. There are some locations where MLRS/SRP are switched but I have those locations marked in the audit to fix.

If Cody wants to relabel those links something else, that's fine. I'll just need to fix all 30 (thus far) instances of them.

**Comment by AlexandracmONRR** [comment]
_Updated proposed rewrite:_

Check the references in the list below or find the lease or agreement number and additional information in the [MLRS](https://mlrs.blm.gov/s/).
Note: LR2000 is no longer updated by BLM; this information is available on the [Serial Register Page](https://reports.blm.gov/reports/MLRS/).

<img width="319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenQwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--073becd76d74709fee42b8435d87168816e8d9cd/image.png" alt="image.png" />


See [Lease & Agreement Contacts](https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts) if this doesn't answer your question.

**Comment by AlexandracmONRR** [comment]
Updates approved via email and now live: https://onrr.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-help-finding-a-lease-or-agreement-number
