### ISSUE TITLE
Develop prototype for Valuation Resources - Indian

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#2947]
Related to #2923: https://app.zenhub.com/workspaces/open-data-design--development-5464fa79c3cc8d7f4c384eaf/issues/gh/doi-onrr/onrr.gov-site/2923

**Comment by eelzi-ONRR** [comment]
Based on our meeting with Jodie on 3/14, this is not an immediate priority. We will take the document she made on the new tab/content organization, turn that into a chart that displays the information architecture (similar to our Axure sitemaps). Once that is approved by her we'll work on some design options

**Comment by eelzi-ONRR** [comment]
Jodie's document is linked to issue #2923
