### ISSUE TITLE
Update DISC Contacts

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2949]
Please update the DISC contacts using the shared Contacts Spreadsheet for the pages listed below:

Onshore Production - please update the changes highlighted in yellow on the spreadsheet.  https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Offshore Production - please update all the contacts for this page, 3 new companies were added and several of the contacts changed for company assignments.  https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

Please let me know if you have any questions.

Thank you,
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj, this is ready for review
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

**Comment by bowlenj** [comment]
This looks great!  Approved to push live and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Wednesday, December 13, 2023 3:17 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update DISC Contacts (Issue #2949)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj>, this is ready for review
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

**Comment by eelzi-ONRR** [comment]
@bowlenj Great! These are now live: 
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G reacted to your message:
________________________________
From: Erin Elzi ***@***.***>
Sent: Wednesday, December 13, 2023 10:39:38 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update DISC Contacts (Issue #2949)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> Great! These are now live:
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
