### ISSUE TITLE
Update ODDD onrresource page to include more details about submitting an onrr.gov issue

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2957]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied and @lpgoldstein do you want to review before I make the change in onrresource? Here's the updated content for the page: 

https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EUFmt8aMQhFDn2RD-GHdN8UBgPZWn-ygZKa8XCK2U7ZM2g?e=CUlJUY

I still kept pretty simple, linking to the wiki and what we have in Github as much as possible so we don't have to make updates in multiples places if we make changes.

Here's the current ODDD onrresource page if you want to compare: https://onrresource/ODDD

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I reviewed and made minor edits, looks good!
