### ISSUE TITLE
Update  contact in payment option renewable energy tabs

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2959]
@AlexandracmONRR This request came in through the mailbox, please send the dev link for review by replying to the email in onrrweb mailbox. Thanks

Michelle VanVleet is leaving ONRR at the end of December. Please remove Michelle VanVleet from all the Renewable Energy tabs and add Tanvir Mojumder 303-231-3668.

<img width="1054" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHA2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b29d0a3867041a93611df6022d981f0ca61dc301/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
Change approved by email. [Update](https://www.onrr.gov/paying/payment-options?tabs=renewable-energy,bid-deposit-options) is now live.
