### ISSUE TITLE
100% Fed Agmt

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#2969]
Please replace the existing spreadsheet for 100% Federal Agreements with the same Royalty Rate & Royalty Distributions located here - https://onrr.gov/reporting/revenue?tabs=references, on the Reference Lists card, with the attached spreadsheet.

Please also change Updated 10/02/2023 to Updated 01/02/2024

[fedagmts.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13813141/fedagmts.xlsx)

Thank You
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj , this is ready to review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by bowlenj** [comment]
This looks great, thank you!  Approved to push live and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, January 2, 2024 1:14 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] 100% Fed Agmt (Issue #2969)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj> , this is ready to review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by eelzi-ONRR** [comment]
Great! This is now live: https://onrr.gov/reporting/revenue?tabs=references
