### ISSUE TITLE
Update interest rates

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2970]
Hello, 

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas please make the following updates: 
Add a new line at the top of the late payments & underpayments table for Period 1/1/2024-3/31/2023. Oil and gas remained the same at 8%.

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal please make the following updates: 
Add a new line at the top of the late payment & underpayment table for period 1/1/2024-3/31/2023. Solid's increased to 4%. 

Replace the Interest Calculator excel file at https://onrr.gov/paying/interest?tabs=interest-calculator with the attached below: 

[Interest_Calculator_Master_v2.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13822251/Interest_Calculator_Master_v2.xlsx)

Thanks so much!

**Comment by Sheetsj** [comment]
Sorry the Period should read 1/1/2024 - 3/30/2024.

**Comment by lpgoldstein** [comment]
@sheetsj ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal

**Comment by Sheetsj** [comment]
It looks good. I just couldn't download the excel file to check that it was the right one, but I am sure you have it just fine. Good to go live.

**Comment by lpgoldstein** [comment]
@sheetsj This is live!

**Comment by Sheetsj** [comment]
[heart]         Sheets, Jessica E reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, January 3, 2024 9:48:13 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Sheets, Jessica E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update interest rates (Issue #2970)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2970<https://github.com/DOI-ONRR/onrr.gov-site/issues/2970> as completed.

**Comment by Sheetsj** [comment]
Hey it was brought to my attention that when the site was updated for the rates that one of the time periods were taken away, 10/1/2023-12/31/2023 is not there. It should be there with the 8% as well just like the other lines. It is just missing on the Oil & Gas one. It should not have been removed.  https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas

**Comment by lpgoldstein** [comment]
@Sheetsj Fixing now.

**Comment by lpgoldstein** [comment]
@Sheetsj ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,oil-gas

**Comment by Sheetsj** [comment]
Looks perfect! Thank you so fixing that so fast.

**Comment by Sheetsj** [comment]
Oh wait, some other lines have become missing now


Jessica Sheets
Staff Accountant, Financial Services
Team Lead, Special Invoice Team
Revenue, Reporting, & Compliance Management

Office of Natural Resources Revenue<https://www.onrr.gov/>

1-800-433-9801 ext 3401

303-231-3401

***@***.***>


________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, January 4, 2024 12:34 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Sheets, Jessica E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update interest rates (Issue #2970)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Sheetsj<https://github.com/Sheetsj> ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,oil-gas

**Comment by Sheetsj** [comment]
Never mind, I am just losing it. It is fine

Jessica Sheets
Staff Accountant, Financial Services
Team Lead, Special Invoice Team
Revenue, Reporting, & Compliance Management

Office of Natural Resources Revenue<https://www.onrr.gov/>

1-800-433-9801 ext 3401

303-231-3401

***@***.***>


________________________________

**Comment by lpgoldstein** [comment]
@Sheetsj It looks good again - https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas

**Comment by Sheetsj** [comment]
Yep looks good!
