### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov - January 2024

### ISSUE THREAD

**Issue by hasketta** [DOI-ONRR/onrr.gov-site#2972]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “January 2024 Lease Agreement XREF.txt" and "January 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 01/04/2024.
[Uploading January 2024 Lease Agreement XREF.txt…]()
[Uploading January 2024 Lease Agreement XREF.xlsx…]()

**Comment by AlexandracmONRR** [comment]
Hi Andrew, thanks for your submission. Please take a look at [the update on our dev site](https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers). If it looks good, send your approval and I will post live.

**Comment by hasketta** [comment]
Peer Review has been completed.  The files can be moved to the live site.  Thank you!

**Comment by lpgoldstein** [comment]
@hasketta This is live! https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
