### ISSUE TITLE
January Indian Index Zone Prices

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#2974]
Hello and happy new year! The Indian Index Zone prices for January 2024 are ready to be posted on ONRR.gov. A separate email with data will be sent. Can you please make sure that the prices ending in zero display the price to the hundredths place? Thanks!!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej Happy new year! Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Everything looks great! Thanks for taking care of that!

From: lpgoldstein ***@***.***>
Sent: Thursday, January 4, 2024 1:26 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] January Indian Index Zone Prices (Issue #2974)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> Happy new year! Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by lpgoldstein** [comment]
@penvosej This is live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
