### ISSUE TITLE
Dec 2023 NYMEX Prices

### ISSUE THREAD

**Issue by WW-Git-Hub** [DOI-ONRR/onrr.gov-site#2975]
Please update the NYMEX prices.

December 2023	 
 NYMEX CMA Price	$72.12 
 NYMEX Roll	         $0.41 
 NYMEX + Roll          $72.53

[NYMEX122023.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/13835845/NYMEX122023.xlsx)

@sudarr

Thank you.

**Comment by lpgoldstein** [comment]
@WW-Git-Hub ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by WW-Git-Hub** [comment]
Hi you two!!!!

Everything looks good.

Thanks

@sudarr

**Comment by lpgoldstein** [comment]
@WW-Git-Hub Happy New Year! And it's live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
