### ISSUE TITLE
Update Refund page

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#2982]
Hello,

I need to make changes to the refund page on ONRR.gov: https://onrr.gov/paying/payment-options?tabs=refunds

Please remove: 

The following information is needed when submitting your refund request.
The name and payor code associated with the refund.
The item number and the amount of each item.
An explanation of:
  a.  How the overpayment occurred or what the payment(s) were for.
  b.  What the adjustment reporting pertains to (Negative Form-2014).

Please add: 

The following form is needed when submitting your refund request. 
(Include form with this. I have attached it to this message)

[ONRR Refund Request Form.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/13967073/ONRR.Refund.Request.Form.pdf)

Thank you!

**Comment by cthomasONRR** [comment]
@Sheetsj 

Hello,
We are happy to make the update, but the PDF attached does not pass the Adobe accessibility checker. Please send us an accessible version of the PDF and then we can proceed with this update.

Thanks,
Christine

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/409d05a0-89aa-4c3a-8066-5f3e001dc4e2)

**Comment by Sheetsj** [comment]
Okay, I will work on that and let you know when I fixed it.

**Comment by Sheetsj** [comment]
I am having issues with the PDF. It is showing failed but not giving me the "Fix" choose, it is only giving me the "Skip Rule" choose. I don't know what to do to fix this or what the issue is.

**Comment by Sheetsj** [comment]
[ONRR Refund Request Form v2.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/13969120/ONRR.Refund.Request.Form.v2.pdf)


Okay, I was able to fix all the errors. I hope this passes now

**Comment by cthomasONRR** [comment]
@Sheetsj 

Thank you! 
This update is in now in dev: https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds
Please review and give us your approval to go live.

Thanks!
Christine

**Comment by Sheetsj** [comment]
Everything looks good. Thanks for all your help!

**Comment by Sheetsj** [comment]
Please use this form, that I am attaching. I found that one of the fields were duplicating information. The names were the same and I needed to change it to something different so that they won't do that error. I ran it through 508 and I don't see any errors on it. Let me know if you have any questions. 
[ONRR Refund Request Form.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/13976789/ONRR.Refund.Request.Form.pdf)

**Comment by cthomasONRR** [comment]
@Sheetsj Thanks for the update! This new doc is on dev for your review: https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds

**Comment by Sheetsj** [comment]
OKay, now everything looks good. It can go live. Thanks!

**Comment by cthomasONRR** [comment]
@Sheetsj Great! This update is now live: https://www.onrr.gov/paying/payment-options?tabs=refunds

Thanks for all your help and patience!
