### ISSUE TITLE
ONRR.gov webpage update

### ISSUE THREAD

**Issue by Tiffany-Mamayev** [DOI-ONRR/onrr.gov-site#2986]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

Hello,

On the **Solid Minerals** webpage (https://onrr.gov/reporting/solids?tabs=contacts), please update the **Debt Collection, Primary Contact.** 
Please remove Jessica Polacek's information and replace it with Yoona Conrad, 303-231-3681.

Second request:
On the **PayingHome** webpage (https://onrr.gov/paying/contacts-paying?tabs=contacts,debt-collection), please update the **Debt Collection, Solids: MA469-991 (Page 2), Primary Contact.**

Please remove Jessica Polacek's information and replace it with Yoona Conrad, Yoona.Conrad@onrr.gov, 303-231-3681.

Thank you for your help!

Best,
Tiffany

**Comment by lpgoldstein** [comment]
@Tiffany-Mamayev 

Ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying?tabs=contacts,debt-collection
https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=contacts

**Comment by Tiffany-Mamayev** [comment]
@lpgoldstein 

Excellent, I see the updated contact information, it is correct, thank you!

**Comment by lpgoldstein** [comment]
@Tiffany-Mamayev https://onrr.gov/reporting/solids?tabs=contacts
https://onrr.gov/paying/contacts-paying?tabs=contacts,debt-collection

This is live!

**Comment by Tiffany-Mamayev** [comment]
@lpgoldstein 
Thank you so much for your speedy help in updating our contact information in both places! :)
