### ISSUE TITLE
Update to statutes webpage

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2989]
This request came in from the mailbox, please request review by replying to Jim's email.

Hi. When you can, please edit this page.

https://onrr.gov/references/statutes

The entry for the 1996 Amendments to FOGRMA is more commonly known as the Federal Oil and Gas Royalty Simplification and Fairness Act of 1996 or RSFA (pronounced “riss-fah”)

Please change the second law name link to “Amendments to the FOGRMA by the Federal Oil and Gas Royalty Simplification and Fairness Act in 1996 (PL 104-185)” add the acronym “RSFA” to it and the landing page to help website users find this information.

Also, change the description to read, “ Revising FOGRMA in 1996 to improve the management of royalties from Federal onshore and offshore oil and gas leases, and to reduce disputes and litigation over royalty payments”
 

FYI: I tried searching for the RSFA acronym on onrr.gov and the Search page was busted also. Can you fix that, too, please?

 

Thanks

**Comment by Maroyafaied** [comment]
@cthomasONRR will make the update if SME's are fine with it. I will contact the user about the search issue

**Comment by cthomasONRR** [comment]
I emailed the SME dev site links to approve, and am waiting their response.

**Comment by cthomasONRR** [comment]
SME approved changes and they are live. 
Their comment about the search is in issue #2992 

Closing issue.
