### ISSUE TITLE
Production Reporting References, Offshore

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2990]
The request came from the mailbox, please find the attachments in Maria's email. 

Greetings,   

On the ONRR.gov home page, please update the Production Reporting References with the attached files, https://onrr.gov/references/reference-lists?tabs=production-reporting-references . The new as of date is 01/24/2024.

There are nine files attach as follow:

Five Gulf
Three Pacific
One Alaska

**Comment by lpgoldstein** [comment]
Reviewed and approved via email.
