### ISSUE TITLE
ONRR search feature in Edge - possible screen size bug

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#2992]
In Edge, when the screen size is small enough that you have to click the hamburger to see the search option, once you click the search option the screen gives the null Home. The search box does not appear. We need to makes sure that the search box appears even if small screen dimensions.

<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW4rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff71ab3029799aec0b3bb53eb872868f41afbdb4/image.png" alt="image.png" />

<img width="1218" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWorQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9da861da1eff9468efee0e5b46c5528bbbf86dd/image.png" alt="image.png" />

**Comment by Maroyafaied** [comment]
This link is wrong https://onrr.gov/search-results , it should be https://search.usa.gov/search?affiliate=onrr.gov&query=

**Comment by greensomes** [comment]
This has been fixed and is ready for review.

**Comment by greensomes** [comment]
@cthomasONRR, if you have a moment, please got to [dev](https://dev-onrr-frontend.app.cloud.gov) and enter the Responsive Design mode in your browser to verify that the fix is good to go. Thanks!

**Comment by cthomasONRR** [comment]
@greensomes I just tested again, and it works for me:

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/37798af3-6465-4291-a704-4f7f9dd62843)

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/a810cdb8-4e6c-4530-be57-43ba4e29c8cb)

**Comment by greensomes** [comment]
@cthomasONRR, should we release this fix to prod? Alternatively, we can queue it to go with other changes. My concern is that we shelve it and forget it.

**Comment by cthomasONRR** [comment]
@greensomes I think it's ok to release, I don't want to forget about it either. As long as you don't see any issue releasing, let's do it :)
