### ISSUE TITLE
February 2024 ONRR events for onrr.gov

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2993]
This issue was submitted in the mailbox. Please respond to Stephanie's email with the dev link to review

Good Afternoon,
Please post the attached Indian Outreach event information for February 2024 to the ONRR events (Events | Office of Natural Resources Revenue (onrr.gov)) on onrr.gov.  If you have any questions, please let me know.

 

Thank you,

**Comment by lpgoldstein** [comment]
reviewed and approved via email.
