### ISSUE TITLE
Add plant statements to minngl RV example

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#2994]
- [x] Lindsay: MinNGL, onrr.gov/references/valuation/minngl, https://dev-onrr-cms.app.cloud.gov/admin/content/pages/189
waiting on plant statement

**Comment by lpgoldstein** [comment]
@cthomasONRR I pushed it live because of some wonky cms issues. Does this look okay to you? 
https://onrr.gov/references/valuation/minngl?tabs=sample-statement

**Comment by cthomasONRR** [comment]
@lpgoldstein Yes, I see it and it looks ok.
