### ISSUE TITLE
Update org chart 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/onrr.gov-site#2995]
This issue came in as IT help desk ticket from Christina Mathers. 

Please add Dane Templin as the Western Audit Management Program Manager and remove Linda Shishido.  Also, please add Heidi Badaracco as Senior Advisor to IT Modernization under Tim Wight.   Thank you!

**Comment by eelzi-ONRR** [comment]
Waiting to hear back from Christina to see if we need to add another type of box in the org chart or if Heidi can be added using the program manager box

**Comment by eelzi-ONRR** [comment]
Approved via email
