### ISSUE TITLE
Review website accessibility statements for updates

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#2997]
According to Sid this needs to be done by March 19, 2024

**Comment by Maroyafaied** [comment]
Will work on this once DOI lets us know they're done with their updates.

**Comment by eelzi-ONRR** [comment]
Sid sent me more info: 

Good morning,
Per OMB Memorandum M-24-08, agencies are required to:
By March 20, 2024,
•	agencies shall establish (or review and update, as appropriate) digital accessibility statements on all agency websites.  
•	agencies shall establish (or review and update, as appropriate) a public feedback mechanism for receiving complaints or reports about accessibility issues with agency websites and digital services and begin to track, review, and address feedback.
Per GSA’s Government-wide IT Accessibility Program, DOI can establish and maintain a single accessibility statement webpage for all components to point to (such as the Department’s accessibility statement), or each agency can have a statement for each enterprise website. For additional guidance, please see Developing a Website Accessibility Statement.
By Friday, March 8, 2024, please provide confirmation by completing the attached spreadsheet (columns G and H) that your bureau/office has completed this requirement for your websites. Please let me know if you have any questions.

The spreadsheet indicates we need both a statement and instructions on a public feedback mechanism

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Do you know if the DOI accessibility page (https://www.doi.gov/accessibility) has been reviewed? It says last modified 8/2/22... but not sure if they reviewed it and found everything fine as-is.

**Comment by cthomasONRR** [comment]
I found one new  link in the disability section within the DOI accessibility page that we didn't have so I added that and updated the 'updated date'  in dev: https://dev-onrr-frontend.app.cloud.gov/accessibility

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/ab3fd8c0-597b-4942-a9ac-543dc7366b2f)

**Comment by eelzi-ONRR** [comment]
Sid asked we make sure our statement meets these requirements: https://www.section508.gov/manage/laws-and-policies/website-accessibility-statement/

**Comment by cthomasONRR** [comment]
ONRR page is live and NRRD is in a PR. Closing this issue.
