### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – February 2024

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#2999]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “February 2024 Lease Agreement XREF.txt" and "February 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 2/5/2024.

[Febuary 2024 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14168427/Febuary.2024.Lease.Agreement.XREF.xlsx)
[Febuary 2024 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/14168433/Febuary.2024.Lease.Agreement.XREF.txt)

**Comment by cthomasONRR** [comment]
@StaceyKaiser 

Good morning,

These updates are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us approval to go live.

Thanks,
Christine

**Comment by StaceyKaiser** [comment]
Files have been reviewed and can be moved to the live site.  Thanks!

**Comment by cthomasONRR** [comment]
@StaceyKaiser Great, thanks! These files are now live: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers.
