### ISSUE TITLE
Requirements list for ONRR's Directus WYSIWYG

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3000]
I created a document [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/FY24/Requirements%20list%20for%20Directus%20WYSIWYG.docx?d=w357e48cc1d574a6d9eb8934beea554d5&csf=1&web=1&e=tn6efZ) for us to list our requirements for the Directus WYSIWYG. Let's try to finalize this list next sprint for Jeff.

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU0wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--949748146c45a66edc4fa05ee4823eb351f5c551/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
I added my edits to this document.
