### ISSUE TITLE
February Indian Index Zone data

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3001]
Hello! The Indian Index Zone prices for February 2024 are ready to be posted on ONRR.gov. A separate email with data will be sent. Can you please make sure that the price ending in zero display the price to the hundredths place? Thank you!!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Everything looks, good! Thanks for taking care of that so quickly!

From: lpgoldstein ***@***.***>
Sent: Tuesday, February 6, 2024 3:21 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] February Indian Index Zone data (Issue #3001)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by lpgoldstein** [comment]
@penvosej it's live!
