### ISSUE TITLE
ONRR.gov NYMEX Prices January 2024

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#3002]
The January NYMEX prices are ready to be uploaded to the ONRR.gov site. I have attached the spreadsheet for uploading as well

January NYMEX:  73.86
January Roll: -0.29

Thanks
Cory Forgrave
@Sudarr
[NYMEX012024.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14196681/NYMEX012024.xlsx)

**Comment by lpgoldstein** [comment]
@forgravec ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by forgravec** [comment]
It looks good...Thanks!

Cory
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, February 7, 2024 9:41 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] ONRR.gov NYMEX Prices January 2024 (Issue #3002)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://github.com/forgravec> ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by lpgoldstein** [comment]
@forgravec it's live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
