### ISSUE TITLE
Lease & Agreement Contacts Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3003]
Please update the lease & agreement contacts page, https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts, using the shared spreadsheet.  All changes have been highlighted.

Please note that New Operator Numbers and New Payor Numbers have been removed, we've now combined those titles to New Customer number on the spreadsheet.  The contact Tony Demon remained the same.

Please let me know if you have any questions.

Thank You
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj! This is ready to review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by bowlenj** [comment]
Wow this looks perfect! It took me longer to update the spreadsheet than it took you to update the site :)

Approved to push live & close

THANK YOU!!!!!!!!!!!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Wednesday, February 7, 2024 10:07 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Lease & Agreement Contacts Update (Issue #3003)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @bowlenj<https://github.com/bowlenj>! This is ready to review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by eelzi-ONRR** [comment]
@bowlenj Awesome! This is now live: https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by bowlenj** [comment]
[heart]         Bowlen, Jessica G reacted to your message:
________________________________
From: Erin Elzi ***@***.***>
Sent: Wednesday, February 7, 2024 5:18:44 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Lease & Agreement Contacts Update (Issue #3003)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> Awesome! This is now live: https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
