### ISSUE TITLE
WebCenter Portal Link Issue

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3004]
We were notified that the WebCenter Portal (external) link on the ONRR.gov homepage on the Reporting tile is not opening in Chrome but it is working in Edge.

Is there anything we need to do to correct that on ONRR.gov?

Thank You
Jessica Bowlen

**Comment by Maroyafaied** [comment]
@bowlenj I'm able to open these links in Chrome. Since we don't manage the WebCenter Portal system, I'm not sure if it might've been down when the user tried to access it.  Can you ask the user to try again?

**Comment by bowlenj** [comment]
Thank you Maroya, we don't think the site was down we're just not sure what is going on.  I cleared my casche and tried again and now I can't get the link to open in either chrome or edge.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Maroyafaied ***@***.***>
Sent: Thursday, February 8, 2024 6:53 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] WebCenter Portal Link Issue (Issue #3004)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> I'm able to open these links in Chrome. Since we don't manage the WebCenter Portal system, I'm not sure if it might've been down when the user tried to access it. Can you ask the user to try again?

**Comment by lpgoldstein** [comment]
@bowlenj WebCenter Portal opens in both Chrome and Edge for me this morning. Let's check in on 2/12 since you are out today.

**Comment by bowlenj** [comment]
Good Morning,

Thank you for looking into this issue with us.  As stated in chat you are unable to duplicate the issue on your side and the links are all the same.  I will submit a ticket to the helpdesk.

Please close the GitHub ticket.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, February 9, 2024 7:49 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] WebCenter Portal Link Issue (Issue #3004)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> WebCenter Portal opens in both Chrome and Edge for me this morning. Let's check in on 2/12 since you are out today.
