### ISSUE TITLE
List of all the use cases for the inline link editor

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3010]
Add urls and screenshots to this issue to show Jeff all the ways the inline links are used on the front end.

Note that not all inline links are added via the inline link editor. In collections (press releases and reporter letters), we add the file to the entry in the cms and it creates the inline link on the front end automatically. We do not use the editor for those.

**Comment by lpgoldstein** [comment]
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/be4e2017-ee26-4f78-82a4-991fe2ceb5de)

**Comment by lpgoldstein** [comment]
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/4b8f0042-b24c-4ba2-a6f8-97fa74b44336)

**Comment by eelzi-ONRR** [comment]
On a card with other links: https://onrr.gov/
In this case, the other links are a mix of internal pages and external
<img width="375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48e2a1579e918d24dd5687e2aa8c6cec685e8ba9/image.png" alt="image.png" />

**Comment by eelzi-ONRR** [comment]
On it's own - not in a list of links or a paragraph of other text https://onrr.gov/about/organization?tabs=organization-chart <img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0piQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ec88d8015aca4eea98a46e6cd44ce3c086bb0e0/image.png" alt="image.png" />

**Comment by greensomes** [comment]
See **Potential solutions** sections inline in the comments above for possible ways to address replacing the inline link editor with functionality provided natively by Directus.

**Comment by cthomasONRR** [comment]
Meeting set for Monday 3/9 @ 11:30
