### ISSUE TITLE
Update Refund form

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3011]
Hello,

I need to update the refund form on ONRR.gov. Location: https://onrr.gov/paying/payment-options?tabs=refunds. 

[ONRR Refund Request Form.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/14315789/ONRR.Refund.Request.Form.pdf)

Thank you!

**Comment by eelzi-ONRR** [comment]
Hello @Sheetsj  - the file had been updated and is ready for review: https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds

**Comment by Sheetsj** [comment]
Looks great ! Thank you!

**Comment by eelzi-ONRR** [comment]
It's live: https://onrr.gov/paying/payment-options?tabs=refunds

Have a great weekend!

**Comment by Sheetsj** [comment]
Thanks! You have a great weekend as well.
