### ISSUE TITLE
DISC Contact Missing Lease and Agreement Contact

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3017]
Please add the Offshore Leases contact to the Lease & Agreement contacts page per the shared spreadsheet.  The contact info was there before but it looks like it was removed somehow.  I've highlighted the row that needs to be added to onrr.gov on the shared spreadsheet.

Lease & Agreement Contacts page - https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

Please let me know if you have any questions.

Thank you
Jessica Bowlen

**Comment by lpgoldstein** [comment]
@bowlenj Check out tab 4 - https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
ready for your review

**Comment by bowlenj** [comment]
Perfect, thank you for getting that added so quickly!  Approved to go live and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, February 27, 2024 10:34 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Missing Lease and Agreement Contact (Issue #3017)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> Check out tab 4 - https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
ready for your review

**Comment by lpgoldstein** [comment]
@bowlenj It's live! https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
