### ISSUE TITLE
Update Feb NYMEX on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3022]
Good afternoon,

Please update onrr.gov with the Feb NYMEX prices as attached.

Thanks,

Sean
@sudarr

[NYMEX022024.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14486767/NYMEX022024.xlsx)

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices it's live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
