### ISSUE TITLE
March Indian Index Zone prices for ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3023]
Good afternoon! The Indian Index Zone prices for March 2024 are ready to be posted on ONRR.gov. A separate email with data will be sent. Thank you for posting this for us!!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Hi, Lindsay,

The updated webpage looks good!

From: lpgoldstein ***@***.***>
Sent: Monday, March 4, 2024 8:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] March Indian Index Zone prices for ONRR.gov (Issue #3023)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by lpgoldstein** [comment]
@penvosej live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
