### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – March 2024

### ISSUE THREAD

**Issue by hasketta** [DOI-ONRR/onrr.gov-site#3024]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “March 2024 Lease Agreement XREF.txt" and "March 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 3/5/2024

[March 2024 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14498374/March.2024.Lease.Agreement.XREF.xlsx)
[March 2024 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/14498376/March.2024.Lease.Agreement.XREF.txt)

**Comment by cthomasONRR** [comment]
@hasketta 

These changes are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us approval to go live.

Thanks,
Christine

**Comment by hasketta** [comment]
Peer review has been completed.  The files can be moved to the live site.  Thanks!

**Comment by lpgoldstein** [comment]
@hasketta the changes are live! https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
