### ISSUE TITLE
Explore data: improve selection in map for specific states

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3027]
Previously addressed: at 100% on large laptop screen dimension, this button was blocking states so that a user could not see nor select. 

Now: the states are visible, but have limited select-ability (this issue can be seen in FL).

**Comment by eelzi-ONRR** [comment]
Also a problem with Alaska

**Comment by AlexandracmONRR** [comment]
@greensomes and @eelzi-ONRR - I just tested it out at different magnifications and on the laptop size and it is working! Thank you, Jeff!
