### ISSUE TITLE
Update 2022 gas major portion prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3031]
Good morning,

Hopefully this format still works for the annual mpp updates, but please let me know if you need it to be changed. As indicated in the attachment, responses are due by May 31, 2024.

[Maj_Portion_FinalPrices_2022.xls](https://github.com/DOI-ONRR/onrr.gov-site/files/14604742/Maj_Portion_FinalPrices_2022.xls)

@sudarr

Thanks!
- Sean

**Comment by lpgoldstein** [comment]
[Indian_Gas_Major_Portion_Sep_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605204/Indian_Gas_Major_Portion_Sep_2022.xlsx)
[Indian_Gas_Major_Portion_Oct_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605206/Indian_Gas_Major_Portion_Oct_2022.xlsx)
[Indian_Gas_Major_Portion_Dec_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605207/Indian_Gas_Major_Portion_Dec_2022.xlsx)
[Indian_Gas_Major_Portion_July_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605208/Indian_Gas_Major_Portion_July_2022.xlsx)
[Indian_Gas_Major_Portion_May_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605210/Indian_Gas_Major_Portion_May_2022.xlsx)
[Indian_Gas_Major_Portion_Apr_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605211/Indian_Gas_Major_Portion_Apr_2022.xlsx)
[Indian_Gas_Major_Portion_Feb_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605212/Indian_Gas_Major_Portion_Feb_2022.xlsx)
[Indian_Gas_Major_Portion_Mar_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605213/Indian_Gas_Major_Portion_Mar_2022.xlsx)
[Indian_Gas_Major_Portion_Jan_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605214/Indian_Gas_Major_Portion_Jan_2022.xlsx)
[Indian_Gas_Major_Portion_June_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605215/Indian_Gas_Major_Portion_June_2022.xlsx)
[Indian_Gas_Major_Portion_Aug_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605216/Indian_Gas_Major_Portion_Aug_2022.xlsx)
[Indian_Gas_Major_Portion_Nov_2022.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14605217/Indian_Gas_Major_Portion_Nov_2022.xlsx)

**Comment by cthomasONRR** [comment]
@boices This is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-major-portion

Please review and give us approval to go live.

In the future, is it possible for you to send us separate spreadsheets for every month, similar to what Lindsay posted in this issue?

Thanks,
Christine

**Comment by boices** [comment]
Prices look great and we'll use that format next year!

**Comment by cthomasONRR** [comment]
@boices Great! These prices are live: https://github.com/DOI-ONRR/onrr.gov-site/issues/2923
