### ISSUE TITLE
DISC ONRR.gov Contact Update

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3035]
Please update DISC contact information per shared spreadsheet, all updates have been highlighted in yellow.  The below webpages on ONRR.gov all have changes associated with them:

Lease & Agreements - https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
Onshore Production - https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
Offshore Production - https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
Royalty - https://onrr.gov/about/contact/royalty-contacts?tabs=contacts

Please let me know if you need additional information or if you have any questions.

THANK YOU!!!!
Jessica Bowlen

**Comment by eelzi-ONRR** [comment]
Hi @bowlenj! These are ready to review: 
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production
