### ISSUE TITLE
Improve SEO for Reporter Training tabs

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3038]
Reporter training pages in search results do not include details of what each page is for specific tabs (training schedule, training videos, etc.).

In addition, the Oil and Gas Production videos tab has an "Untitled" label.
https://www.onrr.gov/references/training?tabs=training-videos,oil-gas-production

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/122935097/d2a2394a-c7e8-4f78-baba-02f70a6f7a1e)

**Comment by eelzi-ONRR** [comment]
From IDEA search engine questions. Not possible with our directus set-up
