### ISSUE TITLE
Change to Indian Payor Handbook

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#3039]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Hello!

As we discussed, RV would like to start with posting our Valuation Resources for Indian Lands (former the Indian Handbook) as a locked Word document on the handbook cards on these pages:
https://onrr.gov/references/handbooks
https://onrr.gov/references/valuation?tabs=valuation-regulations
[Valuation Resources for Indian Leases 3.2024.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14706395/Valuation.Resources.for.Indian.Leases.3.2024.docx)

It is not broken out by chapter.  It is a very succinct document, so there is no need for multiple files.  Please let me know if something doesn't work correctly!  Thank you!

**Comment by eelzi-ONRR** [comment]
Thanks @jpetersononrr! We'll work these into the sprint that starts next week!

**Comment by eelzi-ONRR** [comment]
@jpetersononrr This is ready for review: 
https://onrr.gov/references/valuation?tabs=valuation-regulations
https://onrr.gov/references/handbooks

Due to a problem we had earlier to day these have already been pushed to the live site. But we can easily change/take them down if needed.

**Comment by jpetersononrr** [comment]
Those look great!  Thank you!!

Jodie Peterson
Minerals Revenue Specialist
Royalty Valuation
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

From: Erin Elzi ***@***.***>
Sent: Wednesday, March 27, 2024 3:18 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Change to Indian Payor Handbook (Issue #3039)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://github.com/jpetersononrr> This is ready for review:
https://onrr.gov/references/valuation?tabs=valuation-regulations
https://onrr.gov/references/handbooks

Due to a problem we had earlier to day these have already been pushed to the live site. But we can easily change/take them down if needed.

**Comment by eelzi-ONRR** [comment]
@jpetersononrr Awesome! Closing the issue since it's already live
