### ISSUE TITLE
Changes to Indian Example:  Index Zone Arm's-Length Dedicated Alt DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#3041]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

As discussed, the example here needs to be updated:  https://onrr.gov/references/valuation/pd-alt

I have attached a copy for you to work from that is highlighted with changes.  I have dropped some comments in the document to hopefully make it easier too!  Please let me know if you have any questions at all.  More than happy to discuss!  I will attach a locked copy of an accessible Word doc shortly!

[Processed Gas ALDC Index Alt DA 3.2024 Highlighted changes.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14749091/Processed.Gas.ALDC.Index.Alt.DA.3.2024.Highlighted.changes.docx)

**Comment by jpetersononrr** [comment]
I forgot, we would like this to be updated no later than April 25 if at all possible.  It will be included in a paper being presented at RMMLF (now known as FNREL)  that week.  Thank you!

**Comment by lpgoldstein** [comment]
@jpetersononrr ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt?tabs=detailed-example,part-c-comparing-the-values-determined-in-parts-a-b&panel=assumptions-processed-gas-reporting-arms-length-dedicated-contract-in-an-index-zone-with-alternative-dual-accounting

**Comment by jpetersononrr** [comment]
You are awesome!

I only see 2 small things. 

1.  This one is on me.  Can you add a link in the text in the intro paragraph in PC 07 to go to the Minimum NGL example?  Toward the end here:  As those fees cannot be netted against the sales value, they should instead be taken as allowances where appropriate. For a more in-depth explanation of why the NGL minimum value is calculated this way, please see our full **Processed Gas Reporting: Minimum Value Provision for NGLs Example** (refer to Scenario 2 for details pertaining to this example).
2.  The graphic on Step 1 of Part C needs to be changed because the math changed.  I may have neglected to highlight that!  

I've attached a locked copy of the document too to replace the downloadable PDF.  Thank you!!  This is amazing being done so fast!!
[Processed Gas ALDC Index Alt DA.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14775794/Processed.Gas.ALDC.Index.Alt.DA.docx)

**Comment by lpgoldstein** [comment]
@jpetersononrr I think I got it all this time! https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt

**Comment by jpetersononrr** [comment]
This is fantastic, and you are amazing!  Thank you!!

Jodie Peterson
Minerals Revenue Specialist
Royalty Valuation
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

From: lpgoldstein ***@***.***>
Sent: Wednesday, March 27, 2024 10:44 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Changes to Indian Example: Index Zone Arm's-Length Dedicated Alt DA (Issue #3041)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://github.com/jpetersononrr> I think I got it all this time! https://dev-onrr-frontend.app.cloud.gov/references/valuation/pd-alt

**Comment by lpgoldstein** [comment]
@jpetersononrr It's live! https://onrr.gov/references/valuation/pd-alt

**Comment by lpgoldstein** [comment]
@jpetersononrr When you have time, could you please send me an accessible version of the word doc to repost? Thanks!

**Comment by jpetersononrr** [comment]
I swear I'm going to punch Word...I think it's fine now.
[Processed Gas ALDC Index Alt DA.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14856853/Processed.Gas.ALDC.Index.Alt.DA.docx)

**Comment by lpgoldstein** [comment]
@jpetersononrr all good now! Thanks!
