### ISSUE TITLE
Changes to Indian Example:  Index Zone Non-Arm's Length Dedicated Actual DA

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#3043]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
As discussed, the example here needs to be updated: https://onrr.gov/references/valuation/pnd-act

I have attached a copy for you to work from that is highlighted with changes.  I have dropped some comments in the document to hopefully make it easier too!  Please let me know if you have any questions at all.  More than happy to discuss!  I will attach a locked copy of an accessible Word doc shortly!  Also, if this can at all be completed by April 25, we would be incredibly grateful!  Thank you!

[Processed Gas ALNDC Index Actual DA 3.2024 Highlighted changes.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14749113/Processed.Gas.ALNDC.Index.Actual.DA.3.2024.Highlighted.changes.docx)

**Comment by cthomasONRR** [comment]
@jpetersononrr This is in dev ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act?tabs=detailed-example,pc07

**Comment by jpetersononrr** [comment]
This looks fantastic!  Here's a locked copy to replace the downloadable PDF with a downloadable word doc.  Thank you so much!!
[Processed Gas ALNDC Index Actual DA.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/14762233/Processed.Gas.ALNDC.Index.Actual.DA.docx)

**Comment by cthomasONRR** [comment]
@jpetersononrr Thanks, the new doc is added: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act?tabs=overview.

**Comment by jpetersononrr** [comment]
That looks great!

Jodie Peterson
Minerals Revenue Specialist
Royalty Valuation
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

From: Christine Thomas ***@***.***>
Sent: Tuesday, March 26, 2024 1:18 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Changes to Indian Example: Index Zone Non-Arm's Length Dedicated Actual DA (Issue #3043)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://github.com/jpetersononrr> Thanks, the new doc is added: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pnd-act?tabs=overview.

**Comment by cthomasONRR** [comment]
@jpetersononrr Thanks, this is now live: https://www.onrr.gov/references/valuation/pnd-act
