### ISSUE TITLE
2024 ONRR Reporter Training

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3045]
Please add the attached agendas and edit the text at url: 

https://www.onrr.gov/references/training?tabs=training-schedule

Please change the text "No upcoming training" to reflect the upcoming training "13-17 May, 2024, virtual training via MS Teams"

[Oil and Gas Reporter Training Agenda.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/14776956/Oil.and.Gas.Reporter.Training.Agenda.pdf)
[Solids Reporter Training Agenda.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/14776957/Solids.Reporter.Training.Agenda.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS 

These changes are now in dev:
- https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule
- https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events

Please review and give us approval to go live.

Thanks,
Christine

**Comment by jasonDSTS** [comment]
Hi Christine,

Thanks for your work everything looks great.

The links in the .pdfs were not working.  Can you please replace them with the attached so I can try again?

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, March 27, 2024 11:45 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] 2024 ONRR Reporter Training (Issue #3045)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

These changes are now in dev:

  *   https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule
  *   https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS 

Thanks for sending those in teams!
The 2 PDFs are now updated:

- https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule
- https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events

**Comment by jasonDSTS** [comment]
Everything is great!

Thank you, please go live.

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, March 27, 2024 12:47 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] 2024 ONRR Reporter Training (Issue #3045)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

Thanks for sending those in teams!
The 2 PDFs are now updated:

  *   https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule
  *   https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events

**Comment by cthomasONRR** [comment]
@jasonDSTS 

Great! This is now live:

- https://www.onrr.gov/references/training?tabs=training-schedule
- https://www.onrr.gov/events?tabs=other-onrr-events

Thanks for your patience!

**Comment by jasonDSTS** [comment]
[heart]         Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, March 27, 2024 8:16:12 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] 2024 ONRR Reporter Training (Issue #3045)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

Great! This is now live:

  *   https://www.onrr.gov/references/training?tabs=training-schedule
  *   https://www.onrr.gov/events?tabs=other-onrr-events

Thanks for your patience!
