### ISSUE TITLE
Update Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3048]
Please replace the existing document, Federal Onshore Terminable Lease - sorted by Due Date with the attached excel file located in the Reference Lists on the following webpage - https://onrr.gov/reporting/revenue?tabs=references

Please also changed (updated 3/01/2024) to (updated 4/02/2024)

[20240402.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14842167/20240402.xlsx)

Thank You
Jessica Bowlen

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review! https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by bowlenj** [comment]
Looks great, thank you!  Approved to push live & close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, April 2, 2024 12:25 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Federal Onshore Terminable Leases (Issue #3048)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> ready for your review! https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by lpgoldstein** [comment]
@bowlenj It's live!
