### ISSUE TITLE
Update Refund page

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3050]
Hello,

Location: https://onrr.gov/paying/payment-options?tabs=refunds

Could you please change under the "Note" section on the refund page under number 3. Change "FORM-2014" to "form ONRR-2014". Also change number 3(a) from "FORM-2014" to "form ONRR-2014". 

Under Notes number 5. remove the - between 120 days. 

Also, please upload the updated form that I attached. 
[ONRR Refund Request Form.pdf](https://github.com/DOI-ONRR/onrr.gov-site/files/14855937/ONRR.Refund.Request.Form.pdf)

Thank you!

**Comment by cthomasONRR** [comment]
@Sheetsj These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Sheetsj** [comment]
Looks great! Thank you!

**Comment by cthomasONRR** [comment]
@Sheetsj Great, this is now live: https://www.onrr.gov/paying/payment-options?tabs=refunds
