### ISSUE TITLE
Update March NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3051]
Good afternoon,

Please update the March NYMEX CMA and Roll values on onrr.gov according to the attached file.

Thanks,
Sean

@sudarr
[NYMEX032024.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14875529/NYMEX032024.xlsx)

**Comment by AlexandracmONRR** [comment]
@sudarr - thanks for your submission. Please review the [dev site](https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices) and let me know if it is approved for the live site.

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by AlexandracmONRR** [comment]
@boices and @sudarr - the NYMEX prices are now live!

https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
