### ISSUE TITLE
ONRR.gov Indian Gas Index Zone April 2024

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#3052]
The April Indian Gas Index Zone prices are ready to be posted onto ONRR.gov.  The prices are attached.

Thanks
Cory Forgrave
@Sudarr
[Indian_Index_Zone_2024_04.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14875690/Indian_Index_Zone_2024_04.xlsx)

**Comment by eelzi-ONRR** [comment]
Hi @forgravec! This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&panel=index-zone-arms-length-non-dedicated-contract

**Comment by forgravec** [comment]
Prices look good.

Thanks,
Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: Erin Elzi ***@***.***>
Sent: Thursday, April 4, 2024 12:53 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] ONRR.gov Indian Gas Index Zone April 2024 (Issue #3052)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @forgravec<https://github.com/forgravec>! This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&panel=index-zone-arms-length-non-dedicated-contract

**Comment by eelzi-ONRR** [comment]
@forgravec Great! This is now live: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
