### ISSUE TITLE
Replace the existing active lease file

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3054]
Please replace the existing active lease file with the attached updated active lease file on the following webpage - [Reference Lists & Codes | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases).

Please also change (updated 01/02/2024) to read 4/08/2024

[aLwState.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14906421/aLwState.xlsx)

**Comment by jasonDSTS** [comment]
Looks good please publish.

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Erin Elzi ***@***.***>
Sent: Monday, April 8, 2024 8:42 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Replace the existing active lease file (Issue #3054)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Good morning, @jasonDSTS<https://github.com/jasonDSTS> - this is now ready to review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases

**Comment by eelzi-ONRR** [comment]
@jasonDSTS Great! This is now live: https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases
