### ISSUE TITLE
March 2024 IBMP Pirces

### ISSUE THREAD

**Issue by damionschulte** [DOI-ONRR/onrr.gov-site#3062]
All I have updated the Data for ONRR spreadsheet on the OneDrive with the March 2024 IBMP Prices. Can you please prepare them to be published to the website?
I've also attached a sheet with the prices in it as well.  Please let me know if you there is anything else I can do.  

Thank you
Damion Schulte 

@sudarr
[March 24 IBMP For GitHub.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14908835/March.24.IBMP.For.GitHub.xlsx)

**Comment by AlexandracmONRR** [comment]
@damionschulte and @sudarr - please review the updated pricing date on our [dev site](https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion&years=2024). 

If it looks good, please send your approval and we will publish live.

**Comment by AlexandracmONRR** [comment]
@damionschulte - thanks for letting me know, I was able to move up the march data points to the top of the list, so it should be the first thing you see now. Please take a look at the [dev site here](https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion).

Thanks,
Alex

**Comment by damionschulte** [comment]
These prices look great!  Thank you.

From: Alexandra C McNally ***@***.***>
Sent: Monday, April 8, 2024 1:54 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] March 2024 IBMP Pirces (Issue #3062)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> - thanks for letting me know, I was able to move up the march data points to the top of the list, so it should be the first thing you see now. Please take a look at the dev site here<https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion>.

Thanks,
Alex

-

**Comment by AlexandracmONRR** [comment]
IBMP prices are now [live](https://onrr.gov/references/valuation?tabs=pricing,indian-oil-major-portion). Thank you!
