### ISSUE TITLE
Replace the existing agreement file

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3064]
Please replace the existing agreement file with the attached updated agreement file on the following webpage under Reference Lists - [Oil & Gas Revenue | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/revenue?tabs=references).

Please also change (updated 01/02/2024) to read 4/09/2024.

[100pct fed agreements.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/14922518/100pct.fed.agreements.xlsx)

**Comment by eelzi-ONRR** [comment]
Hi @jasonDSTS, this is ready to review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by jasonDSTS** [comment]
Looks good please publish!

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, April 9, 2024 12:53 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Replace the existing agreement file (Issue #3064)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @jasonDSTS<https://github.com/jasonDSTS>, this is ready to review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by eelzi-ONRR** [comment]
Great! It's live: https://onrr.gov/reporting/revenue?tabs=references

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: Erin Elzi ***@***.***>
Sent: Tuesday, April 9, 2024 7:04:52 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Replace the existing agreement file (Issue #3064)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Great! It's live: https://onrr.gov/reporting/revenue?tabs=references
