### ISSUE TITLE
Use robots.txt file to disable preview site

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3066]
Figure out and implement changes to robots.txt file in order to remove preview site from search results

**Comment by eelzi-ONRR** [comment]
This might be a bigger issue - thinking through it more we also should indicate canonical URLs so lessen the number of results that come up form the old site

**Comment by lpgoldstein** [comment]
<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6c25a4cc9d84abcb8b3294c278699ccd3e0df24/image.png" alt="image.png" />
