### ISSUE TITLE
Osage pricing initial meeting and requirements

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#3068]
[Notes and requirement document](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/OSAGE/Osage%20pricing%20requirements%20and%20next%20steps.docx?d=wb9d39963d9d1415699dff332dd480c03&csf=1&web=1&e=1wemQ3)

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I added a couple things to the requirements. Ready to close the issue when everyone else is

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein Looks good.
