### ISSUE TITLE
Updates to ONRR's Information Collection Requests Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#3070]
Good morning, 

I am requesting updates to this page https://onrr.gov/references/icrs/1012-0001

Please add the bullet below under Federal Register Publications 
"60-Day Agency Information Collection - (89 FR 269315--April 16, 2024)"

As a hyperlink to the (89 FR 269315--April 16, 2024) language, please add the link below

https://www.federalregister.gov/documents/2024/04/16/2024-08019/agency-information-collection-activities-accounts-receivable-confirmations-reporting

Thank you

**Comment by cthomasONRR** [comment]
@gingerhensley 
Good morning, 
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0001. 
Please review and give us approval to go live. 
Thanks!

**Comment by gingerhensley** [comment]
Approve. thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley Great! These changes are live: https://www.onrr.gov/references/icrs/1012-0001. Closing this issue now.
