### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – April 2024

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#3074]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “April 2024 Lease Agreement XREF.txt" and "April 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 4/11/2024.
[April 2024 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/15014574/April.2024.Lease.Agreement.XREF.xlsx)
[April 2024 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/15014578/April.2024.Lease.Agreement.XREF.txt)

**Comment by lpgoldstein** [comment]
@StaceyKaiser This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Also I noticed that you are using an old link to this page - please bookmark the new link. The old link does redirect to the new page but we don't want you to get lost if it ever doesn't work! https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by StaceyKaiser** [comment]
@lpgoldstein thank you for letting me know we are using an outdated link.  I have updated our methodology with the new link.  The file on the dev site looks good and you can move it to the live site. Thanks!

**Comment by lpgoldstein** [comment]
@StaceyKaiser This is live! https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
