### ISSUE TITLE
Update term on webpages on ONRR.gov

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3083]
Please update all pages where "Customer Number" is found and replace with "ONRR Customer ID".

Attached is a word document with onrr.gov pages I found that need to be updated and screenshots showing the highlighted text that needs to updated to the new text, "ONRR Customer ID".

[Website updates_4-23-24.docx](https://github.com/DOI-ONRR/onrr.gov-site/files/15082704/Website.updates_4-23-24.docx)

Please let me know if you have any questions or need clarification!!

Thank You
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj I used our content audit to find all the following locations:

Getting Started - new reporter checklists
- https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id
- https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=oil-gas-revenue
- https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=solid-minerals
- https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=geothermal

System Access - troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - O&G production - new reporter checklist & troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=new-reporter-checklist&panel=get-an-onrr-customer-id
- https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - O&G revenue - new reporter checklist & troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=new-reporter-checklist
- https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - solid minerals - new reporter checklist
- https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=new-reporter-checklist

Reporting - geothermal - new reporter checklist
- https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=new-reporter-checklist

Contacts - Getting Started - troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?panel=i-need-an-onrr-customer-id

Contacts - System Access - troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/about/contact/system-access-contacts?panel=i-need-an-onrr-customer-id
 
Contacts - O&G production - troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?panel=i-need-an-onrr-customer-id

Contacts - O&G revenue - troubleshooting
- https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?panel=i-need-an-onrr-customer-id

**Comment by bowlenj** [comment]
Thank you Christine!

This looks great, I approve to push live and to close issue.

Thank you for catching the pages I missed, I really appreciate the extra time you put into it!!!!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, April 24, 2024 6:57 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update term on webpages on ONRR.gov (Issue #3083)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> I used our content audit to find all the following locations:

Getting Started - new reporter checklists

  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id
  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=oil-gas-revenue
  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=solid-minerals
  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=geothermal

System Access - troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - O&G production - new reporter checklist & troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=new-reporter-checklist&panel=get-an-onrr-customer-id
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - O&G revenue - new reporter checklist & troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=new-reporter-checklist
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-an-onrr-customer-id

Reporting - solid minerals - new reporter checklist

  *   https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=new-reporter-checklist

Reporting - geothermal - new reporter checklist

  *   https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=new-reporter-checklist

Contacts - Getting Started - troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?panel=i-need-an-onrr-customer-id

Contacts - System Access - troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/about/contact/system-access-contacts?panel=i-need-an-onrr-customer-id

Contacts - O&G production - troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?panel=i-need-an-onrr-customer-id

Contacts - O&G revenue - troubleshooting

  *   https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?panel=i-need-an-onrr-customer-id

**Comment by cthomasONRR** [comment]
@bowlenj Great! These updates are now live. Thanks!
