### ISSUE TITLE
Update the link provided with new penalty amounts.

### ISSUE THREAD

**Issue by KristianL3101** [DOI-ONRR/onrr.gov-site#3087]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Hello. Please change penalty amounts under "Civil Penalties" to as follows..

Link on ONRR.gov: https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties

"ONRR regulations at [30 CFR part 1241](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1241#sp30.3.1241.b) provide a grace period of at least 20 days for regulatory violations, such as failure to submit reports. Violations not fixed within the grace period are subject to civil penalties until fixed. These penalties can be up to $1,522.00 per day ($15,232.00 per day after 40 days)

"Certain violations, such as failure to permit an audit, failure to timely pay royalties, or submission/maintenance of false, inaccurate, or misleading information are subject to higher civil penalties. They can be as much as $30,461.00 or $76,155.00 per violation for each day the violation continues."

**Comment by eelzi-ONRR** [comment]
@KristianL3101 This is ready to review: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties

**Comment by KristianL3101** [comment]
Looks good. Thank you.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: Erin Elzi ***@***.***>
Sent: Friday, April 26, 2024 2:06 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update the link provided with new penalty amounts. (Issue #3087)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://github.com/KristianL3101> This is ready to review: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties

**Comment by eelzi-ONRR** [comment]
@KristianL3101 Great! This is now live: https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties
