### ISSUE TITLE
DISC Contact Updates to ONRR.gov

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3089]
Please update contacts list for DISC on onrr.gov as shown by the highlighted areas on the shared spreadsheet:

https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

Any questions please feel free to contact me.

**Comment by lpgoldstein** [comment]
@jasonDSTS this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by jasonDSTS** [comment]
Line 417 on the Offshore tab was incorrect.  I fixed it.  Please update.  Everything else looks good!

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, April 29, 2024 1:51 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Updates to ONRR.gov (Issue #3089)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production

https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by lpgoldstein** [comment]
@jasonDSTS that one is fixed. Once you approve, I'll publish them all.

**Comment by jasonDSTS** [comment]
Looks good, please publish.

You folks are the best!

Thanks,

Jason
Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, April 29, 2024 2:04 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Updates to ONRR.gov (Issue #3089)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> that one is fixed. Once you approve, I'll publish them all.

**Comment by lpgoldstein** [comment]
@jasonDSTS These are live! https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, April 29, 2024 8:46:37 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] DISC Contact Updates to ONRR.gov (Issue #3089)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> These are live! https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production

https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
