### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – May 2024

### ISSUE THREAD

**Issue by Daphnesmum** [DOI-ONRR/onrr.gov-site#3091]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-number titled “Cross-Reference Lease to Agreement Number” with the new provided files titled, “May 2024 Lease Agreement XREF.txt" and "May 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 5/1/2024.
THANK YOU
______________________________________________________________________________________________________________________________________
[May 2024 Lease Agreement XREF.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/15178363/May.2024.Lease.Agreement.XREF.xlsx)
[May 2024 Lease Agreement XREF.txt](https://github.com/DOI-ONRR/onrr.gov-site/files/15178367/May.2024.Lease.Agreement.XREF.txt)

**Comment by eelzi-ONRR** [comment]
@Daphnesmum This is ready for review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by Daphnesmum** [comment]
Peer review has been completed. The files can be moved to the live site. Thank you!

**Comment by eelzi-ONRR** [comment]
@Daphnesmum This is now live: https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
