### ISSUE TITLE
Correction request for ONRR.gov website

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3095]
Hello,

As explained in an email dated 4/26/2024, we have discovered two Indian Index Zone prices that need to be corrected. I will send an email shortly with the details.

Thank you,
Jessica
@sudarr

**Comment by cthomasONRR** [comment]
@penvosej 
Hi Jessica,

I updated these 2 November 2016 prices in the dev site: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2016

Please review and give us approval to go live.

Thanks,
Christine

**Comment by penvosej** [comment]
The updates look good. Thank you so much for taking care of that!

From: Christine Thomas ***@***.***>
Sent: Wednesday, May 1, 2024 3:15 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Correction request for ONRR.gov website (Issue #3095)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej>
Hi Jessica,

I updated these 2 November 2016 prices in the dev site: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2016

Please review and give us approval to go live.

Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@penvosej 
Good morning,

These changes are live: https://www.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone&years=2016

Thanks!
Christine
