### ISSUE TITLE
Create list of custom events to track with GTM

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3096]

**Comment by cthomasONRR** [comment]
Ideas discussed:
- Differentiate links between top menu nav and regular links
- Internal searches like contacts search
- Footer activity
-

**Comment by eelzi-ONRR** [comment]
- Differentiate where a doc is downloaded from (eg. is a 4444 pdf downloaded from the homepage or the forms page)
- Track as many things as possible in explore and query - including use of filters, how users select a location (map, add a location tab, comparison cards), use of add a column, etc.
- Any possible way that would make the filtered URLs from NRRD more easy to track in analytics

We'll bring these ideas up to the rest of the team at sync-up next week. Some of these might be beyond the scope of GTM but maybe we can figure out other solutions

**Comment by cthomasONRR** [comment]
Closing this issue and will discuss at sync-up next week
