### ISSUE TITLE
Indicate top 20 URLs as canonical

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3098]
Look in analytics and google search console for top 20 URLs from old site that still are used/come up in search results. Use files (robots?) to tell search engines to index the new URL instead of the old one

**Comment by eelzi-ONRR** [comment]
Took the top 20 URLs from google search console for which there was no canonical or google had selected the incorrect one (the old website, a dev link, or sometimes just wrong), and added the correct URLs to the sitemap.xml file so they will be indexed and improve search results)

@AlexandracmONRR This is one of the things that will improve the search results based on the tasks you were looking at for M-22-23.

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - Amazing, I'm going to add this into one of our tasks for action item #5 digitization and self-service optimization. Thank you!!
