### ISSUE TITLE
Add No Fear to footer

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#3100]
Per OMB M-23-22 - we need to have the DOI No Fear link in our footer

Agencies may need to convey information about legal compliance, points of contact, or other topics of interest to the public on their websites. In the footer of each agency’s principal website or principal sub-agency websites, the agency must include links to: o The agency’s “about” page, which contains descriptions of the mission and statutory authority of the agency, information about the organizational structure of the agency, and the agency’s strategic plan. o The agency’s Freedom of Information Act page. The agency’s accessibility statement. The agency’s vulnerability disclosure policy, which must include a security contact for the public to report observed or suspected information security issues. The equal employment opportunity data required to be posted by each agency under Title III of the Notification and Federal Employee Antidiscrimination and Retaliation Act of 2002 (No FEAR Act). The agency’s Privacy Program Page. In the footer of each agency’s website, or the entry point for a digital service, the agency must include links to the website’s privacy policy. Agencies should consult USWDS and Digital.gov for more specific recommendations on how to best display required links and other relevant information on websites and digital services.

**Comment by lpgoldstein** [comment]
https://www.doi.gov/pmb/eeo/reports-repository

**Comment by lpgoldstein** [comment]
https://dev-onrr-frontend.app.cloud.gov/

**Comment by lpgoldstein** [comment]
@cthomasONRR ready to review

**Comment by cthomasONRR** [comment]
@lpgoldstein looks good!
