### ISSUE TITLE
ONRR.gov - NYMEX Crude price - April 2024

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#3102]
The April NYMEX crude prices are ready to be added to the ONRR.gov website. The spreadsheet is attached as well to be added to the site.

NYMEX April:  84.39
NYMEX Roll:  0.76

Thanks,
[NYMEX042024.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/15221855/NYMEX042024.xlsx)

Cory Forgrave
@Sudarr

**Comment by eelzi-ONRR** [comment]
Hi @forgravec, This is ready to review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by eelzi-ONRR** [comment]
@forgravec Great! This is now live: https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
