### ISSUE TITLE
Update May Index Zone prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3103]
Good morning,

Please update the May prices according to the attachment.

Thank you!
@sudarr
[Indian_Index_Zone_2024_05.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/15221902/Indian_Index_Zone_2024_05.xlsx)

**Comment by AlexandracmONRR** [comment]
@boices and @sudarr - thank you for your submission. Please review the updated may prices [on the dev site](https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone).

If you approve of the changes, please let me know and I will publish live.
