### ISSUE TITLE
Please Replace Documents

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3104]
Please replace documents at:  
https://onrr.gov/references/training?tabs=training-presentations
with updated same-named documents attached.

Thanks,

Jason
[Solids Billing.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225941/Solids.Billing.pptx)
[Solids Valuation Sodium and Potassium.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225942/Solids.Valuation.Sodium.and.Potassium.pptx)
[1989 Federal and Indian Coal Royalty Rule Reporter Valuation Training.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225912/1989.Federal.and.Indian.Coal.Royalty.Rule.Reporter.Valuation.Training.pptx)
[2014 Adjustments and Recoupments.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225913/2014.Adjustments.and.Recoupments.pptx)
[2014 Reporting Errors.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225916/2014.Reporting.Errors.pptx)
[Commonly Used 2014 Transaction Codes.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225917/Commonly.Used.2014.Transaction.Codes.pptx)
[Federal and Indian Accounts Receivable and Debt Collection.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225918/Federal.and.Indian.Accounts.Receivable.and.Debt.Collection.pptx)
[Federal and Indian Billing.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225920/Federal.and.Indian.Billing.pptx)
[Form ONRR-4430 (P&R).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225921/Form.ONRR-4430.P.R.pptx)
[Form-2014 Basic Reporting Principles.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225922/Form-2014.Basic.Reporting.Principles.pptx)
[Liquid Verification System (LVS) and Gas Verification System (GVS).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225924/Liquid.Verification.System.LVS.and.Gas.Verification.System.GVS.pptx)
[Missing Production Reports.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225926/Missing.Production.Reports.pptx)
[OGOR Reporting Errors.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225928/OGOR.Reporting.Errors.pptx)
[ONRR Compliance Overview.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225929/ONRR.Compliance.Overview.pptx)
[ONRR Data Requests.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225930/ONRR.Data.Requests.pptx)
[ONRR Enforcement.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225931/ONRR.Enforcement.pptx)
[ONRR-4054 Oil and Gas Operations Report (OGOR).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225932/ONRR-4054.Oil.and.Gas.Operations.Report.OGOR.pptx)
[Royalty Reporting for eCommerce and Electronic Tools.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225934/Royalty.Reporting.for.eCommerce.and.Electronic.Tools.pptx)
[Solid Minerals Compliance.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225935/Solid.Minerals.Compliance.pptx)
[Solid Minerals Opening, Form ONRR-4444, Payor Codes, and EMARF.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225936/Solid.Minerals.Opening.Form.ONRR-4444.Payor.Codes.and.EMARF.pptx)
[SolidMineral Leases, Sales Summary, Sales Contracts & Facility Data, Handbook.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225938/SolidMineral.Leases.Sales.Summary.Sales.Contracts.Facility.Data.Handbook.pptx)
[Solids AR Basics.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225939/Solids.AR.Basics.pptx)

**Comment by lpgoldstein** [comment]
- [ ] [Solids Billing.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225941/Solids.Billing.pptx)
- [ ] [Solids Valuation Sodium and Potassium.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225942/Solids.Valuation.Sodium.and.Potassium.pptx)
- [ ] [1989 Federal and Indian Coal Royalty Rule Reporter Valuation Training.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225912/1989.Federal.and.Indian.Coal.Royalty.Rule.Reporter.Valuation.Training.pptx)
- [ ] [2014 Adjustments and Recoupments.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225913/2014.Adjustments.and.Recoupments.pptx)
- [ ] [2014 Reporting Errors.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225916/2014.Reporting.Errors.pptx)
- [ ] [Commonly Used 2014 Transaction Codes.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225917/Commonly.Used.2014.Transaction.Codes.pptx)
- [ ] [Federal and Indian Accounts Receivable and Debt Collection.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225918/Federal.and.Indian.Accounts.Receivable.and.Debt.Collection.pptx)
- [ ] [Federal and Indian Billing.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225920/Federal.and.Indian.Billing.pptx)
- [ ] [Form ONRR-4430 (P&R).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225921/Form.ONRR-4430.P.R.pptx)
- [ ] [Form-2014 Basic Reporting Principles.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225922/Form-2014.Basic.Reporting.Principles.pptx)
- [ ] [Liquid Verification System (LVS) and Gas Verification System (GVS).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225924/Liquid.Verification.System.LVS.and.Gas.Verification.System.GVS.pptx)
- [ ] [Missing Production Reports.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225926/Missing.Production.Reports.pptx)
- [ ] [OGOR Reporting Errors.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225928/OGOR.Reporting.Errors.pptx)
- [ ] [ONRR Compliance Overview.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225929/ONRR.Compliance.Overview.pptx)
- [ ] [ONRR Data Requests.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225930/ONRR.Data.Requests.pptx)
- [ ] [ONRR Enforcement.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225931/ONRR.Enforcement.pptx)
- [ ] [ONRR-4054 Oil and Gas Operations Report (OGOR).pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225932/ONRR-4054.Oil.and.Gas.Operations.Report.OGOR.pptx)
- [ ] [Royalty Reporting for eCommerce and Electronic Tools.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225934/Royalty.Reporting.for.eCommerce.and.Electronic.Tools.pptx)
- [ ] [Solid Minerals Compliance.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225935/Solid.Minerals.Compliance.pptx)
- [ ] [Solid Minerals Opening, Form ONRR-4444, Payor Codes, and EMARF.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225936/Solid.Minerals.Opening.Form.ONRR-4444.Payor.Codes.and.EMARF.pptx)
- [ ] [SolidMineral Leases, Sales Summary, Sales Contracts & Facility Data, Handbook.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225938/SolidMineral.Leases.Sales.Summary.Sales.Contracts.Facility.Data.Handbook.pptx)
- [ ] [Solids AR Basics.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15225939/Solids.AR.Basics.pptx)

**Comment by jasonDSTS** [comment]
This email has no instructions?

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, May 6, 2024 2:17 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Documents (Issue #3104)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



  *    Solids Billing.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225941/Solids.Billing.pptx>
  *    Solids Valuation Sodium and Potassium.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225942/Solids.Valuation.Sodium.and.Potassium.pptx>
  *    1989 Federal and Indian Coal Royalty Rule Reporter Valuation Training.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225912/1989.Federal.and.Indian.Coal.Royalty.Rule.Reporter.Valuation.Training.pptx>
  *    2014 Adjustments and Recoupments.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225913/2014.Adjustments.and.Recoupments.pptx>
  *    2014 Reporting Errors.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225916/2014.Reporting.Errors.pptx>
  *    Commonly Used 2014 Transaction Codes.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225917/Commonly.Used.2014.Transaction.Codes.pptx>
  *    Federal and Indian Accounts Receivable and Debt Collection.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225918/Federal.and.Indian.Accounts.Receivable.and.Debt.Collection.pptx>
  *    Federal and Indian Billing.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225920/Federal.and.Indian.Billing.pptx>
  *    Form ONRR-4430 (P&R).pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225921/Form.ONRR-4430.P.R.pptx>
  *    Form-2014 Basic Reporting Principles.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225922/Form-2014.Basic.Reporting.Principles.pptx>
  *    Liquid Verification System (LVS) and Gas Verification System (GVS).pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225924/Liquid.Verification.System.LVS.and.Gas.Verification.System.GVS.pptx>
  *    Missing Production Reports.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225926/Missing.Production.Reports.pptx>
  *    OGOR Reporting Errors.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225928/OGOR.Reporting.Errors.pptx>
  *    ONRR Compliance Overview.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225929/ONRR.Compliance.Overview.pptx>
  *    ONRR Data Requests.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225930/ONRR.Data.Requests.pptx>
  *    ONRR Enforcement.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225931/ONRR.Enforcement.pptx>
  *    ONRR-4054 Oil and Gas Operations Report (OGOR).pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225932/ONRR-4054.Oil.and.Gas.Operations.Report.OGOR.pptx>
  *    Royalty Reporting for eCommerce and Electronic Tools.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225934/Royalty.Reporting.for.eCommerce.and.Electronic.Tools.pptx>
  *    Solid Minerals Compliance.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225935/Solid.Minerals.Compliance.pptx>
  *    Solid Minerals Opening, Form ONRR-4444, Payor Codes, and EMARF.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225936/Solid.Minerals.Opening.Form.ONRR-4444.Payor.Codes.and.EMARF.pptx>
  *    SolidMineral Leases, Sales Summary, Sales Contracts & Facility Data, Handbook.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225938/SolidMineral.Leases.Sales.Summary.Sales.Contracts.Facility.Data.Handbook.pptx>
  *    Solids AR Basics.pptx<https://github.com/DOI-ONRR/onrr.gov-site/files/15225939/Solids.AR.Basics.pptx>

**Comment by lpgoldstein** [comment]
@jasonDSTS This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/training

**Comment by jasonDSTS** [comment]
Thank you please publish.

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, May 6, 2024 5:04 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Documents (Issue #3104)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/training

**Comment by lpgoldstein** [comment]
@jasonDSTS They should all be live. Please check carefully. https://onrr.gov/references/training
