### ISSUE TITLE
Replace Reporter Training Presentations

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3107]
At https://onrr.gov/references/training, please replace the 2 presentations: Basic Leases and Agreements, Federal and Basic Leases and Agreements, Indian with the one presentation attached, Basic Leases and Agreements.  
[Basic Leases and Agreements.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15262772/Basic.Leases.and.Agreements.pptx)

Thanks, Jason

**Comment by cthomasONRR** [comment]
@jasonDSTS Good morning,
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/training
Please review and give us approval to go live.
Thanks,
Christine

**Comment by jasonDSTS** [comment]
Looks great please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 9, 2024 7:34 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Replace Reporter Training Presentations (Issue #3107)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Good morning,
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/training
Please review and give us approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS This is now live. Closing issue. Thanks!
