### ISSUE TITLE
Replace Reporter Training Presentations 

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3109]
Please replace reporter training presentations at:
https://dev-onrr-frontend.app.cloud.gov/references/training
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/112106249/6791c614-890b-454a-903c-57a554479bf2)

With the attached updates.

Thanks,

Jason
[Solids 1989 Federal and Indian Coal Royalty Valuation Rule.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15263146/Solids.1989.Federal.and.Indian.Coal.Royalty.Valuation.Rule.pptx)
[Solids Sodium and Potassium.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15263148/Solids.Sodium.and.Potassium.pptx)

**Comment by cthomasONRR** [comment]
@jasonDSTS These updated docs are in dev. Rob is working on getting corrected docs for us. https://dev-onrr-frontend.app.cloud.gov/references/training
