### ISSUE TITLE
Input top task #5 for digitization and self-service optimization for IDEA Act 

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3112]
OMB has released Action 5 for M-23-22, Delivering a Digital-First Public Experience. Action 5 is focused on identifying top tasks to help inform opportunities for digitization and self-service optimization. Each bureau has its own spreadsheet for completing this action, located in the   “Action 5 Top Tasks” folder on the DOI Customer and Digital Experience SharePoint site. Please review the   instructions before completing your submission as they give more details about each step of the request as well as definitions and examples.

**Comment by AlexandracmONRR** [comment]
I drafted approximately 10 tasks that we can use as a starting point to discuss and move forward with.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR @lpgoldstein - i've added you to this task for you to review the spreadsheet that we hope will be filled out. I've left a comment in Column D for some additional help in filling out.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR . @lpgoldstein and I reviewed. We added content in Column D, additional service items, an additional column for whether the service is informational or task-based, and an additional column for which website the service is located.
