### ISSUE TITLE
Study 01 Bias Reduction Activity

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3116]
watch this video on [Trauma Informed UXR ](https://www.youtube.com/watch?v=xl2uVJir_80)

**Comment by eelzi-ONRR** [comment]
Bias Reduction Activity: watch this video on Trauma Informed UXR

**Comment by eelzi-ONRR** [comment]
@lpgoldstein and @cthomasONRR if you can't get to this until next sprint that's fine since your involvement in the interviews won't happen until early June

**Comment by cthomasONRR** [comment]
I watched the Trauma Informed UXR video.

**Comment by lpgoldstein** [comment]
Done

**Comment by eelzi-ONRR** [comment]
Done. @AlexandracmONRR, you can close the issue after you watch it.
