### ISSUE TITLE
Modify Information on ONRR.gov Contacts Page

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3119]
Please edit contact information.  Changes highlighted at: 

https://doimspp.sharepoint.com/:x:/s/NRRD/ESwIhf6_I6hKjNDHFsPUpIsBuUYgyr4mA1mf9EzVtFNzGw?e=4%3APD43GM&CID=edc9d20c-bec9-daf8-2e44-0b8506cc001c

Thanks,

Jason

**Comment by AlexandracmONRR** [comment]
Hi @jasonDSTS - thank you for your submission. Please review the requested changed on the [dev site](https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts). If it all looks good, please send your approval and I will post live.

**Comment by AlexandracmONRR** [comment]
Approved via email.
