### ISSUE TITLE
Please Add the Attached Training Presentation to ONRR.gov

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3128]
Please Add the Attached Training Presentation to [ONRR.gov](https://onrr.gov/references/training) under Royalty Valuation Training Presentations
[Indian Index Zone Valuation.pptx](https://github.com/DOI-ONRR/onrr.gov-site/files/15340767/Indian.Index.Zone.Valuation.pptx)

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/112106249/973e3420-fab5-4887-9a63-3312b03855db)

**Comment by jasonDSTS** [comment]
Anything you can do to expedite is appreciated.  I missed this one and the class is in session.  Thanks, JLR

**Comment by cthomasONRR** [comment]
@jasonDSTS 

This is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/training 
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/9aec61d7-07d9-4b0f-ba35-abc8fa1d1b12)

Please review and give us approval to go live. Thanks!

**Comment by jasonDSTS** [comment]
Awesome!  Please go live, THANK YOU!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 16, 2024 2:40 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Add the Attached Training Presentation to ONRR.gov (Issue #3128)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

This is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/training
image.png (view on web)<https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/9aec61d7-07d9-4b0f-ba35-abc8fa1d1b12>

Please review and give us approval to go live. Thanks!

**Comment by cthomasONRR** [comment]
@jasonDSTS Great! It's now live! https://www.onrr.gov/references/training

**Comment by jasonDSTS** [comment]
[cid:1ca943ea-7ad3-42df-a567-eb43ca1cb13f]


Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Roach, Jason L (Federal)
Sent: Thursday, May 16, 2024 2:43 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Subject: RE: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Add the Attached Training Presentation to ONRR.gov (Issue #3128)

[heart]         Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 16, 2024 8:43:22 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Add the Attached Training Presentation to ONRR.gov (Issue #3128)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Great! It's now live! https://www.onrr.gov/references/training

**Comment by jasonDSTS** [comment]
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/112106249/9921f358-5bed-453c-8cd5-f3b2879955a2)

**Comment by jasonDSTS** [comment]
Sorry probably everybody went to it at once

**Comment by cthomasONRR** [comment]
The link is working on the live site now! Closing issue!

**Comment by jasonDSTS** [comment]
[heart]         Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 16, 2024 8:43:22 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Add the Attached Training Presentation to ONRR.gov (Issue #3128)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Great! It's now live! https://www.onrr.gov/references/training
