### ISSUE TITLE
Test Directus extensions in preview

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/onrr.gov-site#3142]
With all the refactoring for the updated editor and extension build automation, all extensions need to be thoroughly tested in dev.

The new ONRR editor should be thoroughly tested for card blocks, tab blocks, and content blocks. All plugins should be validated, with special attention on the following:
- [ ] Image upload
- [ ] Inline link autocomplete
- [ ] Table
- [ ] Lists (new version supports nesting)
- [ ] Text color (inline)

Endpoints:
- [ ] document
- [ ] reporter-letters
- [ ] press-releases
- [ ] unbundling

Hooks:
- [ ] ibmp
- [ ] index-zones
- [ ] indian-gas-major-portion
- [ ] nymex

Jeff will coordinate a time for deploying the changes to dev for testing.

**Comment by cthomasONRR** [comment]
Christine's checklist:

- [ ] Image upload
- [ ] Inline link autocomplete
- [ ] Table
- [ ] Lists (new version supports nesting)
- [ ] Text color (inline)

Endpoints:
- [ ] document
- [ ] reporter-letters
- [ ] press-releases
- [ ] unbundling

Hooks:
- [ ] ibmp
- [ ] index-zones
- [ ] indian-gas-major-portion
- [ ] nymex

**Comment by eelzi-ONRR** [comment]
I tested the text editor and endpoints, but no the hooks since I think you and Christine are working on them. 
Also tested accordions, deep nesting, and changing link targets. All worked great!

@greensomes - My one suggestion is to add black to the color palette. So that if we change text to a color we can easily change it back to black if we want.

**Comment by AlexandracmONRR** [comment]
I've tested the different blocks and the first set of test elements. It is working great! Other than what Christine and Erin said, I have nothing to add.

**Comment by lpgoldstein** [comment]
I'm going to close this one. Also tested. I can't get the color green to work for me but will keep trying.
