### ISSUE TITLE
IDEA Act Task 5/6 - request the inventorying or ONRR public services

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3146]

**Comment by AlexandracmONRR** [comment]
@cthomasONRR @lpgoldstein - I sent you the link (can also find [draft word doc here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Admin/Digital%20Experience/Data-Call-DX/DX-Action5-InternalDataRequest/ONRR-DataRequestInternal-EmailDraft.docx?d=wc86fcd05b73d4357be4a32a5f29049b7&csf=1&web=1&e=bogEBp)) for your review of the email request to different ONRR folks, asking them to fill out the spreadsheet. 

Make any edits or comments needed... thank you!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I put all my edits in TrackChanges, and am now out of the doc.

**Comment by AlexandracmONRR** [comment]
Emails sent to points of contact on 6/4

**Comment by AlexandracmONRR** [comment]
Scheduled check in with ODDD on 6/12 for top task prioritization.

**Comment by AlexandracmONRR** [comment]
Submitted on 6/14. May require some follow-up after meeting with Cody on 6/18.
