### ISSUE TITLE
Clarification/prep of Indian handbook issue

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#3148]
Go through documentation and organize/understand

**Comment by cthomasONRR** [comment]
We got clarification from Jodie!

- We will add the new tab as seen in the image below.
- We will repurpose the existing Indian Payor Handbook page to be "Indian Valuation Resources".
    - We will review the oil section to make sure it matches the new document.
    - We will add new tabs/sections for all the new gas content.
- We will replace all the old IPH links with the new/repurposed webpage.

![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/a1374bab-c8b9-494b-a348-585b116a83d0)

**Comment by cthomasONRR** [comment]
We will make these updates in the preview site, but will wait to make major changes in the preview site until Jeff comes back from vacation. I let Jodie know and she's ok with this.

@lpgoldstein I think we can close this issue. We have a solid plan and can start prepping with making new issues. Thanks.
