### ISSUE TITLE
Please replace the existing document, Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3152]
Please replace the existing document, Federal Onshore Terminable Leases, sorted by due date, located at:

https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references

with the attached Excel file. Please also change the Updated date to 6/3/2024.

Thanks,
Jason
[20240603.xlsx](https://github.com/user-attachments/files/15535884/20240603.xlsx)

**Comment by lpgoldstein** [comment]
@jasondsts onrr.gov is partially down so I'll update as soon as it's back up.

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, June 3, 2024 5:06:02 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the existing document, Federal Onshore Terminable Leases (Issue #3152)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> onrr.gov is partially down so I'll update as soon as it's back up.

**Comment by lpgoldstein** [comment]
@jasonDSTS ready for your review https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by jasonDSTS** [comment]
Looks good please publish.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, June 3, 2024 12:13 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the existing document, Federal Onshore Terminable Leases (Issue #3152)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> ready for your review https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, June 3, 2024 7:54:04 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the existing document, Federal Onshore Terminable Leases (Issue #3152)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #3152<https://github.com/DOI-ONRR/onrr.gov-site/issues/3152> as completed.
