### ISSUE TITLE
Update Interest rates and calculator

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3155]
Hello,

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas please make the following updates:
Add a new line at the top of the late payments & underpayments table for Period 7/1/2024-9/30/2024. Oil and gas remained the same at 8%.

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal please make the following updates:
Add a new line at the top of the late payment & underpayment table for period 7/1/2024-9/30/2024. Solid's remained the same at 4%.

Replace the Interest Calculator excel file at https://onrr.gov/paying/interest?tabs=interest-calculator with the attached below:

[Interest_Calculator_Master.xlsx](https://github.com/user-attachments/files/15566128/Interest_Calculator_Master.xlsx)

Thanks so much!

**Comment by lpgoldstein** [comment]
@Sheetsj https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal ready for your review

**Comment by Sheetsj** [comment]
Everything looks good! Thank you :)

**Comment by lpgoldstein** [comment]
https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas It's live @Sheetsj

**Comment by Sheetsj** [comment]
Perfect thank you!
