### ISSUE TITLE
Pick colors for link editor editor

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3156]
Discuss and then provide Jeff with colors to put in the inline link editor. 

Use:
https://designsystem.digital.gov/utilities/color/

https://revenuedata.doi.gov/patterns/visual-styles/color

Team's folder

**Comment by AlexandracmONRR** [comment]
https://app.axure.cloud/app/project/mjf0mg/preview/lyayzn

**Comment by AlexandracmONRR** [comment]
https://github.com/DOI-ONRR/onrr.gov-site/wiki/Content-guide

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR @cthomasONRR @lpgoldstein @greensomes - here are some proposed colors that include some colors that are already a part of the onrr.gov website and some that are proposed from USWDS utilities. 

Please let me know which options you like or don't like. Also, let me know if you think we are missing a colors!

Thank you!

<img width="736" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDQ5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7c4cfaf8a4e0d2dfe2e5a440bf2ac44449aa879/image.png" alt="image.png" />

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I don't really have a preference in the colors. As long as the pass accessibility, I'm game. I don't think onrr.gov has a dark mode yet, so not sure it's worth adding options H-K just yet. Thanks for compiling!

**Comment by eelzi-ONRR** [comment]
We definitely need the black and whatever blue is currently used in the text editor - not sure what the hex# is for that. I like E for the error color and maybe option C for another option. Aesthetically I like G more than C but I think we should be moving toward USWDS when possible with new design decisions.

**Comment by eelzi-ONRR** [comment]
We definitely need the black and whatever blue is currently used in the text editor - not sure what the hex# is for that. I like E for the error color and maybe option C for another option. Aesthetically I like G more than C but I think we should be moving toward USWDS when possible with new design decisions.

**Comment by eelzi-ONRR** [comment]
If that shade is accessible and readable with our fonts and sizes then I'm fine with it - it looks a little light but that might be this particular font. Or I'm fine with the orange too

**Comment by AlexandracmONRR** [comment]
Okay, here are the colors from our discussion:

#000000 - Black
#000051 - Dark Blue (Headings and clicked link text)
#0076A3 - Light Blue (unclicked link text)
#D83933 - Red Error
#C05500 - Orange Alert
#538200 - Green Other Content

#EBEBED - Light gray (_potential if needed for footer edits_)

**Comment by eelzi-ONRR** [comment]
I propose we only keep colors in the text editor that we will use for text content in the CMS. The light gray is part of the css and the footer is updated in VSC with the css applied, so we will never need to use the text editor to update the footer

**Comment by eelzi-ONRR** [comment]
Same for the link text - that's part of the css. I proposed we only put a single blue in the text editor so there is never confusion about which one to use. We need it for instances like this: https://onrr.gov/references/valuation/processed-gas-example?tabs=sample-statement, but not for links.

**Comment by AlexandracmONRR** [comment]
Okay, here is the list:

#000000 - Black
#1A22FE - Blue
#D83933 - Red Error
#C05500 - Orange Alert
#538200 - Green Other Content

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - any last thoughts or changes before I let Jeff know about this color list?

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR Nope - this list looks good to me!

**Comment by AlexandracmONRR** [comment]
Added to CMS editor on 6/11/24.
