### ISSUE TITLE
Update May NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3161]
Good afternoon,

Please update the May NYMEX prices on onrr.gov according to the attached spreadsheet.

Thanks,
Sean

@sudarr
[NYMEX052024.xlsx](https://github.com/user-attachments/files/15570471/NYMEX052024.xlsx)

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices It's live!
