### ISSUE TITLE
Ensure markup documents contain well-formed elements

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3163]
OCIO 2024 report

Instances: 36
Severity: 6
Priority: 1 (lowest)
Occurrence: <1%

Cause/Note:

- This SPAN has an id attribute of 'docs-internal-guid-28c214a1-e5e0-1ec8-f292-ee50a89ab429', which is not unique in the same DOM

All instance of this issue are on the Information Quality page: https://onrr.gov/government-initiatives-laws?tabs=information-quality

**Comment by greensomes** [comment]
This was resolved in issue #2706
