### ISSUE TITLE
Review Osage pricing page language

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3172]

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein I reviewed the content given to us in the Excel located here:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/990fd371-5080-49ff-b80c-6c01e310f3be)

I went into the CMS preview site and created the tables on the "/about/test-page" to see how they will display. (I created an issue for Jeff to refine the text alignment within table columns.) I also refined some of the intro language to the tables, and will further refine once the new reg cites are published in the FR.

I made sure their small amount of intro text is at grade 10. I also potentially found an error where they want to cite a FR publication from June 23, 2011. I think I found the correct pub, but it's from June 28, 2011.

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR I applied the comments I found in the "Osage Price Tab Language" section. Thanks for reviewing. If there are no more comments, I will close this issue.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks good! I added a couple comments on the Osage Tab language to what has already been commented on. Thanks for working on this!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein Thanks, I incorporated edits, and made sure autosave was on! Closing this issue.
