### ISSUE TITLE
Tables - add text alignment options to table columns & cards

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3179]
I'm playing with the new table editor within preview, and am noticing some issues with text alignment that could be improved. 

Is there a way we can add text alignment so that the table column formatting is more consistent?

Here's an example:
<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelpzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c2aa74c3ade4fd8cde2278e82f84e0eed57f801/image.png" alt="image.png" />

When creating new cards, there is no way to center-align right now:
![image](https://github.com/user-attachments/assets/de47c146-818e-4df0-9998-bd018c56ae02)

**Comment by greensomes** [comment]
Digging into the code to see how table alignment works, I've observed that the feature is not very sophisticated. The alignment tune tool applies the same alignment to every table cell, so it's generally useless. However, there is logic in the frontend rendering that right aligns text that is determined to be numeric. The multiplier value in the example screenshot above should be right aligned. I'll look at the logic and fix the apparent bug.

**Comment by greensomes** [comment]
Text blocks now have the alignment tool available.
