### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – June 2024

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#3182]
Please replace the existing file located at: [https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freferences%2Freference-lists%3Ftabs%3Dleases-agreement-numbers%2Ccross-reference-lease-to-agreement-numbers&data=05%7C02%7Cstacey.kaiser%40onrr.gov%7C42af7e9ae6e94ea2710d08dc5efe73fd%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638489694161728105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HxnpufFTSzOQQiFn52y1lWgSaYpPSFA99tjT8BedulI%3D&reserved=0) titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “June 2024 Lease Agreement XREF.txt" and "June 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 6/18/2024.
[June 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/15891107/June.2024.Lease.Agreement.XREF.xlsx)

[June 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/15891114/June.2024.Lease.Agreement.XREF.txt)
[June 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/15891115/June.2024.Lease.Agreement.XREF.txt)

**Comment by lpgoldstein** [comment]
@StaceyKaiser Ready for your review https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by StaceyKaiser** [comment]
@lpgoldstein the file looks good and can be moved to the live site. Thanks!

**Comment by lpgoldstein** [comment]
@StaceyKaiser It is live! https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
