### ISSUE TITLE
Automated and manual testing of top 10 downloads

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3185]
Required for annual govt-wide assessment. Due July 31

**Comment by cthomasONRR** [comment]
@eelzi-ONRR This is ready for your review. I probably put in more comments than needed, but wanted to explain what I was seeing in case it didn't fully meet a WCAG element.

**Comment by cthomasONRR** [comment]
Fixed 39 instances of broken links, and fixes are live. Content audit is updated.

**Comment by eelzi-ONRR** [comment]
Thank you so much for your work on this! I reviewed and don't have any questions. I think the comments you put in are great and we can eventually use this to help justify expanding the ONRR document policy to require more manual checks
