### ISSUE TITLE
Minerals Production Reporter Handbook Changes

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3187]
- Please replace the existing Chapter 5 at:
https://onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=chapters
with the attached Chapter 5.

- Please replace the Appendix I at:
https://onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information
with the attached Appendix I.

- Please replace the Minerals Production Reporter Handbook at:
https://onrr.gov/references/handbooks
with the attached Minerals Production Reporter Handbook.

[Minerals Production Reporter Handbook Appendix I Disposition adjustment Codes and Descriptions.pdf](https://github.com/user-attachments/files/15991570/Minerals.Production.Reporter.Handbook.Appendix.I.Disposition.adjustment.Codes.and.Descriptions.pdf)
[Minerals Production Reporter Handbook Combined -508 pass.pdf](https://github.com/user-attachments/files/15991571/Minerals.Production.Reporter.Handbook.Combined.-508.pass.pdf)
[Minerals Production Reporter Handbook Chapter 5.pdf](https://github.com/user-attachments/files/15991572/Minerals.Production.Reporter.Handbook.Chapter.5.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS 

These 3 documents are updated on the dev site. Please review and give us approval to go live.

- https://dev-onrr-frontend.app.cloud.gov/references/handbooks
- https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=chapters
- https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Thanks,
Christine

**Comment by jasonDSTS** [comment]
Hi Christine,

The changes look good.  Please go live.

Thanks for all you do!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, June 26, 2024 9:52 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Minerals Production Reporter Handbook Changes (Issue #3187)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

These 3 documents are updated on the dev site. Please review and give us approval to go live.

  *   https://dev-onrr-frontend.app.cloud.gov/references/handbooks
  *   https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=chapters
  *   https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS 

Great! These updates are now live:

- https://www.onrr.gov/references/handbooks
- https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=chapters
- https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Thanks,
Christine

**Comment by jasonDSTS** [comment]
[0]     Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, June 26, 2024 4:15:39 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Minerals Production Reporter Handbook Changes (Issue #3187)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #3187<https://github.com/DOI-ONRR/onrr.gov-site/issues/3187> as completed.

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, June 26, 2024 4:15:39 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Minerals Production Reporter Handbook Changes (Issue #3187)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #3187<https://github.com/DOI-ONRR/onrr.gov-site/issues/3187> as completed.
