### ISSUE TITLE
Please Update Royalty Contacts

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3195]
Please update Oil and Gas Royalty Contacts at:
https://onrr.gov/about/contact

to reflect highlighted changes on the Royalty tab of the SharePoint spreadsheet located at:

https://doimspp.sharepoint.com/:x:/s/NRRD/ESwIhf6_I6hKjNDHFsPUpIsBuUYgyr4mA1mf9EzVtFNzGw?e=4%3APD43GM&CID=edc9d20c-bec9-daf8-2e44-0b8506cc001c

Thanks!

Jason

**Comment by lpgoldstein** [comment]
@jasonDSTS Ready for your review https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

**Comment by jasonDSTS** [comment]
Looks good, please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, July 2, 2024 12:37 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update Royalty Contacts (Issue #3195)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Ready for your review https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

**Comment by lpgoldstein** [comment]
@jasonDSTS live!

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, July 2, 2024 7:04:22 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update Royalty Contacts (Issue #3195)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> live!
