### ISSUE TITLE
Make all existing and new links open in the same tab (non-document links)

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3196]
For ALL non-document links- internal to onrr.gov AND external sites open in the same tab.

**Comment by cthomasONRR** [comment]
Add external indicators to buttons as well

**Comment by AlexandracmONRR** [comment]
This one was in preview, but Jeff has to re-run the conversion.

**Comment by greensomes** [comment]
@cthomasONRR, I ran the conversion in preview again. Please review the links in preview and let me know if you find any that aren't working as expected. Thanks!

**Comment by greensomes** [comment]
The data conversion for editor links has been applied to the preview database.

**Comment by cthomasONRR** [comment]
@greensomes I'm checking in preview right now and things look good! All links I'm testing are opening in the same tab- yay!!! I also really love the external link indicator!

The only thing I'm seeing right now is adding the external link indicator to buttons (eCommerce, WebCenter Portal, EMARF, Solids P&R Tool, Pay.gov). But I think we can release what's in preview now and I can make a new issue to add the indicator to the buttons.

**Comment by greensomes** [comment]
@cthomasONRR, since there are only a few buttons to change, I can add the external link class via the editor and we can publish via the flow. Besides the home page, what pages are the buttons on?

**Comment by cthomasONRR** [comment]
Most of these are the same cards but here are all locations:

- [ ] onrr.gov/getting-started/new-reporter-checklist?tabs=oil-gas-production
- [ ] https://www.onrr.gov/getting-started/new-reporter-checklist?tabs=oil-gas-revenue
- [ ] https://www.onrr.gov/getting-started/new-reporter-checklist?tabs=solid-minerals
- [ ] https://www.onrr.gov/getting-started/new-reporter-checklist?tabs=geothermal
- [ ] https://www.onrr.gov/getting-started/system-access?tabs=setting-up-access
- [ ] https://www.onrr.gov/getting-started/system-access?tabs=troubleshooting
- [ ] onrr.gov/reporting
- [ ] onrr.gov/reporting/production?tabs=file-reports
- [ ] onrr.gov/reporting/production?tabs=new-reporter-checklist
- [ ] onrr.gov/reporting/revenue?tabs=new-reporter-checklist
- [ ] onrr.gov/reporting/solids?tabs=file-reports
- [ ] https://www.onrr.gov/reporting/solids?tabs=forms
- [ ] https://www.onrr.gov/reporting/solids?tabs=new-reporter-checklist
- [ ] https://www.onrr.gov/reporting/geothermal?tabs=file-reports
- [ ] https://www.onrr.gov/reporting/geothermal?tabs=new-reporter-checklist
- [ ] onrr.gov/references/forms?tabs=system-access
- [ ] onrr.gov/references/forms?tabs=solid-minerals-reporting
- [ ] onrr.gov/paying/payment-options?tabs=paygov
- [ ] onrr.gov/paying/payment-options?tabs=rent-payments
- [ ] onrr.gov/paying/payment-options?tabs=renewable-energy,bid-deposit-options
- [ ] onrr.gov/paying/payment-options?tabs=renewable-energy,first-years-rental-payments
- [ ] onrr.gov/about/contact/getting-started-contacts?tabs=troubleshooting
- [ ] onrr.gov/about/contact/system-access-contacts?tabs=troubleshooting
- [ ] onrr.gov/about/contact/rent-contacts?tabs=troubleshooting

**Comment by greensomes** [comment]
Note to self: for prod conversion run, execute the update-buttons.py (update_anchor_tag, update_button) then add-usa-link-class.py.
