### ISSUE TITLE
Update June NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [DOI-ONRR/onrr.gov-site#3197]
Good morning,

Please update the June NYMEX prices on onrr.gov according to the attached spreadsheet.

Thanks,
Sean

@sudarr
[NYMEX062024.xlsx](https://github.com/user-attachments/files/16086913/NYMEX062024.xlsx)

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by boices** [comment]
That's perfect--thank you!

**Comment by lpgoldstein** [comment]
@boices live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
