### ISSUE TITLE
Indian Index Zone prices for July 2024

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3198]
Good afternoon! The Indian Index Zone prices for July are ready to be posted on ONRR.gov. I will send a separate email with data after I submit this ticket. Thank you very much and have a nice July 4th holiday!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Everything looks great!

Quick question: would it be better (or better serve the purpose of using GitHub) if we responded to updates within GitHub, rather than replying to this email?

From: lpgoldstein ***@***.***>
Sent: Wednesday, July 3, 2024 2:52 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Indian Index Zone prices for July 2024 (Issue #3198)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by lpgoldstein** [comment]
@penvosej This is live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

I see your email responses within GitHub so whatever is easier for you is fine for us. The only thing I could think of is that there could be a slight delay by using email instead of commenting directly within the issue.

**Comment by penvosej** [comment]
Okay. To minimize emails (at least for me), I'll start replying within GitHub. I'll also suggest it to my teammates if they don't already do so. Thanks for the info and for getting the prices up so quickly!

From: lpgoldstein ***@***.***>
Sent: Wednesday, July 3, 2024 3:10 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Indian Index Zone prices for July 2024 (Issue #3198)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://github.com/penvosej> This is live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

I see your email responses within GitHub so whatever is easier for you is fine for us. The only thing I could think of is that there could be a slight delay by using email instead of commenting directly within the issue.

-
