### ISSUE TITLE
Please Replace Appendix I for Interactive Minerals Production Reporter Handbook

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3203]
Please replace Appendix I, located at:

https://onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

with the attached pdf.

[Minerals Production Reporter Handbook Appendix I Disposition Adjustment Codes and Descriptions.pdf](https://github.com/user-attachments/files/16168084/Minerals.Production.Reporter.Handbook.Appendix.I.Disposition.Adjustment.Codes.and.Descriptions.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS 

This update is in dev:
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Please review and give us your approval to go live.
Thanks,
Christine

**Comment by jasonDSTS** [comment]
Hi Christine!

This looks good, please publish.

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, July 10, 2024 1:47 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Appendix I for Interactive Minerals Production Reporter Handbook (Issue #3203)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>

This update is in dev:
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Please review and give us your approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS Great! This is now live! https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Thanks,
Christine

**Comment by jasonDSTS** [comment]
You're the best, Thanks!

J
Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, July 10, 2024 1:57 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Appendix I for Interactive Minerals Production Reporter Handbook (Issue #3203)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Great! This is now live! https://www.onrr.gov/references/handbooks/minerals-production-reporter-handbook?tabs=supplemental-information

Thanks,
Christine
