### ISSUE TITLE
Review in-line link editor and document updates in dev

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3204]
@greensomes Is moving all the updates from preview to dev. Once in dev, let's review again before going live.

**Comment by cthomasONRR** [comment]
So far I checked dev content in Getting Started and Reporting with the live site. All content is present, so that prior issue is resolved. 

I'm now testing functionality on the test page, and the only major thing I'm noticing is that the NYMEX files aren't showing in the link autocomplete. We rarely if ever have these excel files outside of the NYMEX collection table, so just wanted to bring this up in case they are supposed to show. https://dev-onrr-frontend.app.cloud.gov/about/test-page

**Comment by cthomasONRR** [comment]
Another minor difference that really doesn't affect anything is the way the list bullets display in the CMS versus Dev. I'm ok with these minor differences, just want to make sure everyone else is.

CMS:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/aa0b5db4-9f97-479a-810d-329751547d41)

Dev Site:
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/72526208/1b333952-8bbf-47d3-90f9-e0a99c499879)

**Comment by greensomes** [comment]
I see. I need to look into and adjust how the nested ordered lists are rendered. IMO, this is a low priority since we don't currently have content structured like this. I'll create an issue to track it.

**Comment by greensomes** [comment]
I remember you all mentioning it, but I did not look into what we can do about it with Editor.js. I believe the standard WYSIWYG was better at handling it. I'll take a look at the Editor.js docs to see if there is a plugin or configuration that can be applied to better handle it.

**Comment by eelzi-ONRR** [comment]
I take that back - it didn't keep the same font when I copied from a word doc, but it changed it to a serifed font we don't use at all instead of the Lato that we do

**Comment by eelzi-ONRR** [comment]
Aside from that and the nested list items Christine pointed out, everything else looks good!

**Comment by AlexandracmONRR** [comment]
Agreed that everything is looking good. I haven't been able to find anything wrong!

In terms of the conversation about copy/pasting text with other formatting. Maybe there is a plugin function that would clear formatting altogether and set it as a basic text formatting. (similar to what Word has)

**Comment by lpgoldstein** [comment]
I haven't found anything either.
