### ISSUE TITLE
Review cloud.gov service agreement draft and determine if we need to up our usage for FY25

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3205]
Sent via email on June 28: 

Hi all,
Your office's agreement with Cloud.gov expires October 31, 2024. For us to continue providing you service, we will need to put a new agreement in place. I have started the process by attaching a draft statement of work for the coming 12 months for your review. This is at your current usage and access levels. Additionally, I've attached a cost estimator to show a year of usage at your current levels.
Can you please provide:
•	TAS accounting information
•	PoCs for Agency, Programming, and Funding
•	**Any updates you'd like to make to your current access level, GB usage, and/or adding any additional support hours.**
Once we receive this information from you, we can begin drafting the rest of the renewal paperwork. Please let me know if you have any questions.

We might want to consider this in conjunction with #3180 in case we want to budget for more GB next year

**Comment by eelzi-ONRR** [comment]
Jeannette contacted me today asking if we had reviewed this yet. I told her the time line for the new supervisor and she's okay to wait until they are in place. But this should be prioritized once the new supervisor is selected.

**Comment by lpgoldstein** [comment]
No changes and responded to email
