### ISSUE TITLE
dev Validation issues

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/onrr.gov-site#3206]
Please document any issues encountered in dev post-deployment of the ONRR Editor (w/inline link editor) here.

**Comment by AlexandracmONRR** [comment]
Currently, I've been finding that some bullets within cards is missing. I've mainly been checking in the expansion panels. 

I will update this comment as I see more, but wanted to start providing screen shots.

<img width="1058" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e815e5acd2f3e1e7c7a1c9ffeb0326ff427d6ee2/image.png" alt="image.png" />

**Comment by lpgoldstein** [comment]
Yep I'm finding the same things
![image](https://github.com/DOI-ONRR/onrr.gov-site/assets/39419003/f6910203-88a9-457b-9846-312e5ef72cd0)

**Comment by lpgoldstein** [comment]
color contrast on divider bars looks good
