### ISSUE TITLE
Osage page prototype

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3216]
Will use the content Christine worked on. Pending Axure being reinstalled.

**Comment by eelzi-ONRR** [comment]
IT has still not fulfilled my Axure request. Passing on to Alex for next sprint

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @AlexandracmONRR This can be done in the preview site now that it's operational.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR - thank you, but as designers Axure gives us more ability to explore different ideas and it's far less work to make multiple prototypes in Axure than it is to build multiple examples pages in Directus
