### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – July 2024

### ISSUE THREAD

**Issue by Daphnesmum** [DOI-ONRR/onrr.gov-site#3221]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “July 2024 Lease Agreement XREF.txt" and "July 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 7/17/2024.

____________________
[July 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/16266336/July.2024.Lease.Agreement.XREF.txt)
[July 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/16266348/July.2024.Lease.Agreement.XREF.xlsx)
__________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

**Comment by cthomasONRR** [comment]
@Daphnesmum 

This update is on the dev site: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Daphnesmum** [comment]
Peer review has been completed. The files can be moved to the live site. Thank you!

**Comment by cthomasONRR** [comment]
@Daphnesmum 
Great! This update is now live: https://www.onrr.gov/references/reference-lists
Closing issue.
Thanks,
Christine
