### ISSUE TITLE
Add Additional Customer Number Contacts

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3222]
Please update the 3 highlighted lines on the lease & agreement tab of the shared spreadsheet.  We're adding 2 additional contacts to Name Changes, Mergers and New Accounts.

Please also add the 2 new contacts, contact information below, to the below listed pages for the New Reporter Checklists and update the instructions to Email all contacts below, instead of email both contacts below.  I've attached a word document with screenshots, please let me know if you have any questions.

Toni Leveille
Antoinette.leveille@onrr.gov
303-231-3066

Katie Connor
kathryn.q.connor@onrr.gov
303-231-3937

- [x] [New Reporter Checklist | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id)
- [x] [New Reporter Checklist | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=oil-gas-revenue)
- [x] [New Reporter Checklist | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=solid-minerals)
- [x] [New Reporter Checklist | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=geothermal)
- [x] [Oil & Gas Production | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/production?tabs=new-reporter-checklist&panel=get-an-onrr-customer-id)
- [x] [Oil & Gas Revenue | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/revenue?tabs=new-reporter-checklist)
- [x] [Solid Minerals | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/solids?tabs=new-reporter-checklist)
- [x] [Geothermal | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/geothermal?tabs=new-reporter-checklist)

- [x] [Customer Number Contact Update_7-18-24.docx](https://github.com/user-attachments/files/16283511/Customer.Number.Contact.Update_7-18-24.docx)

Thank You
Jessica

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist

**Comment by bowlenj** [comment]
Hello,

The new contact cards look great!  Can the instructions on New Reporter Checklist for Oil & Gas Revenue and Geothermal tabs, for get an ONRR customer ID be updated to read Email all, Oil & Gas Production & Solid Minerals shows all but the other 2 still say both.

New Reporter Checklist | Office of Natural Resources Revenue (cloud.gov)<https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=oil-gas-revenue>
New Reporter Checklist | Office of Natural Resources Revenue (cloud.gov)<https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=get-an-onrr-customer-id&tabs=geothermal>


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, July 18, 2024 10:54 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add Additional Customer Number Contacts (Issue #3222)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> ready for your review: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist

**Comment by lpgoldstein** [comment]
@bowlenj apologies - should be there now.

**Comment by bowlenj** [comment]
It looks great, thank you!  Approved to publish and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, July 18, 2024 1:39 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add Additional Customer Number Contacts (Issue #3222)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> apologies - should be there now.

**Comment by lpgoldstein** [comment]
@bowlenj it's live!

**Comment by bowlenj** [comment]
[like]  Bowlen, Jessica G (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, July 18, 2024 8:27:28 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add Additional Customer Number Contacts (Issue #3222)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> it's live! https://onrr.gov/reporting/revenue?tabs=new-reporter-checklist
