### ISSUE TITLE
Add language to accessibility statement that explicitly says we follow DOI 508 and accessible ICT policies

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3229]
Required by M-24-08 and govt-wide assessment that we have these publicly posted. ONRR mostly follows DOI policies in this area instead of having our own: https://www.doi.gov/ocio/information_management/section-508-policies

Can add to the DOI Section 508 Program section. The DOI accessibility statement has updates in this section that ours don't reflect - we can copy that and add that we use the DOI policies

**Comment by cthomasONRR** [comment]
Updated: https://dev-onrr-frontend.app.cloud.gov/accessibility

**Comment by cthomasONRR** [comment]
@lpgoldstein This is ready for your review. It's already live (https://www.onrr.gov/accessibility), but you can compare to NRRD live for changes made (https://revenuedata.doi.gov/accessibility).
