### ISSUE TITLE
Data tables don't read row headers for each cell

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/onrr.gov-site#3246]
Table cells read the column header for each cell, but not the row header when using a screen reader. Found via ANDI.

For example, the first row of this table, second cell currently reads as "Year 2024". It should read "Oklahoma Zone 1 (OK 1) Year 2024. Cell three should read "Oklahoma Zone 1 (OK 1) Month July", etc.
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW90Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b56d4d3e5b869112189fc5fcc2f6dccfdace91a6/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
This is collection tables (this example is a pricing table).

Must identify all instances, make the change, then test.

**Comment by greensomes** [comment]
This was accomplished by converting the first cell in each row to `<th>`, as modeled in the USWDS. I have applied the change to the following collections:

- Indian Gas Index Zone
- Indian Oil Major Portion (IBMP)
- Indian Gas Major Portion
- Nymex Oil Prices
- Crude Oil Market Centers
- Reporter Letters
- Handbooks
- Rulemakings
- Unbundling
- Late payment interest rates (Oil & Gas, Solids)

Let me know if I've missed anything!
