### ISSUE TITLE
August 2024 Indian Index Zone Prices

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3252]
Hello, web team!  We've finished calculating the Indian Index Zone prices for August and they are ready to be posted on ONRR.gov.  I'll send a separate email with the data right after I submit this.  Thank you!!
@sudarr

**Comment by cthomasONRR** [comment]
@penvosej 
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone
Please review and give us approval to go live.
Thanks,
Christine

**Comment by penvosej** [comment]
Everything looks good! Thanks for taking care of this so quickly!

@sudarr

**Comment by cthomasONRR** [comment]
@penvosej Great, these prices are now live: https://www.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
