### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – August 2024

### ISSUE THREAD

**Issue by aalveari1** [DOI-ONRR/onrr.gov-site#3255]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “Aug 2024 Lease Agreement XREF.txt" and "Aug 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 8/9/2024.

[Aug 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/16563401/Aug.2024.Lease.Agreement.XREF.xlsx)
[Aug 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/16563406/Aug.2024.Lease.Agreement.XREF.txt)

**Comment by cthomasONRR** [comment]
@aalveari1 
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us approval to go live.
Thanks,
Christine

**Comment by aalveari1** [comment]
[like]  Alveari, Anna M (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, August 9, 2024 3:02:28 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Alveari, Anna M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Webpage Update - New Lease Agreement XREF files for onrr.gov – August 2024 (Issue #3255)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@aalveari1<https://github.com/aalveari1>
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us approval to go live.
Thanks,
Christine

**Comment by aalveari1** [comment]
Peer review is complete. The files can be moved to the live site. Thank you!

**Comment by cthomasONRR** [comment]
@aalveari1 Thank you! This update is now live: https://www.onrr.gov/references/reference-lists
