### ISSUE TITLE
Change supervisor in system

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3259]
ODDD team must change their supervisor in DOI Talent and USA Performance (?)

**Comment by lpgoldstein** [comment]
I was able to add everyone in doitalent but not usa performance yet

**Comment by lpgoldstein** [comment]
Okay, I can see everyone in USA Performance so you all should be able to change your supervisor as needed in the systems.

**Comment by cthomasONRR** [comment]
@lpgoldstein Do you know where we need to go within USA Performance? Do we need to create a new FY25 plan in order to change supervisor?

**Comment by cthomasONRR** [comment]
@lpgoldstein 
This might already be updated for us! In USA Performance, go to View Profile > Performance Plans tab. Scroll down and I see Lindsay already assigned 
![image](https://github.com/user-attachments/assets/49617ba7-9c0f-4aa8-92ac-ff5033248de4)
