### ISSUE TITLE
Update Enterprise Services IT Contact Number

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3261]
Please update the Technical Assistance Contact card at the following link - https://onrr.gov/about/contact/system-access-contacts?tabs=contacts

Please remove 303-231-3333 and replace with 1-877-256-6260.

If there are any other places in ONRR.gov that show the 303-231-3333 number please remove it and only show the 1-877-256-6260 number.  The local number has been de-activated and is no longer being used.

Please let me know if you have any questions.

Thank You
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

I captured every instance of the "Password Issues and System Lockouts" card:
https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting

I also found instances with contact cards and updated them:
https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/system-access-contacts?tabs=contacts

I reviewed other sections and think we've captured/updates all instances of the old number.

Please review and give us approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great, thank you!  Approved to push live and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 19, 2024 1:45 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Enterprise Services IT Contact Number (Issue #3261)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj>

I captured every instance of the "Password Issues and System Lockouts" card:
https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting

I also found instances with contact cards and updated them:
https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/system-access-contacts?tabs=contacts

I reviewed other sections and think we've captured/updates all instances of the old number.

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great! These are now live:

- https://www.onrr.gov/getting-started/system-access?tabs=troubleshooting&panel=i-need-to-get-or-re-establish-system-access
- https://www.onrr.gov/about/contact/getting-started-contacts?tabs=contacts
- https://www.onrr.gov/about/contact/system-access-contacts?tabs=contacts

Thanks,
Christine
