### ISSUE TITLE
Add Video Link to Report Electronically Card

### ISSUE THREAD

**Issue by bowlenj** [DOI-ONRR/onrr.gov-site#3262]
Please add this YouTube Login.gov training link, https://www.youtube.com/watch?v=iE-0rkcMPIA, to all Report Electronically cards located in ONRR.gov.  I've listed the pages I know below, please also update any cards I may have missed:

https://dev-onrr-frontend.app.cloud.gov/?tabs=contacts
https://onrr.gov/reporting
https://onrr.gov/reporting/production
https://onrr.gov/reporting/revenue
https://onrr.gov/reporting/solids
https://onrr.gov/reporting/geothermal

This update does not have to wait for Friday as we previously discussed.  Please let me know if you have any questions!

Thank you,
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj I cross-checked with my content audit. The following locations are now updated in dev:

- https://dev-onrr-frontend.app.cloud.gov/
- https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access
- https://dev-onrr-frontend.app.cloud.gov/reporting
- https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=file-reports
- https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=file-reports
- https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=file-reports
- https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=file-reports

Please review, let me know if there are any other locations you would like to add the link, or if we're good to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
That is perfect!  Approved to push live & close!!!!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 19, 2024 3:39 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add Video Link to Report Electronically Card (Issue #3262)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://github.com/bowlenj> I cross-checked with my content audit. The following locations are now updated in dev:

  *   https://dev-onrr-frontend.app.cloud.gov/
  *   https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access
  *   https://dev-onrr-frontend.app.cloud.gov/reporting
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=file-reports
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=file-reports
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=file-reports
  *   https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tabs=file-reports

Please review, let me know if there are any other locations you would like to add the link, or if we're good to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great! All these locations are now live!
