### ISSUE TITLE
Please Update Contact Information

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3264]
Please update contact information (highlighted) located on the Onshore Production and Lease/Agreement tabs located at:

https://doimspp.sharepoint.com/:x:/s/NRRD/ESwIhf6_I6hKjNDHFsPUpIsBuUYgyr4mA1mf9EzVtFNzGw?e=4%3APD43GM&CID=edc9d20c-bec9-daf8-2e44-0b8506cc001c

Thanks,

Jason

**Comment by lpgoldstein** [comment]
@jasonDSTS Is there only one contact change from onshore production?

**Comment by jasonDSTS** [comment]
> @jasonDSTS Is there only one contact change from onshore production?

Yes

**Comment by lpgoldstein** [comment]
@jasonDSTS Ready for your review: 
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by jasonDSTS** [comment]
> @jasonDSTS Ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

Changes look good.  There is an empty contact place between Offshore categories.  Can you remove it?
![image](https://github.com/user-attachments/assets/a2bfb9a0-9209-46b1-8066-7cd4acb8f3b6)

**Comment by lpgoldstein** [comment]
@jasonDSTS https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

Done - there must have been spaces in spreadsheet that caused the empty contact to upload.

**Comment by jasonDSTS** [comment]
@lpgoldstein looks great please go live!

**Comment by lpgoldstein** [comment]
@jasonDSTS Going live now. Should be done in a few minutes. I have to step out but I'll check back by 1 pm. 
https://onrr.gov/about/contact/lease-agreement-contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, August 20, 2024 4:51:24 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update Contact Information (Issue #3264)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Going live now. Should be done in a few minutes. I have to step out but I'll check back by 1 pm.
https://onrr.gov/about/contact/lease-agreement-contacts
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, August 20, 2024 6:40:26 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update Contact Information (Issue #3264)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #3264<https://github.com/DOI-ONRR/onrr.gov-site/issues/3264> as completed.
