### ISSUE TITLE
Complete online quiz for team meeting by Aug 28

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3267]
https://www.16personalities.com/free-personality-test

**Comment by lpgoldstein** [comment]
Done!

**Comment by AlexandracmONRR** [comment]
Completed!

ENFJ-A ... this has changed pretty dramatically from when I took it 10 years ago :D

**Comment by lpgoldstein** [comment]
ENTJ-A not sure I agree with all of it. Now I need to do the enneagram!
