### ISSUE TITLE
Fix text on this annoucement card

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/onrr.gov-site#3270]
![image](https://github.com/user-attachments/assets/cf52e2cc-240d-429f-a8d0-19bca5ab1d55)

https://onrr.gov/indian

**Comment by AlexandracmONRR** [comment]
Fixed text:

**Comment by lpgoldstein** [comment]
ONRR no longer provides distribution estimates. The last estimates were provided during the week of October 11, 2022. However, ONRR will still be available to answer any questions not related to estimates. @AlexandracmONRR
