### ISSUE TITLE
Update Information on New Reporter Checklist

### ISSUE THREAD

**Issue by theresabodus** [DOI-ONRR/onrr.gov-site#3275]
Hello,

Location on ONRR.GOV:

The New Reporter Checklist located on bottom left side of the ONRR.gov page: url below

https://onrr.gov/getting-started/new-reporter-checklist

![image](https://github.com/user-attachments/assets/55dcbe97-8cb8-4314-84d7-dbfe87f0a9ff)

The page begins with get an Outer Continental Shelf (OCS) number....  

Problem: The phone numbers for each region change.   Currently the phone numbers for Pacific and Gulf are no longer in service.   Rather than remember to check numbers and enter GitHub tickets we would like the phone numbers in each section to link to the following BOEM page 

https://www.boem.gov/about-boem/contact-us

OR

If you would like to eliminate the boxes (Alaska Region, Gulf Coast Region, Pacific Region) and add a sentence to the upper paragraph which states:  Contact information to obtain an Outer Continental Shelf (OCS) number can be found at https://www.boem.gov/about-boem/contact-us 

Then move the final sentence (You need to wait.....) up to the end of that paragraph.  

Either solution works.   Please execute whichever is the easiest for you.  

Theresa

**Comment by cthomasONRR** [comment]
@theresabodus 
How does this look? https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?tabs=oil-gas-production
Please review and let me know if you want any changes.
Thanks,
Christine

**Comment by theresabodus** [comment]
That looks great!    Thank you!


From: Christine Thomas ***@***.***>
Sent: Tuesday, August 27, 2024 1:21 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bodus, Theresa M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Information on New Reporter Checklist (Issue #3275)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@theresabodus<https://github.com/theresabodus>
How does this look? https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?tabs=oil-gas-production
Please review and let me know if you want any changes.
Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@theresabodus Great! These updates are now live: https://www.onrr.gov/getting-started/new-reporter-checklist?tabs=oil-gas-production
