### ISSUE TITLE
Please replace the existing active lease file

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3277]
Please replace the existing active lease file with the attached updated active lease file on the following webpage - [Reference Lists & Codes | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases).  Also please change Active Leases Updated Date to 8/29/2024

![image](https://github.com/user-attachments/assets/e0bec6cf-a137-4fb0-b8c6-48b0ea890db9)

[WP_ACTIVE_LEASES_1236821585.xlsx](https://github.com/user-attachments/files/16800742/WP_ACTIVE_LEASES_1236821585.xlsx)

**Comment by jasonDSTS** [comment]
@cthomasONRR I attached the wrong file!

**Comment by jasonDSTS** [comment]
[aLwState.xlsx](https://github.com/user-attachments/files/16800817/aLwState.xlsx)

**Comment by jasonDSTS** [comment]
Gawd Im so horrible at this!

**Comment by cthomasONRR** [comment]
@jasonDSTS No worries!
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us approval to go live.
Thanks,
Christine

**Comment by jasonDSTS** [comment]
Looks good please go live.

Thank you!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, August 29, 2024 8:43 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the existing active lease file (Issue #3277)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> No worries!
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us approval to go live.
Thanks,
Christine
