### ISSUE TITLE
Please replace the existing agreement file

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3279]
Please replace the existing agreement file with the attached updated agreement file on the following webpage under Reference Lists - [Oil & Gas Revenue | Office of Natural Resources Revenue (onrr.gov)](https://onrr.gov/reporting/revenue?tabs=references).

Also, please update the date updated to 08/29/2024
![image](https://github.com/user-attachments/assets/b794d9fe-9907-40dd-9003-fae20a5574f7)

Thanks!

Jason
[100pct fed agreements.xlsx](https://github.com/user-attachments/files/16803285/100pct.fed.agreements.xlsx)

**Comment by AlexandracmONRR** [comment]
@jasonDSTS - thank you for your submission. Please review the update on our [dev site](https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references). If you approve, let me know and I will publish live. Thank you!

**Comment by jasonDSTS** [comment]
Its good please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Alexandra C McNally ***@***.***>
Sent: Thursday, August 29, 2024 12:18 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the existing agreement file (Issue #3279)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> - thank you for your submission. Please review the update on our dev site<https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references>. If you approve, let me know and I will publish live. Thank you!

**Comment by AlexandracmONRR** [comment]
Update is now live. Thank you!
