### ISSUE TITLE
Slight change to wording on New Reporter Checklist

### ISSUE THREAD

**Issue by theresabodus** [DOI-ONRR/onrr.gov-site#3280]
Good Morning,

This text is found at https://onrr.gov/getting-started/new-reporter-checklist under oil and gas production.   This is a simplification of the earlier text.   The header, title and sentence beginning with Contact information and the link are all correct.   The rewrite is a combination of several sentences.   After management review they would like to change wording for sentences highlighted in grey below

![image](https://github.com/user-attachments/assets/01807f4f-f27c-4e44-be03-08109fee4d2b)

To read:

Call the appropriate regional office to apply for an OCS Qualification Number.   Before you can become an OCS bidder, lessee, assignee, operator or reporter, you will need the Qualification number.

Let me know if you have any questions.   Thanks.   Theresa

**Comment by cthomasONRR** [comment]
@theresabodus Good morning,
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist
![image](https://github.com/user-attachments/assets/db4de2e7-860a-496e-b233-196a892520ec)
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by theresabodus** [comment]
Looks great.  Please go live.

Thank you so much!   Theresa

From: Christine Thomas ***@***.***>
Sent: Tuesday, September 3, 2024 8:29 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Bodus, Theresa M (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Slight change to wording on New Reporter Checklist (Issue #3280)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@theresabodus<https://github.com/theresabodus> Good morning,
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist
image.png (view on web)<https://github.com/user-attachments/assets/db4de2e7-860a-496e-b233-196a892520ec>
Please review and give us your approval to go live.
Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@theresabodus Great! This is now live: https://www.onrr.gov/getting-started/new-reporter-checklist
