### ISSUE TITLE
Please replace the Minerals Revenue Reporter Handbook

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3281]
Please replace the Minerals Revenue Reporter Handbook with the attached.  The handbook is located at:
https://onrr.gov/references/handbooks

Also please update the link to Release 4.3:
![image](https://github.com/user-attachments/assets/6f0a61df-6156-4f20-af8b-06b6c4a1b25b)

Thanks!

Jason
[Minerals.Revenue.Handbook_4.3 version 508 pass.pdf](https://github.com/user-attachments/files/16871348/Minerals.Revenue.Handbook_4.3.version.508.pass.pdf)

**Comment by lpgoldstein** [comment]
@cthomasONRR assigning this to you so you can make sure that the link matches what we currently have because I'm sure the file name is different.

**Comment by cthomasONRR** [comment]
@jasonDSTS I did the Adobe automated accessibility check, and several errors are showing. Could yo double check to make sure you sent the correct document? When doing the check, make sure you have 32 or 32 checking options selected.
![image](https://github.com/user-attachments/assets/064dd889-1b24-48e4-829e-7064c1b9bd94)
![image](https://github.com/user-attachments/assets/fee571d0-26cd-47ca-bccc-0ae0ced958ad)

**Comment by jasonDSTS** [comment]
Hi Christine,

I was afraid of that.  I couldn't figure out how to fix them.  So you're telling me "Skip Rule" is not the answer, lol.  Okay I'll get back to work on it.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, September 4, 2024 12:41 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the Minerals Revenue Reporter Handbook (Issue #3281)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> I did the Adobe automated accessibility check, and several errors are showing. Could yo double check to make sure you sent the correct document? When doing the check, make sure you have 32 or 32 checking options selected.
image.png (view on web)<https://github.com/user-attachments/assets/064dd889-1b24-48e4-829e-7064c1b9bd94>
image.png (view on web)<https://github.com/user-attachments/assets/fee571d0-26cd-47ca-bccc-0ae0ced958ad>

**Comment by cthomasONRR** [comment]
@jasonDSTS I'd recommend going back to the Word version of the document and make sure it passes Microsoft's automated checks. After that, then convert to PDF. The PDF won't be perfect but likely will have less issues.

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, September 4, 2024 7:12:58 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the Minerals Revenue Reporter Handbook (Issue #3281)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> I'd recommend going back to the Word version of the document and make sure it passes Microsoft's automated checks. After that, then convert to PDF. The PDF won't be perfect but likely will have less issues.

**Comment by jasonDSTS** [comment]
Corrected copy attached.  Thanks.
[Minerals.Revenue.Handbook_4.3 version 508 pass.pdf](https://github.com/user-attachments/files/16881616/Minerals.Revenue.Handbook_4.3.version.508.pass.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS Thanks, I appreciate your work!

This is now updated in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks
I also updated the release number on the interactive page: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=table-of-contents

Please review and give us approval to go live.

Thanks,
Christine

**Comment by jasonDSTS** [comment]
Thanks Christine,

It looks great.  Please go live.

Have a great day!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, September 5, 2024 6:47 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the Minerals Revenue Reporter Handbook (Issue #3281)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Thanks, I appreciate your work!

This is now updated in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks
I also updated the release number on the interactive page: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=table-of-contents

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS Great, this is now live:
https://www.onrr.gov/references/handbooks
https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook

**Comment by jasonDSTS** [comment]
[like]  Roach, Jason L (Federal) reacted to your message:
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, September 5, 2024 1:32:37 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please replace the Minerals Revenue Reporter Handbook (Issue #3281)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Great, this is now live:
https://www.onrr.gov/references/handbooks
https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook
