### ISSUE TITLE
Please Change Contact Info on ONRR.gov

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3282]
Please Change Contact Info on ONRR.gov to place Tony Demons first on the left followed by Stacey Lopez:

https://onrr.gov/getting-started/new-reporter-checklist?tabs=oil-gas-revenue

![image](https://github.com/user-attachments/assets/bacec9c6-a780-4223-b635-8cdaea8e441b)

**Comment by lpgoldstein** [comment]
@jasondsts this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?tabs=oil-gas-revenue

**Comment by jasonDSTS** [comment]
Looks great.  Please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, September 5, 2024 3:23 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Change Contact Info on ONRR.gov (Issue #3282)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> this is ready for your review: https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?tabs=oil-gas-revenue

**Comment by lpgoldstein** [comment]
@jasondsts these changes are live https://onrr.gov/getting-started/new-reporter-checklist?tabs=oil-gas-revenue
