### ISSUE TITLE
Please Update onrr.gov

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3286]
Please replace the downloadable excel, Federal Onshore Terminable Leases - sorted by Due Date, located at:

https://onrr.gov/reporting/revenue?tabs=references

with the attached spreadsheet.  Also, please change the Updated Date to today's date.

![image](https://github.com/user-attachments/assets/32cde4b5-b306-48da-bdef-0a80ae6b1304)

[20240905.xlsx](https://github.com/user-attachments/files/16898068/20240905.xlsx)

Thanks!

Jason

**Comment by cthomasONRR** [comment]
@jasonDSTS 
Thanks, this is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references
Please review and give us approval to go live.

**Comment by jasonDSTS** [comment]
Looks great.  Please go live.

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, September 5, 2024 11:51 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update onrr.gov (Issue #3286)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS>
Thanks, this is now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references
Please review and give us approval to go live.

**Comment by cthomasONRR** [comment]
@jasonDSTS Great! This is now live: https://www.onrr.gov/references/reference-lists?tabs=revenue-reporting-references
