### ISSUE TITLE
September Indian Index Zone prices ready for ONRR.gov

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#3287]
The September Indian Index Zone prices are ready to be posted on ONRR.gov
The spreadsheet is attached.

Thanks,
Cory Forgrave
[Indian_Index_Zone_2024_09.xlsx](https://github.com/user-attachments/files/16899805/Indian_Index_Zone_2024_09.xlsx)
@sudarr

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by forgravec** [comment]
The prices look good...Thanks.

Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, September 5, 2024 3:19 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] September Indian Index Zone prices ready for ONRR.gov (Issue #3287)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://github.com/forgravec> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by lpgoldstein** [comment]
@foregravec This is live: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
