### ISSUE TITLE
Please Replace Interactive Minerals Revenue Reporter Handbook Sections

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3292]
Please Replace Interactive Minerals Revenue Reporter Handbook Chapters located at:
https://onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=chapters
With the attached Chapters.

[Minerals Revenue Reporter Handbook Chapter 2 - Basic Reporting Principles.pdf](https://github.com/user-attachments/files/16934375/Minerals.Revenue.Reporter.Handbook.Chapter.2.-.Basic.Reporting.Principles.pdf)
[Minerals Revenue Reporter Handbook Chapter 6 - Adjustments, Recoupments, and Refunds.pdf](https://github.com/user-attachments/files/16934377/Minerals.Revenue.Reporter.Handbook.Chapter.6.-.Adjustments.Recoupments.and.Refunds.pdf)
[Minerals Revenue Reporter Handbook Chapter 5 - Interest for Federal and Indian Oil and Gas Leases.pdf](https://github.com/user-attachments/files/16934378/Minerals.Revenue.Reporter.Handbook.Chapter.5.-.Interest.for.Federal.and.Indian.Oil.and.Gas.Leases.pdf)
[Minerals Revenue Reporter Handbook Chapter 1 - About This Handbook.pdf](https://github.com/user-attachments/files/16934379/Minerals.Revenue.Reporter.Handbook.Chapter.1.-.About.This.Handbook.pdf)
[Minerals Revenue Reporter Handbook Chapter 7 - Reporting Geothermal Royalty and other Lease Payments.pdf](https://github.com/user-attachments/files/16934380/Minerals.Revenue.Reporter.Handbook.Chapter.7.-.Reporting.Geothermal.Royalty.and.other.Lease.Payments.pdf)
[Minerals Revenue Reporter Handbook Chapter 4 - Reporting Instructions by Transaction Code.pdf](https://github.com/user-attachments/files/16934381/Minerals.Revenue.Reporter.Handbook.Chapter.4.-.Reporting.Instructions.by.Transaction.Code.pdf)
[Minerals Revenue Reporter Handbook Chapter 8 - Electronic Reporting.pdf](https://github.com/user-attachments/files/16934382/Minerals.Revenue.Reporter.Handbook.Chapter.8.-.Electronic.Reporting.pdf)
[Minerals Revenue Reporter Handbook Chapter 9 - Online Rentals.pdf](https://github.com/user-attachments/files/16934383/Minerals.Revenue.Reporter.Handbook.Chapter.9.-.Online.Rentals.pdf)
[Minerals Revenue Reporter Handbook Chapter 3 - Electronic Form ONRR-2014.pdf](https://github.com/user-attachments/files/16934384/Minerals.Revenue.Reporter.Handbook.Chapter.3.-.Electronic.Form.ONRR-2014.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
Please review and give us approval to go live.
Thanks,
Christine

**Comment by jasonDSTS** [comment]
These all look good and can go live.

Thanks!

Jason
Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, September 9, 2024 1:15 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Interactive Minerals Revenue Reporter Handbook Sections (Issue #3292)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
Please review and give us approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS Chapter 3 is updated. Maybe try using "ctrl+F5" to refresh the PDF. Thanks!

**Comment by jasonDSTS** [comment]
Yep, that did the trick.  Please go live.

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, September 9, 2024 1:47 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Interactive Minerals Revenue Reporter Handbook Sections (Issue #3292)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> Chapter 3 is updated. Maybe try using "ctrl+F5" to refresh the PDF. Thanks!

**Comment by cthomasONRR** [comment]
@jasonDSTS Thanks, these are now live: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook
