### ISSUE TITLE
Please Replace Interactive Minerals Revenue Reporter Handbook Supplemental Information

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3293]
Please Replace Interactive Minerals Revenue Reporter Handbook Supplemental Information located at:
https://onrr.gov/references/handbooks/minerals-revenue-reporter-handbook?tabs=supplemental-information

With the attached files.

[Minerals Revenue Reporter Handbook Appendix C - Product Codes.pdf](https://github.com/user-attachments/files/16934413/Minerals.Revenue.Reporter.Handbook.Appendix.C.-.Product.Codes.pdf)
[Minerals Revenue Reporter Handbook Appendix E - Transaction Codes.pdf](https://github.com/user-attachments/files/16934414/Minerals.Revenue.Reporter.Handbook.Appendix.E.-.Transaction.Codes.pdf)
[Minerals Revenue Reporter Handbook Appendix B - ONRR Lease, Unit, or Communitization Number.pdf](https://github.com/user-attachments/files/16934415/Minerals.Revenue.Reporter.Handbook.Appendix.B.-.ONRR.Lease.Unit.or.Communitization.Number.pdf)
[Minerals Revenue Reporter Handbook Appendix D - Sales Type Codes.pdf](https://github.com/user-attachments/files/16934416/Minerals.Revenue.Reporter.Handbook.Appendix.D.-.Sales.Type.Codes.pdf)
[Minerals Revenue Reporter Handbook Glossary.pdf](https://github.com/user-attachments/files/16934417/Minerals.Revenue.Reporter.Handbook.Glossary.pdf)
[Minerals Revenue Reporter Handbook Abbreviations.pdf](https://github.com/user-attachments/files/16934418/Minerals.Revenue.Reporter.Handbook.Abbreviations.pdf)
[Minerals Revenue Reporter Handbook Appendix A - Contact Information.pdf](https://github.com/user-attachments/files/16934419/Minerals.Revenue.Reporter.Handbook.Appendix.A.-.Contact.Information.pdf)
[Minerals Revenue Reporter Handbook Appendix F - Adjustment Reason Codes.pdf](https://github.com/user-attachments/files/16934420/Minerals.Revenue.Reporter.Handbook.Appendix.F.-.Adjustment.Reason.Codes.pdf)
[Minerals Revenue Reporter Handbook Appendix G - Payment Method Codes.pdf](https://github.com/user-attachments/files/16934421/Minerals.Revenue.Reporter.Handbook.Appendix.G.-.Payment.Method.Codes.pdf)

**Comment by cthomasONRR** [comment]
@jasonDSTS These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
Please review and give us approval to go live.
Thanks,
Christine

**Comment by jasonDSTS** [comment]
Hi Christine,

Please verify Chapter 3 updated.  The rest look good.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, September 9, 2024 1:15 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Interactive Minerals Revenue Reporter Handbook Supplemental Information (Issue #3293)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
Please review and give us approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jasonDSTS Thanks, these are now live: https://www.onrr.gov/references/handbooks/minerals-revenue-reporter-handbook
