### ISSUE TITLE
Test existing Directus flows

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/onrr.gov-site#3297]
Let's create test plans for each existing Directus flow to ensure they are working as needed. Those that aren't working need to be fixed before we can reliably use all flows.

Here's the list of publishing flows:

- [x] Publish plant specific Ucas @lpgoldstein 
- [x] Publish press releases @lpgoldstein 
- [x] Publish reporter letters @lpgoldstein 
- [x] Publish pricing data @lpgoldstein 
    - [x] Index zones
    - [x] IBMP
    - [x] Indian gas major portion
    - [x] Nymex 
- [x] Publish redirects @lpgoldstein 
- [x] Publish tab blocks (consider removing) @cthomasONRR 
- [x] Publish contacts @cthomasONRR 
- [x] Publish handbooks @cthomasONRR 
    - [x] Revenue handbook
    - [x] Production handbook
    - [x] Solid minerals handbook
    - [x] Geothermal class 1
    - [x] Geothermal class 2 3
- [x] Publish announcements and rulemakings. @cthomasONRR 
- [x] Publish page content updates @cthomasONRR 
- [x] Publish interest @cthomasONRR 
    - [x] Interest oil and gas
    - [x] Interest solids

**Comment by cthomasONRR** [comment]
NOTES

- **Publish tab blocks (consider removing)**: Removed my 3 levels of tab blocks in the test-page dev. Went into preview, made a text edit in the tab block, then published to dev. All 3 levels republished to dev.
- **Publish contacts**:  Removed the Oil and Gas Rent contact in dev. Republished in preview, and back on dev site!
- **Revenue handbook**: Tested with abbreviations @greensomes not working, doc not getting back to dev with the flow
- Production handbook
- Solid minerals handbook
- Geothermal class 1 
- Geothermal class 2 3

**Comment by lpgoldstein** [comment]
@greensomes all of my flows work!
