### ISSUE TITLE
Update interest 

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3298]
Hello,

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas please make the following updates:

Add a new line at the top of the late payments & underpayments table for Period 10/1/2024-12/31/2024. Oil and gas remained the same at 8%.

On the late payment & Underpayment Interest tables page, at https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal please make the following updates:
Add a new line at the top of the late payment & underpayment table for period 10/1/2024-12/31/2024. Solid's remained the same at 4%.

Replace the Interest Calculator excel file at https://onrr.gov/paying/interest?tabs=interest-calculator with the attached below:

Thanks so much!

**Comment by Sheetsj** [comment]
I keep trying to add the file but it won't add on here for some reason

**Comment by Sheetsj** [comment]
Everything looks good. Thank you!

**Comment by cthomasONRR** [comment]
@Sheetsj Great! This is now live: https://www.onrr.gov/paying/interest?tabs=interest-rates,oil-gas
