### ISSUE TITLE
Dear Reporter Letter - Secure File Transfer and Multi-Factor Authentication Requirements 

### ISSUE THREAD

**Issue by MDanmandude** [DOI-ONRR/onrr.gov-site#3303]
[Signed Dear Reporter Letter Secure File Transfer 8-23-2024.pdf](https://github.com/user-attachments/files/16965399/Signed.Dear.Reporter.Letter.Secure.File.Transfer.8-23-2024.pdf)

Dear Reporter Letter - Secure File Transfer and Multi-Factor Authentication Requirements when providing records to the Office of Natural Resources Revenue

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:
Please post with other Dear Reporter Letters

**Comment by cthomasONRR** [comment]
@MDanmandude Sorry about that, please try again, it should be fixed. https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

**Comment by cthomasONRR** [comment]
Approved via Teams and now live.
