### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – Sept 2024

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#3308]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “Sept 2024 Lease Agreement XREF.txt" and "Sept 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 9/17/2024.

[Sept 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/17030376/Sept.2024.Lease.Agreement.XREF.xlsx)

[Sept 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/17030409/Sept.2024.Lease.Agreement.XREF.txt)

**Comment by lpgoldstein** [comment]
@StaceyKaiser This is ready for you: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by StaceyKaiser** [comment]
@lpgoldstein the data looks good and we request you move the data to the live site. Thank you!

**Comment by lpgoldstein** [comment]
@StaceyKaiser This is live! https://onrr.gov/references/reference-lists
