### ISSUE TITLE
Updates to ONRR.gov's Information Collection Request's Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#3317]
Good morning,

I am requesting updates to this page https://onrr.gov/references/icrs/1012-0001

Please add the bullet below under Federal Register Publications
"30-Day Agency Information Collection - (89 FR 77540--September 23, 2024)"

As a hyperlink to the (89 FR 77540--September 23, 2024) language, please add the link below https://www.federalregister.gov/documents/2024/09/23/2024-21613/agency-information-collection-activities-accounts-receivable-confirmations-reporting

Please let me know if you have any questions.
Thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley 

Good morning,
This update is in dev: https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0001
Please review and give us approval to go live.
Thanks,
Christine

**Comment by gingerhensley** [comment]
Approved. Thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley Great! This is now live: https://www.onrr.gov/references/icrs/1012-0001
