### ISSUE TITLE
Please Replace Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3345]
Please Replace Federal Onshore Terminable Leases located at:  https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references

And refresh the "updated date":

![image](https://github.com/user-attachments/assets/dfbe66bd-f4a4-4177-a268-a96e9571288c)

With the attached file.
[20241002.xlsx](https://github.com/user-attachments/files/17233970/20241002.xlsx)

**Comment by lpgoldstein** [comment]
@jasonDSTS This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by jasonDSTS** [comment]
Its good, please go live.

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, October 2, 2024 1:02 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Federal Onshore Terminable Leases (Issue #3345)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by lpgoldstein** [comment]
@jasonDSTS This is live: https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references
