### ISSUE TITLE
October 2024 Indian Index Zone prices

### ISSUE THREAD

**Issue by WW-Git-Hub** [DOI-ONRR/onrr.gov-site#3347]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

Please update w/ this months pricing.

@Sudarr
[Indian_Index_Zone_2024_10.xlsx](https://github.com/user-attachments/files/17235699/Indian_Index_Zone_2024_10.xlsx)

**Comment by WW-Git-Hub** [comment]
The posted prices are correct.

Thank you

@sudarr

**Comment by AlexandracmONRR** [comment]
@ww-Git-Hub - thank you for your review!

The Indian Index Zone prices are now live: https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
