### ISSUE TITLE
September 2024 NYMEX Prices

### ISSUE THREAD

**Issue by damionschulte** [DOI-ONRR/onrr.gov-site#3348]
All, Attached is the Nymex Prices for September 2024. Can you please publish them to the website? Please let me know if you need anything else from me. Thanks

Damion

[NYMEX092024.xlsx](https://github.com/user-attachments/files/17235928/NYMEX092024.xlsx)

@sudarr

**Comment by damionschulte** [comment]
These are perfect!  Thank you so much.

From: lpgoldstein ***@***.***>
Sent: Wednesday, October 2, 2024 3:53 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] September 2024 NYMEX Prices (Issue #3348)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://github.com/damionschulte> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

-

**Comment by lpgoldstein** [comment]
@damionschulte It's live!
