### ISSUE TITLE
Please Replace Active Agreements Spreadsheet

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3353]
Please Replace Active Agreements Spreadsheet at:

https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-agreements

with the attached spreadsheet, and refresh the Updated Date:

![image](https://github.com/user-attachments/assets/bd2247a4-fdae-4272-a7b1-dc4f31b7bfa4)
[saaname.xlsx](https://github.com/user-attachments/files/17281718/saaname.xlsx)

**Comment by lpgoldstein** [comment]
@jasonDSTS This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by jasonDSTS** [comment]
Looks good please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, October 7, 2024 12:27 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Active Agreements Spreadsheet (Issue #3353)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by lpgoldstein** [comment]
@jasonDSTS This is live
