### ISSUE TITLE
Please Replace Active Leases Spreadsheet at:

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3355]
Please Replace Active Agreements Spreadsheet at:

https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases

with attached spreadsheet, and refresh Updated Date

![image](https://github.com/user-attachments/assets/efb38b37-f7fa-4eca-a3a2-0cec81babc02)

[aLwState.xlsx](https://github.com/user-attachments/files/17282810/aLwState.xlsx)

**Comment by lpgoldstein** [comment]
@jasonDSTS This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by lpgoldstein** [comment]
@jasonDSTS live!
