### ISSUE TITLE
Please Add Highlighted Contact Info on "Onshore Production" Tab of Contacts Spreadsheet

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3359]
Please Add Highlighted Contact Info on "Onshore Production" Tab of Contacts Spreadsheet, located at:

https://doimspp.sharepoint.com/:x:/s/NRRD/ESwIhf6_I6hKjNDHFsPUpIsBuUYgyr4mA1mf9EzVtFNzGw?e=4%3APD43GM&CID=edc9d20c-bec9-daf8-2e44-0b8506cc001c

**Comment by lpgoldstein** [comment]
@jasondsts This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by jasonDSTS** [comment]
Review complete.  Please go live.

Thanks!

Jason


Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, October 9, 2024 11:57 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Add Highlighted Contact Info on "Onshore Production" Tab of Contacts Spreadsheet (Issue #3359)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
