### ISSUE TITLE
Update refund page

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3360]
Could you please place the following information on the refund request page located: https://onrr.gov/paying/payment-options?tabs=refunds

Please place it after the last sentence "All request for refund needs to be submitted to"

The following information is needed when requesting a refund: 
1.	Name and payor code of company.
2.	EIN/TIN/SSN
3.	Payment ID and/or PAD Number (Separated)
4.	Amount of each Payment and/or PAD number (Separated)
5.	Explanation for refund (How the overpayment occurred or what the payment was for and/or what the adjustment reporting pertains to). 
6.	Bank Name
7.	Bank Address
8.	Company name on Bank Account (if name does not match the company that the refund request is under, please provide the reason and documentation of proof of why the name is different). 
9.	Nine-digit ACH Routing Transit Number
10.	 Account Number
11.	Checking or Savings

**Comment by cthomasONRR** [comment]
@sheetsj

Thanks we are working on this issue! Our developer is making some updates right now and we'll let you know when it's ready to review. Thanks for your patience!

Christine

**Comment by jpetersononrr** [comment]
Hello @Sheetsj!  This is ready for your review:

https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tabs=refunds

Please let us know if you have any changes!  Thanks!

Jodie

**Comment by Sheetsj** [comment]
That looks perfect. Thank you!

**Comment by jpetersononrr** [comment]
@Sheetsj Great!  It is now live!  Thanks!

https://www.onrr.gov/paying/payment-options?tabs=refunds

Jodie
