### ISSUE TITLE
Update external org chart and tabs

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#3368]
https://onrr.gov/about/organization
https://onrr.gov/document/ONRR_External_Org_Chart.pptx

[ONRR_External_Org_Chart (2).pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGM1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb2fc4202544f134fd3d5018ff00fd359829a6df/ONRR_External_Org_Chart%20%282%29.pptx)

We need to lock the powerpoint and make sure it's saved with the right name.

- [x] Update team names under leadership tab
- [x] Update image under the org chart tab
- [x] Update file under the org chart image

**Comment by cthomasONRR** [comment]
Christina approved and it's live! Thanks Lindsay and Jodie for the team effort here!

**Comment by lpgoldstein** [comment]
@cthomasONRR and @jpetersononrr Thanks for working on this! Looks great in Edge but I'm not seeing the new image yet in Chrome. I'm sure it's a caching problem and will go away but just a heads up in case anyone else says anything.

**Comment by cthomasONRR** [comment]
@lpgoldstein Yeah I had to clear browsing data to see the new image in dev and live.
