### ISSUE TITLE
Add the FY 2025 Indian Distribution calendar and remove the FY 2023 calendar.

### ISSUE THREAD

**Issue by bakercook** [DOI-ONRR/onrr.gov-site#3375]
Hello. Please add the CY 2025 Disb memo to https://onrr.gov/indian/indian-references. Add under Royalty Distribution Dates. Remove the Indian Distribution Dates for Calendar Year 2023. Leave the calendar for CY 2024. Place the 2025 calendar above the 2024 calendar. This site should reflect both CY 2025 and CY 2024 when complete. 

<img width="246" alt="image" src="https://github.com/user-attachments/assets/0c6c58b7-1fac-438a-98e2-1d01ff18c2f2">

Thank you.

**Follow these directions**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the exact language that should go to that hyperlink url (if applicable) 
* Attach the new content file (if applicable)
[Indian Distribution Dates for Calendar Year 2025.pdf](https://github.com/user-attachments/files/17381059/Indian.Distribution.Dates.for.Calendar.Year.2025.pdf)

THANK YOU
______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE: Hello. Please add the CY 2025 Disb memo to https://onrr.gov/indian/indian-references. Add under Royalty Distribution Dates. Remove the Indian Distribution Dates for Calendar Year 2023. Leave the calendar for CY 2024. Place the 2025 calendar above the 2024 calendar. This site should reflect both CY 2025 and CY 2024 when complete.

**Comment by bakercook** [comment]
I did not add the title area. After https://onrr.gov/indian/indian-references, please go to the Indian References/References/Indian References/Royalty Distribution Dates. Thanks again.

**Comment by cthomasONRR** [comment]
@bakercook 
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/indian/indian-references
Please review and give us approval to go live.
Thanks,
Christine

**Comment by bakercook** [comment]
Hi Christine,

Looks good. I approve.
Thank you.

Respectfully,

Cheri Baker
Supervisor, Accounts Payable
Office of Natural Resources Revenue
Phone: 303-231-3137

From: Christine Thomas ***@***.***>
Sent: Tuesday, October 15, 2024 10:43 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Add the FY 2025 Indian Distribution calendar and remove the FY 2023 calendar. (Issue #3375)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://github.com/bakercook>
This update is now in dev: https://dev-onrr-frontend.app.cloud.gov/indian/indian-references
Please review and give us approval to go live.
Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@bakercook
Great! This is now live: https://www.onrr.gov/indian/indian-references
Closing issue.
Thanks,
Christine
