### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – October 2024

### ISSUE THREAD

**Issue by StaceyKaiser** [DOI-ONRR/onrr.gov-site#3376]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “Oct 2024 Lease Agreement XREF.txt" and "Oct 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 10/15/2024.

[October 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/17384219/October.2024.Lease.Agreement.XREF.txt)
[October 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/17384249/October.2024.Lease.Agreement.XREF.xlsx)

**Comment by jpetersononrr** [comment]
Hello!

This has been updated on the dev site:  https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

Please review and let us know if you have changes!  Thanks!

Jodie

**Comment by jpetersononrr** [comment]
Great!  @StaceyKaiser that is live!  Thanks!
