### ISSUE TITLE
Updates to ONRR.gov's Information Collection Request's Page

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#3395]
Good morning,

I am requesting updates to this page https://onrr.gov/references/icrs/1012-0003

Please add the bullet below under Federal Register Publications
"30-Day Agency Information Collection - (89 FR 87396--November 1, 2024)"

As a hyperlink to the (89 FR 87396--November 1, 2024) language, please add the link below https://www.federalregister.gov/documents/2024/11/01/2024-25421/agency-information-collection-activities-delegated-and-cooperative-activities-with-states-and-indian

Please let me know if you have any questions.
Thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley 

These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0003
Please review and give us approval to go live.

Thanks,
Christine

**Comment by gingerhensley** [comment]
Approved, thanks!

**Comment by cthomasONRR** [comment]
@gingerhensley Great, this is live: https://www.onrr.gov/references/icrs/1012-0003
Closing issue, thanks!
