### ISSUE TITLE
RV contact missing

### ISSUE THREAD

**Issue by jpetersononrr** [DOI-ONRR/onrr.gov-site#3397]
Royalty Valuation email dropped off the valuation and pricing contact page:  https://www.onrr.gov/references/valuation?tabs=contacts

**Comment by jpetersononrr** [comment]
@greensomes I created this.  Both Christine and I tried to push it.  It looks like a successful push but won't go through to dev.

**Comment by cthomasONRR** [comment]
This is now live. Closing issue.
