### ISSUE TITLE
ONRR.gov Indian Index Zone prices - November ready for publishing

### ISSUE THREAD

**Issue by forgravec** [DOI-ONRR/onrr.gov-site#3402]
The November Indian Index Zone prices are ready to be published on ONRR.gov.  The spreadsheet is attached.

Thanks
Cory Forgrave

@Sudarr
[Indian_Index_Zone_2024_11.xlsx](https://github.com/user-attachments/files/17639296/Indian_Index_Zone_2024_11.xlsx)

**Comment by lpgoldstein** [comment]
@forgravec ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by forgravec** [comment]
Prices look good...thanks

Cory Forgrave (he/him)
Economist, Market & Spatial Analytics
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, November 5, 2024 4:43 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] ONRR.gov Indian Index Zone prices - November ready for publishing (Issue #3402)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://github.com/forgravec> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by lpgoldstein** [comment]
@forgravec prices are live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by lpgoldstein** [comment]
https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
