### ISSUE TITLE
Test Directus upgrade 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/onrr.gov-site#3410]

**Comment by greensomes** [comment]
CMS link: [upgrade-onrr-cms.app.cloud.gov](https://upgrade-onrr-cms.app.cloud.gov)
Frontend link: [upgrade-onrr-frontend.app.cloud.gov](https://upgrade-onrr-frontend.app.cloud.gov)

**Comment by cthomasONRR** [comment]
Checklist

COMPONENTS
- [ ] content blocks
- [ ] card blocks
- [ ] tab blocks

COLLECTIONS
- [ ] UCAs
- [ ] late payment interest
- [ ] pricing: index zones
- [ ] pricing: ibmp
- [ ] pricing: indian gas major portion
- [ ] pricing: nymex
- [ ] reporter letters
- [ ] press releases
- [ ] announcements
- [ ] contacts
- [ ] handbook: revenue
- [ ] handbook: production
- [ ] handbook: solid minerals
- [ ] handbook: geothermal class 1
- [ ] handbook: geothermal class 2

TEXT EDITOR
- [ ] internal link
- [ ] external link
- [ ] document links: PDF, Word, Excel, Txt
- [ ] table functionality
- [ ] headings
- [ ] list
- [ ] image

**Comment by lpgoldstein** [comment]
link to internal docs not working in card block

**Comment by lpgoldstein** [comment]
card block colors not working

**Comment by AlexandracmONRR** [comment]
Agree with lindsay's comment and just adding that the card block icons are not working either.

**Comment by cthomasONRR** [comment]
Removed November index zone prices. Trying to re-upload November index zone prices, and getting this error when I go to re-add and save the November entry. It won't let me save the new entry, I've tried refreshing and can't get it to work. 

![image](https://github.com/user-attachments/assets/4e1be47e-a9f0-4369-bb71-cac3e17fd215)

**Comment by cthomasONRR** [comment]
I'm getting the same issue for IBMP... removed the September 2024 entry and can't get it back. I'm going to stop testing the pricing collections until this gets resolved.

**Comment by cthomasONRR** [comment]
Same broken file path issue with all handbooks: 
![image](https://github.com/user-attachments/assets/4bbf6f5c-147e-49eb-bae7-27c96dac282c)

**Comment by cthomasONRR** [comment]
Made issues for everything listed here.
