### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – November 2024

### ISSUE THREAD

**Issue by EckEmily** [DOI-ONRR/onrr.gov-site#3412]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________

Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “November 2024 Lease Agreement XREF.txt" and "November 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 11/13/2024.

[November 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/17734835/November.2024.Lease.Agreement.XREF.txt)
[November 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/17734865/November.2024.Lease.Agreement.XREF.xlsx)

**Comment by EckEmily** [comment]
PR is good and this can be moved to Prod. 

Thanks! 
Emily

**Comment by cthomasONRR** [comment]
@EckEmily Thanks! It's now live: https://www.onrr.gov/references/reference-lists
