### ISSUE TITLE
Directus upgrade: pricing collections issue

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3416]
Removed November index zone prices. Trying to re-upload November index zone prices, and getting this error when I go to re-add and save the November entry. It won't let me save the new entry, I've tried refreshing and can't get it to work. 

All pricing collections tested are giving me the same issue.

![image](https://github.com/user-attachments/assets/4e1be47e-a9f0-4369-bb71-cac3e17fd215)

**Comment by greensomes** [comment]
This has been fixed by adding the PUBLIC_URL environment variable to the manifest files. The previous way that it was set in config.js is no longer available outside of configuration.

It was the same issue for all pricing collections.
