### ISSUE TITLE
Nov - Dec 2024 Indian outreach events

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3426]
[EVENT CAL_NOV-DEC_2024 OUTREACHupdate.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a85770dc003d2949f5c2ae693790d61d6582e873/EVENT%20CAL_NOV-DEC_2024%20OUTREACHupdate.docx)

Good afternoon,
 
Please remove the previous events and post the attached updated Indian outreach event information for November and December 2024 to the ONRR events (Events | Office of Natural Resources Revenue (onrr.gov)) on onrr.gov.  If you have any questions, please let me know.
 
Thank you, 
 
Stephanie Manhalter

**Comment by jpetersononrr** [comment]
Approved via email.
