### ISSUE TITLE
Please Replace Spreadsheet on ONRR.gov

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3428]
Please replace Federal Terminable Onshore Leases spreadsheet located at:

https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references

![image](https://github.com/user-attachments/assets/3532b35b-0c10-401c-9591-68320e12e782)

with the attached spreadsheet, and please change the updated date to today's date.

[20241119.xlsx](https://github.com/user-attachments/files/17819007/20241119.xlsx)

**Comment by jpetersononrr** [comment]
Hello @jasonDSTS!

Please see this following for the updated link.  Let me know if any changes are necessary.  Thanks!

Jodie
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by jasonDSTS** [comment]
Looks good.  Please go live.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: jpetersononrr ***@***.***>
Sent: Tuesday, November 19, 2024 12:03 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Replace Spreadsheet on ONRR.gov (Issue #3428)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hello @jasonDSTS<https://github.com/jasonDSTS>!

Please see this following for the updated link. Let me know if any changes are necessary. Thanks!

Jodie
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-references

**Comment by jpetersononrr** [comment]
Great!  This is now live.  Thanks!

https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references
