### ISSUE TITLE
Review new Osage language

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/onrr.gov-site#3430]
All new text in red.

**VALUATION & PRICING PAGES:**
- [x] Main pricing tab https://preview-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing
    - Added Osage CFR cite, and specified non-Osage in pricing on Indian lands
    
- [x] Indian Gas Index Zone https://preview-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone
    - Added non-Osage to heading
    
- [x] IBMP https://preview-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion
    - Added non-Osage to heading
    
- [x] Indian gas major portion https://preview-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-major-portion
    - Added non-Osage to heading
    
**INDIAN PRICING PAGES:**
- [x] Main pricing page https://preview-onrr-frontend.app.cloud.gov/indian/indian-pricing
    - Added sentence about non-osage pricing (consistent with Valuation & Pricing page).
    - Added link to Osage pricing
    
- [x] How to value gas https://preview-onrr-frontend.app.cloud.gov/indian/indian-pricing?tabs=how-to-value,gas
    - Added non-Osage to heading
    
- [x] How to value oil  https://preview-onrr-frontend.app.cloud.gov/indian/indian-pricing?tabs=how-to-value,oil
    - Added non-Osage to heading
 
**VALUATION REGULATIONS PAGE:**
- [x] https://preview-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-regulations
    - Added non-Osage to Indian rows in Oil and Gas tables (can't color text in tables as red)
    - Need more info on the rulemakings/regulations before I can add a new row for Osage in these tables.

**Comment by AlexandracmONRR** [comment]
This is more of a question for you about my prototype, The title of "Osage Crude Oil and Natural Gas" is very long to include in a tab name, so I shortened it to "Osage Oil & Gas". Do you think it is okay if these don't match exactly at the title of the sub-tab because it is being more specific? Or, do you think that both titles should match?

![image](https://github.com/user-attachments/assets/1ee7ba18-55b6-45ba-9c6b-f6d3c5c737d7)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I think "Osage Oil & Gas" is fine for the tab... we don't specify natural gas and crude oil in any of the other tabs.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR 

The [Indian Pricing page, Osage Oil & Gas tab](https://preview-onrr-frontend.app.cloud.gov/indian/indian-pricing?tabs=osage-oil-gas) may still be under construction, but this tab for Action 2 is missing the accordions for the tables (to be similar to the same tab on the Pricing page).



![image](https://github.com/user-attachments/assets/0e771316-4c6e-4ca5-8d4c-c8486a03c840)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Fixed

**Comment by lpgoldstein** [comment]
Thanks for working on this! One question - is the text supposed to be larger in the valuations regulations rulemakings table? <img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37846eb3c84d8bcd577b3e8dea2b4ada70bca400/image.png" alt="image.png" />

**Comment by cthomasONRR** [comment]
@lpgoldstein The last row in all tables right now has larger text... we have issue #3403 set to fix it.

**Comment by cthomasONRR** [comment]
@lpgoldstein @AlexandracmONRR @jpetersononrr If everyone has reviewed and is ok with these updates, I'll change the text to black and close this issue.

**Comment by jpetersononrr** [comment]
Looks good to me!

**Comment by cthomasONRR** [comment]
All text is now in black. Closing issue.

Remember to NOT publish anything from Valuation & Pricing and Indian Pricing webpages... doing so will move the Osage content from preview to dev then live.
