### ISSUE TITLE
Directus upgrade: overlay issue in ONRR editor

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/onrr.gov-site#3433]

**Comment by cthomasONRR** [comment]
@greensomes The box is there now, but now I'm not seeing the text editor, just the code

![image](https://github.com/user-attachments/assets/9a445fda-b591-4008-89a9-82f274d08f0a)

**Comment by cthomasONRR** [comment]
@greensomes I did a hard refresh and I'm seeing the updates now!

![image](https://github.com/user-attachments/assets/48832e7d-134f-4b09-b043-9f67a367758d)
