### ISSUE TITLE
Test flows between upgrade instance and dev

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/onrr.gov-site#3438]
https://upgrade-onrr-cms.app.cloud.gov/
https://upgrade-onrr-frontened.app.cloud.gov

Here's a checklist based on the top-level flows:

- [x] Pages
- [x] Documents
- [x] Plant-specific UCAs
- [x] Handbooks
- [x] Reporter letters
- [x] Announcements
- [x] Rulemakings
- [x] Pricing data
- [x] Contacts
- [x] Press Releases

**Comment by cthomasONRR** [comment]
I removed content and card blocks from the test page on the upgrade CMS. Did the flow, and not seeing the content removed within dev frontend. I don't think the flow is working for Pages.

**Comment by cthomasONRR** [comment]
Plant-Specific UCAs - I removed the Ramsey UCA from the collection and also the document file folder. Dev did not update to show that it's been removed.

**Comment by cthomasONRR** [comment]
I removed the deliveries announcement and added a new test announcement. Neither made it to dev frontend. I'm going to pause testing until I can talk to Jeff.

**Comment by greensomes** [comment]
Both announcements (new/update) and the pages flow are ready for retest.

**Comment by cthomasONRR** [comment]
Announcements flow working, but need to add ordering in reverse chronological order by "Published On" date.

**Comment by cthomasONRR** [comment]
@greensomes I added an additional topic to an existing reporter letter, and the new topic isn't showing in dev after running the flow

UCAs are working (testing by modifying the info within an existing collection entry, and the flow to dev worked). And so are Handbooks (same testing method as UCAs).

**Comment by cthomasONRR** [comment]
@greensomes I'm testing Indian Gas Index Zones... I removed the December monthly entry from dev CMS, added it to the upgrade CMS, ran the flow, and seeing it on the dev site. BUT, the November monthly entry disappeared from the dev CMS and dev site when I tested December. The Nov entry is still within the upgrade CMS, but the flow isn't working to get it back to dev. Super weird.

**Comment by cthomasONRR** [comment]
@greensomes IBMP is being a bit weird, I have the October entry in the uppgrade CMS with the October date: 
![image](https://github.com/user-attachments/assets/649813b0-6bfc-42a2-a030-bfbed231ac98)

When I run the flow, the October entry is there, but it changes the date to September:
![image](https://github.com/user-attachments/assets/cfccf090-266a-463d-9ca9-b8df8d6afa98)

**Comment by cthomasONRR** [comment]
NYMEX worked perfectly!

**Comment by cthomasONRR** [comment]
I experienced the same ID issue with Contacts as we saw in Reporter Letters. Once I cleaned up the ID instances, the flow worked. Press Releases also worked!

**Comment by cthomasONRR** [comment]
Rulemakings works too!
