### ISSUE TITLE
Please Modify "Leases & Agreements" Tab

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3444]
Please make highlighted change to "Leases & Agreements" Tab at:

https://doimspp.sharepoint.com/:x:/s/NRRD/ESwIhf6_I6hKjNDHFsPUpIsBuUYgyr4mA1mf9EzVtFNzGw?e=4%3APD43GM&CID=edc9d20c-bec9-daf8-2e44-0b8506cc001c

**Comment by lpgoldstein** [comment]
@jasonDSTS should "Indian" be added in front of the new 2nd contact in Geothermal? that's what we currently have on the contact card.

**Comment by jasonDSTS** [comment]
Hi Lindsay,

I think the highlighted change is correct, no need to add "Indian"

Thanks!

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, December 5, 2024 1:23 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Modify "Leases & Agreements" Tab (Issue #3444)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> should "Indian" be added in front of the new 2nd contact in Geothermal? that's what we currently have on the contact card.

**Comment by lpgoldstein** [comment]
@jasonDSTS ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by jasonDSTS** [comment]
I'm sorry, Lindsay.  Is this still open?  I've lost track.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, December 5, 2024 2:56 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Modify "Leases & Agreements" Tab (Issue #3444)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts

**Comment by lpgoldstein** [comment]
It is - are you ready to go live?


Lindsay Goldstein (she/her)
Office of Natural Resources Revenue
Open Data, Design, & Development
303-231-3301
***@***.***
________________________________
From: jasonDSTS ***@***.***>
Sent: Monday, December 9, 2024 8:40 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Goldstein, Lindsay P (Federal) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Modify "Leases & Agreements" Tab (Issue #3444)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I'm sorry, Lindsay. Is this still open? I've lost track.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, December 5, 2024 2:56 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Modify "Leases & Agreements" Tab (Issue #3444)




This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jasonDSTS<https://github.com/jasonDSTS> ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
