### ISSUE TITLE
Dec 2024 Indian Index Zone prices 

### ISSUE THREAD

**Issue by WW-Git-Hub** [DOI-ONRR/onrr.gov-site#3445]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please post the attached Dec 2024 Indian Index Zone prices to ONRR.gov

[Indian_Index_Zone_2024_12.xlsx](https://github.com/user-attachments/files/18023735/Indian_Index_Zone_2024_12.xlsx)

@Sudarr

**Comment by jpetersononrr** [comment]
@WW-Git-Hub @sudarr please see this page for the updates.  Let me know if it is set to go live.  Thanks!

https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

Jodie

**Comment by WW-Git-Hub** [comment]
Thanks!   This is ready for posting.

@sudarr

**Comment by jpetersononrr** [comment]
Great!  @WW-Git-Hub it's live!  Thanks!

Jodie
