### ISSUE TITLE
Update Federal AR Accountants

### ISSUE THREAD

**Issue by Sheetsj** [DOI-ONRR/onrr.gov-site#3446]
Hello,

The federal AR Accountants and their backups have been changed due to the reorganization. I have attached the spreadsheet with all the updates. Please update the Accountants contact for the Federal Accounts Receivable which can be found: https://onrr.gov/about/contact/paying-contacts?tabs=contacts,federal-accounts-receivable. 

[FederalIndian.Accounts.Receivable..xlsx](https://github.com/user-attachments/files/18027670/FederalIndian.Accounts.Receivable.xlsx)

The IND tab was not changed. Let me know if you have any questions or concerns. Thanks!

**Comment by cthomasONRR** [comment]
@Sheetsj Hello! I have your issue and will be able to make this update tomorrow. Thanks for your patience!

**Comment by cthomasONRR** [comment]
@Sheetsj 
I had some time between meetings! This is in dev: https://dev-onrr-frontend.app.cloud.gov/about/contact/paying-contacts?tabs=contacts,federal-accounts-receivable 

Please review and let me know if any modifications should be made.

Thanks,
Christine

**Comment by Sheetsj** [comment]
Everything looks good. Thank you Christine.

**Comment by cthomasONRR** [comment]
@Sheetsj Great, this is now live: https://www.onrr.gov/about/contact/paying-contacts?tabs=contacts,federal-accounts-receivable

Closing issue.
