### ISSUE TITLE
November 2024 NYMEX prices

### ISSUE THREAD

**Issue by penvosej** [DOI-ONRR/onrr.gov-site#3447]
Hello web team! Can you please post the NYMEX and NYMEX Roll prices to the ONRR.gov website? The file you need is attached. Thank you!

@sudarr
[NYMEX112024.xlsx](https://github.com/user-attachments/files/18028158/NYMEX112024.xlsx)

**Comment by jpetersononrr** [comment]
@penvosej @sudarr Please review this page and let me know if you have changes before we push it live.  Thanks!

https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

Jodie

**Comment by jpetersononrr** [comment]
Great!  It is live!  Thanks!

Jodie
https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
