### ISSUE TITLE
Updates to ONRR.gov's Information Collection Requests

### ISSUE THREAD

**Issue by gingerhensley** [DOI-ONRR/onrr.gov-site#3454]
Good morning,

I am requesting updates to this page https://onrr.gov/references/icrs/1012-0002

Please add the bullet below under Federal Register Publications
"60-Day Agency Information Collection - (89 FR 90734--November 18, 2024)"

As a hyperlink to the (89 FR 90734--November 18, 2024) language, please add the link below https://www.federalregister.gov/documents/2024/11/18/2024-26847/agency-information-collection-activities-indian-oil-and-gas-valuation

Please let me know if you have any questions.
Thanks!

**Comment by jpetersononrr** [comment]
Hi @gingerhensley!  Please let me know if this looks good!  Thanks!

https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0002

Jodie

**Comment by gingerhensley** [comment]
Looks great, thank you!
