### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – December 2024

### ISSUE THREAD

**Issue by aalveari1** [DOI-ONRR/onrr.gov-site#3458]
Please replace the existing file located at: https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “December 2024 Lease Agreement XREF.txt" and "December 2024 Lease Agreement XREF.xlsx”.  The data was queried from the system on 12/11/2024.
[December 2024 Lease Agreement XREF.txt](https://github.com/user-attachments/files/18097423/December.2024.Lease.Agreement.XREF.txt)
[December 2024 Lease Agreement XREF.xlsx](https://github.com/user-attachments/files/18097425/December.2024.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@aalveari1 Good morning, this update is now in dev: 
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
Please review and give us approval to go live.
Thanks,
Christine

**Comment by aalveari1** [comment]
Peer review has been successfully completed. The files can be moved to the live site. Thank you!

**Comment by cthomasONRR** [comment]
@aalveari1 Great! This is now live: https://www.onrr.gov/references/reference-lists
Closing issue.
Thanks,
Christine
