### ISSUE TITLE
Update Password Issues and System Lockouts (ONRR website)

### ISSUE THREAD

**Issue by merrellc** [DOI-ONRR/onrr.gov-site#3470]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**
Please update "Password Issues and System Lockouts on the ONRR website located at -
https://onrr.gov/getting-started/system-access?tabs=troubleshooting
under -
![image](https://github.com/user-attachments/assets/c2ea3a03-ee67-42d1-aa22-fc2297eda8c9)
See attached document -
[Password_Reset-AL Review.docx](https://github.com/user-attachments/files/18189897/Password_Reset-AL.Review.docx)
Thank you!

**Comment by cthomasONRR** [comment]
@merrellc 

These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting

![image](https://github.com/user-attachments/assets/90c33607-aeb9-4e9b-b949-52cadf87261f)

Please review and give us approval to go live.

Thanks,
Christine

**Comment by merrellc** [comment]
Good morning, approval to go live.

Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3517
***@***.***

"The timeless in you is aware of life’s timelessness. And knows that yesterday is but today’s memory and tomorrow is today’s dream." – Kahlil Gibran

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, December 18, 2024 4:55 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Password Issues and System Lockouts (ONRR website) (Issue #3470)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://github.com/merrellc>

These updates are in dev: https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access?tabs=troubleshooting

image.png (view on web)<https://github.com/user-attachments/assets/90c33607-aeb9-4e9b-b949-52cadf87261f>

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc 
Good morning, this is now live:
https://www.onrr.gov/getting-started/system-access?tabs=troubleshooting
Closing issue.
Thanks,
Christine

**Comment by merrellc** [comment]
Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3517
***@***.***

"The timeless in you is aware of life’s timelessness. And knows that yesterday is but today’s memory and tomorrow is today’s dream." – Kahlil Gibran

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, December 19, 2024 7:52 AM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Update Password Issues and System Lockouts (ONRR website) (Issue #3470)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://github.com/merrellc>
Good morning, this is now live:
https://www.onrr.gov/getting-started/system-access?tabs=troubleshooting
Closing issue.
Thanks,
Christine
