### ISSUE TITLE
Please Update Contact Info Under New Reporter Checklist

### ISSUE THREAD

**Issue by jasonDSTS** [DOI-ONRR/onrr.gov-site#3473]
At location:  https://onrr.gov/reporting/revenue?tabs=new-reporter-checklist

Under the expandable menu:
![image](https://github.com/user-attachments/assets/3d09d6c7-92b2-4842-8c3f-dba995587e8d)

Please change the bold font in the box on the left to read:  "Email Address for W-9 and ONRR-4444"

**Comment by jasonDSTS** [comment]
Whoops I meant the box on the right...grrr sorry!
![image](https://github.com/user-attachments/assets/37a12848-88d5-4f34-a9bd-c6a61ba58e21)

**Comment by jpetersononrr** [comment]
Hello @jasonDSTS!  Let me know if this looks good to publish!

https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=new-reporter-checklist

**Comment by jasonDSTS** [comment]
Looks good.  Please publish.

Thanks,

Jason

Jason L. Roach
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
Office Phone: (303) 231-3025

This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.
________________________________
From: jpetersononrr ***@***.***>
Sent: Monday, December 30, 2024 12:58 PM
To: DOI-ONRR/onrr.gov-site ***@***.***>
Cc: Roach, Jason L (Federal) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-ONRR/onrr.gov-site] Please Update Contact Info Under New Reporter Checklist (Issue #3473)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hello @jasonDSTS<https://github.com/jasonDSTS>! Let me know if this looks good to publish!

https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=new-reporter-checklist

**Comment by jpetersononrr** [comment]
Great!  It is live!  Happy New year!

https://onrr.gov/reporting/revenue?tabs=new-reporter-checklist

Jodie
